CREATE TABLE IF NOT EXISTS submissions (
  visitor_hash TEXT PRIMARY KEY,
  caq INTEGER NOT NULL CHECK (caq BETWEEN 0 AND 100),
  pcq INTEGER NOT NULL CHECK (pcq BETWEEN 0 AND 100),
  pq INTEGER NOT NULL CHECK (pq BETWEEN 0 AND 100),
  plq INTEGER NOT NULL CHECK (plq BETWEEN 0 AND 100),
  qs INTEGER NOT NULL CHECK (qs BETWEEN 0 AND 100),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS submissions_created_at ON submissions(created_at);
