(()=>{"use strict";
const G={K:"♔",Q:"♕",R:"♖",B:"♗",N:"♘",P:"♙",k:"♚",q:"♛",r:"♜",b:"♝",n:"♞",p:"♟"},N={K:"Mothership",Q:"Overmind",R:"Fortress",B:"Seer",N:"Strider",P:"Drone"},V={p:100,n:320,b:330,r:500,q:900,k:20000},F="abcdefgh",E=c=>c==="w"?"b":"w",C=p=>!p||p==="."?null:p===p.toUpperCase()?"w":"b",RC=i=>[Math.floor(i/8),i%8],I=(r,c)=>r*8+c,IN=(r,c)=>r>=0&&r<8&&c>=0&&c<8;
const boardEl=document.querySelector("#board"),statusEl=document.querySelector("#status"),logEl=document.querySelector("#moveLog"),thinking=document.querySelector("#thinking"),mode=document.querySelector("#mode"),difficulty=document.querySelector("#difficulty"),musicButton=document.querySelector("#musicToggle");let game,selected=null,selectedMoves=[],flipped=false,busy=false,history=[],moveNames=[];
const spaceMusic={enabled:true,activated:false,running:false,ac:null,master:null,compressor:null,output:null,timer:null,step:0};
const fresh=()=>({board:[..."rnbqkbnrpppppppp................................PPPPPPPPRNBQKBNR"],turn:"w",castling:{K:true,Q:true,k:true,q:true},enPassant:-1,lastMove:null});
const clone=s=>({board:[...s.board],turn:s.turn,castling:{...s.castling},enPassant:s.enPassant,lastMove:s.lastMove?{...s.lastMove}:null});
function attacked(s,sq,by){const[tr,tc]=RC(sq),pawn=by==="w"?"P":"p",pr=by==="w"?tr+1:tr-1;for(const dc of[-1,1])if(IN(pr,tc+dc)&&s.board[I(pr,tc+dc)]===pawn)return true;const knight=by==="w"?"N":"n";for(const[dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])if(IN(tr+dr,tc+dc)&&s.board[I(tr+dr,tc+dc)]===knight)return true;for(const[dr,dc,t]of[[-1,0,"rq"],[1,0,"rq"],[0,-1,"rq"],[0,1,"rq"],[-1,-1,"bq"],[-1,1,"bq"],[1,-1,"bq"],[1,1,"bq"]]){let r=tr+dr,c=tc+dc;while(IN(r,c)){const p=s.board[I(r,c)];if(p!=="."){if(C(p)===by&&t.includes(p.toLowerCase()))return true;break}r+=dr;c+=dc}}const king=by==="w"?"K":"k";for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if((dr||dc)&&IN(tr+dr,tc+dc)&&s.board[I(tr+dr,tc+dc)]===king)return true;return false}
function checked(s,color){const k=s.board.indexOf(color==="w"?"K":"k");return k>=0&&attacked(s,k,E(color))}
function pseudo(s,from){const p=s.board[from],color=C(p);if(!color)return[];const[r,c]=RC(from),type=p.toLowerCase(),out=[],add=(to,x={})=>{const target=s.board[to];if(target==="."||C(target)!==color)out.push({from,to,piece:p,captured:target,...x})};if(type==="p"){const d=color==="w"?-1:1,start=color==="w"?6:1,promo=color==="w"?0:7;if(IN(r+d,c)&&s.board[I(r+d,c)]==="."){add(I(r+d,c),r+d===promo?{promotion:"q"}:{});if(r===start&&s.board[I(r+2*d,c)]===".")add(I(r+2*d,c),{doublePawn:true})}for(const dc of[-1,1])if(IN(r+d,c+dc)){const to=I(r+d,c+dc);if((s.board[to]!=="."&&C(s.board[to])!==color)||to===s.enPassant)add(to,{enPassant:to===s.enPassant,promotion:r+d===promo?"q":undefined})}}else if(type==="n")for(const[dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]]){if(IN(r+dr,c+dc))add(I(r+dr,c+dc))}else if("brq".includes(type)){const ds=type==="b"?[[-1,-1],[-1,1],[1,-1],[1,1]]:type==="r"?[[-1,0],[1,0],[0,-1],[0,1]]:[[-1,-1],[-1,1],[1,-1],[1,1],[-1,0],[1,0],[0,-1],[0,1]];for(const[dr,dc]of ds){let nr=r+dr,nc=c+dc;while(IN(nr,nc)){const to=I(nr,nc);add(to);if(s.board[to]!==".")break;nr+=dr;nc+=dc}}}else{for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if((dr||dc)&&IN(r+dr,c+dc))add(I(r+dr,c+dc));const home=color==="w"?60:4,opp=E(color);if(from===home&&!checked(s,color)){const ks=color==="w"?"K":"k",qs=color==="w"?"Q":"q";if(s.castling[ks]&&s.board[home+1]==="."&&s.board[home+2]==="."&&!attacked(s,home+1,opp)&&!attacked(s,home+2,opp))add(home+2,{castle:"king"});if(s.castling[qs]&&s.board[home-1]==="."&&s.board[home-2]==="."&&s.board[home-3]==="."&&!attacked(s,home-1,opp)&&!attacked(s,home-2,opp))add(home-2,{castle:"queen"})}}return out}
function apply(s,m){const n=clone(s),color=C(m.piece),[fr,fc]=RC(m.from),[tr]=RC(m.to);n.board[m.from]=".";n.board[m.to]=m.promotion?(color==="w"?m.promotion.toUpperCase():m.promotion):m.piece;if(m.enPassant)n.board[m.to+(color==="w"?8:-8)]=".";if(m.castle){const rf=m.castle==="king"?m.to+1:m.to-2,rt=m.castle==="king"?m.to-1:m.to+1;n.board[rt]=n.board[rf];n.board[rf]="."}n.enPassant=m.doublePawn?I((fr+tr)/2,fc):-1;if(m.piece==="K"){n.castling.K=false;n.castling.Q=false}if(m.piece==="k"){n.castling.k=false;n.castling.q=false}if(m.from===63||m.to===63)n.castling.K=false;if(m.from===56||m.to===56)n.castling.Q=false;if(m.from===7||m.to===7)n.castling.k=false;if(m.from===0||m.to===0)n.castling.q=false;n.turn=E(s.turn);n.lastMove={from:m.from,to:m.to};return n}
function legal(s,color=s.turn){const out=[];for(let i=0;i<64;i++)if(C(s.board[i])===color)for(const m of pseudo(s,i))if(!checked(apply(s,m),color))out.push(m);return out}
function musicContext(){try{const ac=spaceMusic.ac||=new(window.AudioContext||window.webkitAudioContext)();if(ac.state==="suspended")ac.resume();if(!spaceMusic.master){spaceMusic.output=ac.createGain();spaceMusic.output.gain.value=1.2;spaceMusic.compressor=ac.createDynamicsCompressor();spaceMusic.compressor.threshold.value=-20;spaceMusic.compressor.knee.value=24;spaceMusic.compressor.ratio.value=5;spaceMusic.compressor.attack.value=.006;spaceMusic.compressor.release.value=.25;spaceMusic.master=ac.createGain();spaceMusic.master.gain.value=.0001;spaceMusic.master.connect(spaceMusic.compressor);spaceMusic.compressor.connect(spaceMusic.output);spaceMusic.output.connect(ac.destination)}return ac}catch{return null}}
function elevatorTone(frequency,duration,volume,type="sine",pan=0){const ac=musicContext();if(!ac||!spaceMusic.master)return;const now=ac.currentTime,oscillator=ac.createOscillator(),filter=ac.createBiquadFilter(),gain=ac.createGain(),stereo=ac.createStereoPanner?.();oscillator.type=type;oscillator.frequency.value=frequency;filter.type="lowpass";filter.frequency.value=type==="sine"?1100:1750;filter.Q.value=.55;gain.gain.setValueAtTime(volume,now);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);oscillator.connect(filter);filter.connect(gain);if(stereo){stereo.pan.value=pan;gain.connect(stereo);stereo.connect(spaceMusic.master)}else gain.connect(spaceMusic.master);oscillator.start(now);oscillator.stop(now+duration+.03)}
function elevatorBeat(){if(!spaceMusic.running)return;const chords=[[261.63,329.63,392,493.88],[220,261.63,329.63,392],[293.66,349.23,440,523.25],[196,246.94,293.66,349.23]],step=spaceMusic.step++,chord=chords[Math.floor(step/4)%chords.length],note=chord[step%4];if(step%4===0){chord.forEach((frequency,index)=>elevatorTone(frequency/2,2.45,.009,"sine",(index-1.5)*.12));elevatorTone(chord[0]/4,1.15,.022,"triangle",0)}elevatorTone(note,.52,.028,"triangle",step%2? .22:-.22);if(step%8===6){elevatorTone(note*2,.85,.014,"sine",.4);elevatorTone(note*2.5,.72,.009,"sine",-.35)}spaceMusic.timer=setTimeout(elevatorBeat,620)}
function startMusic(){if(!spaceMusic.enabled||spaceMusic.running)return;const ac=musicContext();if(!ac)return;spaceMusic.activated=true;spaceMusic.running=true;const now=ac.currentTime;spaceMusic.master.gain.cancelScheduledValues(now);spaceMusic.master.gain.setValueAtTime(Math.max(.0001,spaceMusic.master.gain.value),now);spaceMusic.master.gain.linearRampToValueAtTime(2.15,now+.7);elevatorBeat()}
function stopMusic(){spaceMusic.running=false;clearTimeout(spaceMusic.timer);spaceMusic.timer=null;if(!spaceMusic.ac||!spaceMusic.master)return;const now=spaceMusic.ac.currentTime;spaceMusic.master.gain.cancelScheduledValues(now);spaceMusic.master.gain.setValueAtTime(Math.max(.0001,spaceMusic.master.gain.value),now);spaceMusic.master.gain.exponentialRampToValueAtTime(.0001,now+.35)}
function notation(m,after){if(m.castle)return m.castle==="king"?"O-O":"O-O-O";const t=m.piece.toUpperCase(),cap=m.captured!=="."||m.enPassant;let x=(t==="P"?(cap?F[m.from%8]:""):t)+(cap?"×":"")+F[m.to%8]+(8-Math.floor(m.to/8));if(m.promotion)x+="="+m.promotion.toUpperCase();if(checked(after,after.turn))x+=legal(after).length?"+":"#";return x}
function evaluate(s){let score=0;for(let i=0;i<64;i++){const p=s.board[i];if(p===".")continue;const[r,c]=RC(i),center=7-Math.abs(3.5-r)-Math.abs(3.5-c),val=V[p.toLowerCase()]+center*2;score+=C(p)==="b"?val:-val}return score}
function search(s,d,a,b){const ms=legal(s);if(!d||!ms.length){if(!ms.length&&checked(s,s.turn))return s.turn==="b"?-999999:999999;return evaluate(s)}if(s.turn==="b"){let best=-Infinity;for(const m of ms){best=Math.max(best,search(apply(s,m),d-1,a,b));a=Math.max(a,best);if(b<=a)break}return best}let best=Infinity;for(const m of ms){best=Math.min(best,search(apply(s,m),d-1,a,b));b=Math.min(b,best);if(b<=a)break}return best}
function aiMove(){const ms=legal(game),d=+difficulty.value;let best=-Infinity,picks=[];for(const m of ms){const score=search(apply(game,m),d-1,-Infinity,Infinity)+Math.random()*5;if(score>best+.01){best=score;picks=[m]}else if(Math.abs(score-best)<.01)picks.push(m)}return picks[Math.floor(Math.random()*picks.length)]}
function result(){const ms=legal(game);if(ms.length)return null;return checked(game,game.turn)?(game.turn==="w"?"The Void Hive conquered your mothership.":"Terran Command shattered the Hive!"):"Stalemate. Both fleets drift into the void."}
function perform(m,ai=false){history.push(clone(game));game=apply(game,m);moveNames.push(notation(m,game));selected=null;selectedMoves=[];render();if(!result()&&mode.value==="ai"&&game.turn==="b"&&!ai)runAi()}
function runAi(){busy=true;thinking.hidden=false;status();setTimeout(()=>{const m=aiMove();if(m)perform(m,true);busy=false;thinking.hidden=true;render()},180)}
function pick(sq){if(busy)return;const chosen=selectedMoves.find(m=>m.to===sq);if(chosen){if(chosen.promotion&&mode.value==="local")promote(chosen);else perform(chosen);return}if(C(game.board[sq])===game.turn&&(mode.value==="local"||game.turn==="w")){selected=sq;selectedMoves=legal(game).filter(m=>m.from===sq)}else{selected=null;selectedMoves=[]}render()}
function promote(m){const modal=document.querySelector("#promotionModal"),box=document.querySelector("#promotionChoices");box.innerHTML="";for(const t of["q","r","b","n"]){const b=document.createElement("button");b.textContent=G[game.turn==="w"?t.toUpperCase():t];b.onclick=()=>{modal.hidden=true;perform({...m,promotion:t})};box.appendChild(b)}modal.hidden=false}
function captured(){const start={P:8,N:2,B:2,R:2,Q:1},now={w:{},b:{}};for(const p of game.board)if(p!=="."){const c=C(p),t=p.toUpperCase();now[c][t]=(now[c][t]||0)+1}for(const[c,id]of[["b","whiteCaptured"],["w","blackCaptured"]]){let s="";for(const t of["Q","R","B","N","P"])s+=G[c==="w"?t:t.toLowerCase()].repeat(start[t]-(now[c][t]||0));document.querySelector("#"+id).textContent=s}}
function status(){const r=result();statusEl.textContent=r||`${game.turn==="w"?"Terran Command":"Void Hive"} to move${checked(game,game.turn)?" — MOTHERSHIP IN CHECK!":""}`;document.querySelector("#turnText").textContent=game.turn==="w"?"TERRAN TURN":"HIVE TURN";document.querySelector("#turnDot").style.background=game.turn==="w"?"var(--cyan)":"var(--lime)";document.querySelector("#enemyName").textContent=mode.value==="ai"?"VOID HIVE AI":"RIVAL COMMANDER";document.querySelector("#enemyState").textContent=mode.value==="ai"?"Calculating futures":"Local dark fleet"}
function render(){boardEl.innerHTML="";const order=[...Array(64).keys()];if(flipped)order.reverse();const available=!busy&&(mode.value==="local"||game.turn==="w")?legal(game):[],movable=new Set(available.map(move=>move.from)),targets=new Map(selectedMoves.map(m=>[m.to,m])),king=checked(game,game.turn)?game.board.indexOf(game.turn==="w"?"K":"k"):-1;for(const sq of order){const[r,c]=RC(sq),p=game.board[sq],b=document.createElement("button");b.className=`square ${(r+c)%2?"dark":"light"}`;b.setAttribute("role","gridcell");b.setAttribute("aria-label",`${F[c]}${8-r}${p!=="."?" "+N[p.toUpperCase()]:" empty"}${movable.has(sq)?", available to move":""}`);if(movable.has(sq))b.classList.add("movable");if(sq===selected)b.classList.add("selected");if(targets.has(sq))b.classList.add(game.board[sq]!=="."||targets.get(sq).enPassant?"capture":"legal");if(game.lastMove&&(sq===game.lastMove.from||sq===game.lastMove.to))b.classList.add("last");if(sq===king)b.classList.add("check");if(p!=="."){const x=document.createElement("span");x.className=`piece ${C(p)==="w"?"white":"black"}`;x.textContent=G[p];b.appendChild(x)}if((!flipped&&c===0)||(flipped&&c===7)){const x=document.createElement("span");x.className="coord rank";x.textContent=8-r;b.appendChild(x)}if((!flipped&&r===7)||(flipped&&r===0)){const x=document.createElement("span");x.className="coord file";x.textContent=F[c];b.appendChild(x)}b.onclick=()=>pick(sq);boardEl.appendChild(b)}logEl.innerHTML="";moveNames.forEach((n,i)=>{const li=document.createElement("li");li.textContent=`${Math.floor(i/2)+1}${i%2?"…":"."} ${n}`;logEl.appendChild(li)});logEl.scrollTop=logEl.scrollHeight;captured();status()}
function reset(){game=fresh();selected=null;selectedMoves=[];history=[];moveNames=[];busy=false;thinking.hidden=true;render()}
document.querySelector("#newGame").onclick=reset;document.querySelector("#clearSelection").onclick=()=>{selected=null;selectedMoves=[];render()};document.querySelector("#flip").onclick=()=>{flipped=!flipped;render()};document.querySelector("#undo").onclick=()=>{if(busy||!history.length)return;let n=mode.value==="ai"&&game.turn==="w"?2:1;while(n--&&history.length){game=history.pop();moveNames.pop()}selected=null;selectedMoves=[];render()};mode.onchange=reset;difficulty.onchange=()=>{if(mode.value==="ai")reset()};musicButton.onclick=()=>{spaceMusic.enabled=!spaceMusic.enabled;musicButton.setAttribute("aria-pressed",spaceMusic.enabled);musicButton.textContent=spaceMusic.enabled?"♫ Space music: On":"♫ Space music: Off";if(spaceMusic.enabled)startMusic();else stopMusic()};function firstMusicInput(event){if(event.target.closest?.("#musicToggle"))return;startMusic();if(spaceMusic.activated)document.removeEventListener("pointerdown",firstMusicInput)}document.addEventListener("pointerdown",firstMusicInput);document.addEventListener("keydown",()=>startMusic(),{once:true});document.addEventListener("visibilitychange",()=>{if(document.hidden)stopMusic();else if(spaceMusic.enabled&&spaceMusic.activated)startMusic()});reset();})();
