(()=>{
  const files={card:'assets/arcade-sfx/card-place.mp3',coin:'assets/arcade-sfx/coin-clink.mp3',laser:'assets/arcade-sfx/laser-shot.mp3',metal:'assets/arcade-sfx/metal-impact.mp3',door:'assets/arcade-sfx/sci-fi-door.mp3',step:'assets/arcade-sfx/robot-step.mp3',magic:'assets/arcade-sfx/crystal-chime.mp3',cheer:'assets/cosmo-kids/kids-crowd-yay.mp3'},raw={},buffers={},loads={},decodes={},queued={},last={};let context,master,compressor;
  const style=document.createElement('link');style.rel='stylesheet';style.href='arcade-fx.css?v=1';document.head.append(style);
  Object.entries(files).forEach(([name,url])=>{loads[name]=fetch(url).then(response=>response.ok?response.arrayBuffer():Promise.reject()).then(data=>raw[name]=data).catch(()=>null)});
  function ready(){try{if(!context){context=new(window.AudioContext||window.webkitAudioContext)();master=context.createGain();master.gain.value=.92;compressor=context.createDynamicsCompressor();compressor.threshold.value=-16;compressor.knee.value=20;compressor.ratio.value=7;compressor.attack.value=.003;compressor.release.value=.2;compressor.connect(master);master.connect(context.destination)}if(context.state==='suspended')context.resume();Object.keys(files).forEach(decode);return context}catch{return null}}
  function decode(name){if(buffers[name])return Promise.resolve(buffers[name]);if(!context)return Promise.resolve(null);if(decodes[name])return decodes[name];decodes[name]=(raw[name]?Promise.resolve(raw[name]):loads[name].then(()=>raw[name])).then(data=>{if(!data)return null;delete raw[name];return context.decodeAudioData(data.slice(0))}).then(buffer=>buffers[name]=buffer).catch(()=>null);return decodes[name]}
  function play(name,options={}){if(options.enabled===false)return;const ac=ready();if(!ac)return;const now=performance.now(),cooldown=options.cooldown??35;if(now-(last[name]||0)<cooldown)return;if(!buffers[name]){if(!queued[name]){queued[name]=true;decode(name).then(()=>{queued[name]=false;if(buffers[name])play(name,{...options,cooldown:0})})}return}last[name]=now;const source=ac.createBufferSource(),gain=ac.createGain(),pan=ac.createStereoPanner?.();source.buffer=buffers[name];source.playbackRate.value=options.rate??(.96+Math.random()*.08);gain.gain.value=options.volume??.42;source.connect(gain);if(pan){pan.pan.value=Math.max(-1,Math.min(1,options.pan??0));gain.connect(pan);pan.connect(compressor)}else gain.connect(compressor);source.start(ac.currentTime,Math.max(0,options.offset||0));if(options.duration)source.stop(ac.currentTime+Math.min(options.duration,source.buffer.duration));return source}
  function point(target){if(target?.clientX!=null)return{x:target.clientX,y:target.clientY};const element=target?.nodeType?target:null,rect=element?.getBoundingClientRect?.();return rect?{x:rect.left+rect.width/2,y:rect.top+rect.height/2}:{x:innerWidth/2,y:innerHeight/2}}
  function flash(color='#67ffe2',strength=.3,target){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const p=point(target),node=document.createElement('i');node.className='arcade-fx-flash';node.style.setProperty('--fx-x',`${p.x}px`);node.style.setProperty('--fx-y',`${p.y}px`);node.style.setProperty('--fx-color',color);node.style.opacity=String(strength);document.body.append(node);setTimeout(()=>node.remove(),500)}
  function burst(target,color='#67ffe2',count=10){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const p=point(target);for(let i=0;i<count;i++){const particle=document.createElement('i'),angle=i/count*Math.PI*2+Math.random()*.35,distance=35+Math.random()*75;particle.className='arcade-fx-particle';particle.style.setProperty('--fx-left',`${p.x}px`);particle.style.setProperty('--fx-top',`${p.y}px`);particle.style.setProperty('--fx-size',`${3+Math.random()*6}px`);particle.style.setProperty('--fx-color',color);particle.style.setProperty('--fx-dx',`${Math.cos(angle)*distance}px`);particle.style.setProperty('--fx-dy',`${Math.sin(angle)*distance}px`);document.body.append(particle);setTimeout(()=>particle.remove(),700)}}
  function shake(target=document.body,strength=1){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const element=target?.animate?target:document.body,d=3.5*strength;element.animate([{transform:'translate(0)'},{transform:`translate(${-d}px,${d*.55}px)`},{transform:`translate(${d}px,${-d*.35}px)`},{transform:`translate(${-d*.55}px,0)`},{transform:'translate(0)'}],{duration:180+strength*45,easing:'ease-out'})}
  function hit(target,color='#67ffe2',strength=1){flash(color,.3*strength,target);burst(target,color,Math.round(8+strength*4));if(strength>.65)shake(target?.nodeType?target:document.body,strength)}
  document.addEventListener('pointerdown',event=>{ready();const button=event.target.closest?.('button,[role="button"],.game-card');if(!button||button.disabled)return;const ripple=document.createElement('i');ripple.className='arcade-fx-ripple';ripple.style.setProperty('--fx-left',`${event.clientX}px`);ripple.style.setProperty('--fx-top',`${event.clientY}px`);document.body.append(ripple);setTimeout(()=>ripple.remove(),500)},true);
  window.DanArcadeFX={play,flash,burst,shake,hit,warm:ready};
})();
