(()=>{
'use strict';
const $=s=>document.querySelector(s),startScreen=$('#startScreen'),storyScreen=$('#storyScreen'),endingScreen=$('#endingScreen'),sceneBg=$('#sceneBg'),interaction=$('#interaction'),continueBtn=$('#continueBtn'),storyText=$('#storyText');
const ui={
fr:{shortTitle:'L’Atelier entre les rêves',voice:'Voix',sound:'Son',eyebrow:'UNE HISTOIRE NÉE D’UN VRAI DESSIN',titleA:'L’Atelier',titleB:'entre les rêves',lead:'À minuit, une page de carnet s’ouvre sur un monde qui connaît ton nom. Sept gardiens t’attendent. Tes choix décideront de ce qui mérite d’être sauvé.',nameLabel:'Quel nom doit apparaître dans l’histoire?',namePlaceholder:'Ton prénom',begin:'Ouvrir le carnet',resume:'Reprendre l’histoire',duration:'25–35 minutes',choices:'Choix et actions tactiles',endings:'Plusieurs fins',seeSketch:'Découvrir comment l’histoire a commencé',continue:'Tourner la page',hint:'Tu peux prendre ton temps. L’histoire attendra.',yourEnding:'TA FIN',storySaw:'L’histoire a vu en toi',replay:'Recommencer avec d’autres choix',reveal:'Revoir l’origine de l’histoire',originalPage:'L’ORIGINE DU MONDE',whereBegan:'C’est ici que le rêve a commencé.',sketchCopy:'Ce monde est né d’une vraie page de carnet. Le dessin original reste précieusement privé; ses idées sont devenues cette nouvelle aventure.',minutes:'min',narrator:'LE NARRATEUR',fragments:'fragments retrouvés',hold:'Garde la lumière allumée',sequence:'Mémorise les étoiles…',tryAgain:'La constellation s’efface. Essaie encore.',saved:'Progression sauvegardée',soundOn:'Ambiance activée',soundOff:'Ambiance désactivée',voiceOn:'Narration activée',voiceOff:'Narration désactivée'},
en:{shortTitle:'The Atelier Between Dreams',voice:'Voice',sound:'Sound',eyebrow:'A STORY BORN FROM A REAL DRAWING',titleA:'The Atelier',titleB:'between dreams',lead:'At midnight, a sketchbook page opens onto a world that already knows your name. Seven guardians are waiting. Your choices will decide what deserves to be saved.',nameLabel:'What name should appear in the story?',namePlaceholder:'Your name',begin:'Open the sketchbook',resume:'Resume the story',duration:'25–35 minutes',choices:'Choices and touch actions',endings:'Multiple endings',seeSketch:'Discover how the story began',continue:'Turn the page',hint:'Take your time. The story will wait.',yourEnding:'YOUR ENDING',storySaw:'The story saw in you',replay:'Replay with different choices',reveal:'Revisit the story’s origin',originalPage:'THE ORIGIN OF THE WORLD',whereBegan:'This is where the dream began.',sketchCopy:'This world began with one real sketchbook page. The original drawing remains safely private; its ideas became this new adventure.',minutes:'min',narrator:'THE NARRATOR',fragments:'fragments recovered',hold:'Keep the light alive',sequence:'Memorize the stars…',tryAgain:'The constellation fades. Try again.',saved:'Progress saved',soundOn:'Ambience on',soundOff:'Ambience off',voiceOn:'Narration on',voiceOff:'Narration off'}
};
const chapters=[
{fr:['CHAPITRE I','La page qui respirait'],en:['CHAPTER I','The Page That Breathed']},
{fr:['CHAPITRE II','Le pont d’encre'],en:['CHAPTER II','The Ink Bridge']},
{fr:['CHAPITRE III','Le jardin des souvenirs'],en:['CHAPTER III','The Garden of Memories']},
{fr:['CHAPITRE IV','Le blanc qui dévore'],en:['CHAPTER IV','The Devouring Blank']},
{fr:['CHAPITRE V','Ce que tu choisis de garder'],en:['CHAPTER V','What You Choose to Keep']}
];
const B=(fr,en)=>({fr,en});
const scenes=[
{c:0,img:'cover',s:B('LE NARRATEUR','THE NARRATOR'),title:B('La minute impossible','The Impossible Minute'),text:B(
`À 23 h 59, la maison est silencieuse. Ton carnet est fermé sur le bureau, coincé sous un crayon que tu avais juré de ranger. Pourtant, une feuille remue. Pas comme une page poussée par le vent : comme une poitrine qui prend sa première respiration. Lorsque minuit arrive, l’encre de tes personnages se met à briller. Une ligne dorée traverse le papier, s’arrête sous ton nom — {name} — puis dessine une poignée là où il n’y avait qu’une marge blanche. De l’autre côté, quelqu’un frappe trois fois, poliment, comme s’il attendait depuis très longtemps.`,
`At 11:59 p.m., the house is silent. Your sketchbook lies closed on the desk, trapped beneath a pencil you promised to put away. Then one sheet moves—not like a page pushed by wind, but like a chest taking its first breath. At midnight, the ink around your characters begins to glow. A golden line crosses the paper, pauses beneath your name—{name}—and draws a handle where there had only been a blank margin. From the other side, someone knocks three times, politely, as though they have been waiting for a very long time.`)},
{c:0,img:'cover',s:B('UNE VOIX DERRIÈRE LA PAGE','A VOICE BEHIND THE PAGE'),title:B('« Nous nous souvenons de toi. »','“We remember you.”'),text:B(
`La voix n’est ni grave ni aiguë. Elle ressemble à plusieurs personnes qui chuchotent la même phrase sans parvenir à commencer exactement ensemble. « Tu nous as dessinés lorsque tu avais besoin que quelqu’un reste. Nous sommes restés. Mais l’Atelier perd ses pages, et bientôt nous oublierons pourquoi nous comptions pour toi. » La poignée d’encre devient chaude sous tes doigts. Tu pourrais réveiller quelqu’un, refermer le carnet ou prétendre que tout ceci est un rêve. Mais au fond de toi, tu sais déjà que certains rêves ne demandent pas qu’on y croie. Ils demandent seulement qu’on leur réponde.`,
`The voice is neither deep nor high. It sounds like several people whispering the same sentence without quite beginning together. “You drew us when you needed someone to stay. We stayed. But the Atelier is losing its pages, and soon we will forget why we mattered to you.” The ink handle grows warm beneath your fingers. You could wake someone, close the sketchbook, or pretend this is a dream. Yet somewhere inside, you already know that some dreams do not ask to be believed. They only ask to be answered.`)},
{c:0,img:'cover',s:B('LES SEPT GARDIENS','THE SEVEN GUARDIANS'),title:B('Qui remarques-tu en premier?','Who do you notice first?'),text:B(
`La page s’ouvre sur un atelier aussi vaste qu’un ciel. Des bibliothèques encerclent un océan de feuilles, et sept silhouettes attendent sur un chemin fait de carnets. Elles ne sont pas exactement celles de ton dessin; elles sont ce que ton imagination leur permet de devenir lorsqu’elle rêve sans être surveillée. Trois s’avancent. Lyra, couverte d’étoiles, sourit comme si le danger était une blague privée. Aster, le gardien cornu, se place instinctivement entre toi et le vide. Solenne tient contre son cœur une lanterne remplie de souvenirs.`,
`The page opens onto an atelier as vast as a sky. Bookshelves surround an ocean of paper, and seven figures wait upon a road made of sketchbooks. They are not exactly the figures from your drawing; they are what your imagination lets them become when it dreams without being watched. Three step forward. Lyra, clothed in stars, smiles as though danger were a private joke. Aster, the horned guardian, instinctively places himself between you and the void. Solenne holds a lantern filled with memories against her heart.`),type:'choice',key:'guide',options:[
{v:'lyra',trait:'wonder',label:B('Lyra, la mage des étoiles','Lyra, the star mage'),detail:B('« Je veux comprendre ce monde. »','“I want to understand this world.”'),feedback:B('Lyra rit doucement. « Alors posons les questions interdites. »','Lyra laughs softly. “Then let us ask the forbidden questions.”')},
{v:'aster',trait:'courage',label:B('Aster, le protecteur cornu','Aster, the horned protector'),detail:B('« Je veux que personne ne soit laissé derrière. »','“I want no one left behind.”'),feedback:B('Aster incline la tête. « Ton courage protège déjà quelqu’un. »','Aster bows his head. “Your courage is already protecting someone.”')},
{v:'solenne',trait:'kindness',label:B('Solenne, la gardienne des souvenirs','Solenne, the memory keeper'),detail:B('« Je veux savoir ce qu’ils ont perdu. »','“I want to know what they lost.”'),feedback:B('La lanterne de Solenne s’éclaire. « La douceur aussi peut guider. »','Solenne’s lantern brightens. “Gentleness can guide us too.”')}
]},
{c:0,img:'cover',s:B('{guide}','{guide}'),title:B('La règle de l’Atelier','The Atelier’s Rule'),text:B(
`{guide} t’explique la seule loi de cet endroit : rien ne peut exister ici sans être regardé. Un dessin oublié pâlit. Une idée jugée trop étrange perd sa voix. Une page arrachée devient une tempête. Au centre de l’Atelier se trouve la Reliure, un fil de lumière qui retient ensemble tout ce que les artistes ont aimé sans toujours savoir l’expliquer. Cette nuit, quelque chose appelé le Blanc a coupé ce fil. Pour le renouer, il faut retrouver trois encres : l’Émerveillement, la Mémoire et le Courage de montrer ce qui n’est pas parfait.`,
`{guide} explains the only law of this place: nothing here can exist without being seen. A forgotten drawing fades. An idea judged too strange loses its voice. A torn page becomes a storm. At the center of the Atelier lies the Binding, a thread of light holding together everything artists have loved without always knowing how to explain it. Tonight, something called the Blank has cut that thread. To mend it, you must recover three inks: Wonder, Memory, and the Courage to show what is not perfect.`)},
{c:0,img:'cover',s:B('L’ATELIER','THE ATELIER'),title:B('Rassemble les pages perdues','Gather the Lost Pages'),text:B(
`Avant de partir, les gardiens doivent reconstruire la carte. Cinq fragments tournent autour de toi, chacun portant un détail de ton monde : une corne, une étoile, une flamme, un masque et une main qui tient un crayon. Ils fuient lorsqu’on essaie de les saisir trop vite. {guide} te conseille de ne pas les pourchasser. « Touche-les seulement lorsqu’ils viennent près de toi. Les bonnes idées reviennent plus facilement quand on leur laisse un peu d’espace. »`,
`Before you leave, the guardians must rebuild the map. Five fragments circle you, each carrying one detail from your world: a horn, a star, a flame, a mask, and a hand holding a pencil. They flee whenever anyone grabs too quickly. {guide} advises you not to chase them. “Touch them only when they come close. Good ideas return more easily when you leave them a little room.”`),type:'fragments'},
{c:1,img:'storm',s:B('LE NARRATEUR','THE NARRATOR'),title:B('Le chemin se déchire','The Road Tears Open'),text:B(
`La carte révèle un passage vers la première encre, mais le pont de carnets se fend avant même que vous l’atteigniez. Des gouttes d’encre noire montent vers le ciel, emportant des mots, des visages et des couleurs. Lyra lance une constellation autour des pages. Aster bloque une vague avec ses épaules. Solenne protège sa lanterne sous son manteau. Toi, tu cours. Chaque pas fait apparaître sous tes pieds un dessin que tu ne te rappelles pas avoir fait : des créatures dans les marges, des yeux sur les lunes, des héros avec des mains trop grandes. Aucun n’est parfait. Tous vous empêchent de tomber.`,
`The map reveals a path toward the first ink, but the sketchbook bridge splits before you can reach it. Drops of black ink rise into the sky, carrying words, faces, and colors away. Lyra throws a constellation around the pages. Aster blocks a wave with his shoulders. Solenne shields her lantern beneath her coat. You run. Every step reveals a drawing you do not remember making: creatures in margins, eyes upon moons, heroes with oversized hands. None is perfect. Every one keeps you from falling.`)},
{c:1,img:'storm',s:B('CINDER','CINDER'),title:B('Quelque chose tombe du pont','Something Falls from the Bridge'),text:B(
`Un petit gardien encapuchonné nommé Cinder glisse près du bord. Au même instant, une page portant la seule carte vers la sortie se libère, et la lanterne de Solenne roule dans la direction opposée. Tu n’as qu’une seconde. Les autres pourront peut-être sauver ce que tu ne choisis pas, mais personne ne promet que tout reviendra intact. Dans l’Atelier, un choix n’est jamais une bonne réponse déguisée. C’est une façon de dire au monde ce que tu regardes en premier lorsque tout devient trop rapide.`,
`A small hooded guardian named Cinder slips near the edge. At the same moment, the page containing the only map to the exit tears loose, and Solenne’s lantern rolls the opposite way. You have one second. The others may be able to save what you do not choose, but no one promises everything will return intact. In the Atelier, a choice is never a correct answer in disguise. It is a way of telling the world what you look toward first when everything moves too quickly.`),type:'choice',key:'rescue',options:[
{v:'cinder',trait:'kindness',label:B('Attraper Cinder','Catch Cinder'),detail:B('Une personne avant un plan.','A person before a plan.'),feedback:B('Ta main trouve la sienne. Cinder ne la lâche pas.','Your hand finds theirs. Cinder does not let go.')},
{v:'map',trait:'courage',label:B('Sauter vers la carte','Leap for the map'),detail:B('Créer une chance pour tout le groupe.','Create a chance for everyone.'),feedback:B('Tu atterris sur une page qui plie mais ne casse pas.','You land on a page that bends but does not break.')},
{v:'lantern',trait:'wonder',label:B('Sauver la lanterne','Save the lantern'),detail:B('Les souvenirs doivent survivre.','The memories must survive.'),feedback:B('La lumière t’enveloppe et te montre un chemin caché.','The light surrounds you and reveals a hidden path.')}
]},
{c:1,img:'storm',s:B('MERIDIAN','MERIDIAN'),title:B('Le diplomate à tête d’horloge','The Clock-Headed Diplomat'),text:B(
`Une main gantée te ramène sur le pont. Elle appartient à Meridian, dont le visage rectangulaire ressemble à une horloge sans aiguilles. Il parle avec une précision presque comique : « Rapport de catastrophe : terrible. Rapport d’équipe : étonnamment acceptable. » Derrière lui, Cinder, la carte et la lanterne sont tous revenus, quoique la carte porte maintenant une brûlure en forme de cœur. Meridian t’avoue qu’il a été dessiné pour toujours savoir quoi dire, mais qu’il envie ceux qui peuvent hésiter. « L’hésitation prouve que plusieurs choses comptent. Une machine appelle cela une erreur. Moi, j’appelle cela une âme. »`,
`A gloved hand pulls you back onto the bridge. It belongs to Meridian, whose rectangular face resembles a clock without hands. He speaks with almost comic precision: “Catastrophe report: terrible. Team report: surprisingly acceptable.” Behind him, Cinder, the map, and the lantern have all returned, although the map now bears a heart-shaped burn. Meridian admits he was drawn to always know what to say, yet envies those who can hesitate. “Hesitation proves that several things matter. A machine calls that an error. I call it a soul.”`)},
{c:1,img:'storm',s:B('LYRA','LYRA'),title:B('La constellation oubliée','The Forgotten Constellation'),text:B(
`À l’extrémité du pont, une porte de pierre n’a ni serrure ni poignée. Quatre symboles apparaissent puis disparaissent dans le ciel. Lyra reconnaît une constellation créée par un enfant qui voulait nommer une étoile, mais qui avait oublié comment l’écrire. Pour ouvrir la porte, tu dois retenir l’ordre exact : l’étoile qui ose commencer, la lune qui accepte de changer, la flamme qui garde la chaleur, puis l’étoile qui revient pour les autres. Regarde bien. Lorsque les lumières s’éteindront, l’Atelier ne te laissera que ta mémoire.`,
`At the bridge’s end, a stone door has neither lock nor handle. Four symbols appear and vanish across the sky. Lyra recognizes a constellation invented by a child who wanted to name a star but had forgotten how to spell it. To open the door, remember the exact order: the star that dares to begin, the moon that accepts change, the flame that keeps warmth, and the star that returns for the others. Watch carefully. When the lights go out, the Atelier will leave you only your memory.`),type:'sequence'},
{c:1,img:'storm',s:B('VEY','VEY'),title:B('Derrière la porte sans poignée','Beyond the Handleless Door'),text:B(
`La porte s’ouvre sur un corridor si mince qu’il ressemble à une ligne de crayon. Vey, le voyageur au masque de renard, avance sans produire le moindre son. « Le Blanc écoute les certitudes », dit-il. « Il les suit jusqu’à ceux qui les prononcent. » Il te propose trois routes. La première traverse les marges, où vivent les idées abandonnées. La deuxième passe par la salle des cadres, où chaque dessin est jugé. La troisième descend dans le Jardin des souvenirs, où l’on risque de retrouver quelque chose qu’on avait volontairement oublié. Aucun chemin n’est sûr; chacun révèle une vérité différente.`,
`The door opens onto a corridor so narrow it resembles a pencil line. Vey, the fox-masked wanderer, moves without making a sound. “The Blank listens for certainty,” he says. “It follows certainty back to whoever spoke it.” He offers three routes. The first crosses the margins, where abandoned ideas live. The second passes through the Hall of Frames, where every drawing is judged. The third descends into the Garden of Memories, where you may recover something you deliberately forgot. No road is safe; each reveals a different truth.`)},
{c:1,img:'storm',s:B('VEY','VEY'),title:B('Choisis la route','Choose the Route'),text:B(
`Meridian recommande la salle des cadres parce que ses règles peuvent être étudiées. Vey préfère les marges, précisément parce qu’elles n’obéissent à aucune règle. Vigil, le grand sentinel sans visage, pointe silencieusement vers le jardin. Son armure semble refléter une version de toi légèrement plus âgée, comme s’il connaissait déjà la personne que tu pourrais devenir. {guide} ne choisit pas à ta place. « Un guide qui décide tout ne te conduit pas », dit-il. « Il te transporte. Et tu es venue ici pour marcher. »`,
`Meridian recommends the Hall of Frames because its rules can be studied. Vey prefers the margins precisely because they obey no rules. Vigil, the tall faceless sentinel, silently points toward the garden. His armor reflects a version of you that looks slightly older, as though he already knows the person you might become. {guide} will not choose for you. “A guide who decides everything does not lead you,” they say. “They carry you. And you came here to walk.”`),type:'choice',key:'path',options:[
{v:'margins',trait:'wonder',label:B('Les marges sauvages','The Wild Margins'),detail:B('Suivre les idées étranges.','Follow the strange ideas.'),feedback:B('Vey dessine un sourire sur son masque.','Vey sketches a smile across his mask.')},
{v:'frames',trait:'courage',label:B('La salle des cadres','The Hall of Frames'),detail:B('Regarder le jugement en face.','Face judgment directly.'),feedback:B('Meridian redresse son nœud papillon. « Audacieux. »','Meridian straightens his bow tie. “Bold.”')},
{v:'garden',trait:'kindness',label:B('Le jardin des souvenirs','The Garden of Memories'),detail:B('Écouter ce qui fait encore mal.','Listen to what still hurts.'),feedback:B('Vigil ouvre la marche sans un mot.','Vigil leads the way without a word.')}
]},
{c:1,img:'storm',s:B('LE NARRATEUR','THE NARRATOR'),title:B('La route que tu as créée','The Road You Made'),text:B(
`Le chemin choisi change autour de toi. Les murs deviennent des dessins géants dont les lignes bougent avec ta respiration. Certaines silhouettes semblent magnifiques de loin, puis révèlent des corrections, des ratures et du papier aminci lorsqu’on s’approche. D’autres paraissent maladroites jusqu’à ce que leur ombre forme une scène parfaite. Tu comprends que l’Atelier ne sépare pas les réussites des erreurs. Il les empile. Chaque trait raté soutient le suivant. Même le Blanc ne peut dévorer une ligne qui a servi de fondation à quelque chose que tu aimes maintenant.`,
`The road changes around your choice. Walls become enormous drawings whose lines move with your breathing. Some figures look magnificent from a distance, then reveal corrections, scratches, and paper worn thin when you approach. Others seem awkward until their shadows form a perfect scene. You realize the Atelier does not separate successes from mistakes. It stacks them. Every failed line supports the next one. Even the Blank cannot consume a mark that became the foundation of something you love now.`)},
{c:1,img:'storm',s:B('ASTER','ASTER'),title:B('La première encre','The First Ink'),text:B(
`Au bout de la route flotte une fiole remplie d’un bleu impossible. Aster l’appelle l’Encre d’Émerveillement. Elle apparaît chaque fois que quelqu’un demande « et si…? » sans se moquer de sa propre réponse. Lorsque tu touches la fiole, l’Atelier te montre des centaines de mondes possibles : un train qui voyage entre les constellations, une ville construite dans les bois d’un cerf, une bibliothèque sous la mer. Aucun ne réclame d’être ton meilleur concept. Ils sont heureux d’avoir existé pendant une seconde. La fiole rejoint ton carnet, et une nouvelle page se dessine d’elle-même.`,
`At the road’s end floats a vial filled with an impossible blue. Aster calls it the Ink of Wonder. It appears whenever someone asks “what if?” without mocking their own answer. When you touch the vial, the Atelier shows you hundreds of possible worlds: a train traveling between constellations, a city built within a deer’s antlers, a library beneath the sea. None demands to be your greatest idea. They are simply happy to have existed for one second. The vial enters your sketchbook, and a new page draws itself.`)},
{c:2,img:'garden',s:B('SOLENNE','SOLENNE'),title:B('Le jardin qui se souvient','The Garden That Remembers'),text:B(
`Le Jardin des souvenirs pousse à l’intérieur d’un carnet fermé. Ses fleurs sont faites de papier blanc et leurs racines plongent dans un bassin rempli de constellations. Solenne s’assoit au bord de l’eau. Sa lanterne contient un dessin d’enfance : proportions étranges, lignes tremblantes, couleurs dépassant partout. « C’était le premier endroit où je me sentais vivante », dit-elle. « Puis quelqu’un a ri. La personne qui m’avait dessinée m’a cachée pendant des années. » Elle ne parle pas avec colère. C’est pire : elle parle comme quelqu’un qui s’est habitué à attendre dans le noir.`,
`The Garden of Memories grows inside a closed sketchbook. Its flowers are made of white paper, and their roots descend into a pool filled with constellations. Solenne sits beside the water. Her lantern holds a childhood drawing: strange proportions, trembling lines, colors spilling everywhere. “It was the first place I felt alive,” she says. “Then someone laughed. The person who drew me hid me for years.” She does not sound angry. It is worse—she sounds like someone who became accustomed to waiting in the dark.`)},
{c:2,img:'garden',s:B('SOLENNE','SOLENNE'),title:B('Une lumière fragile','A Fragile Light'),text:B(
`La seconde encre dort dans la lanterne, mais sa flamme diminue. Pour l’éveiller, il faut garder la lumière allumée pendant que Solenne ouvre le souvenir. Tu dois poser ta main sur le cercle et ne pas la retirer, même lorsque les ombres te montrent des dessins comparés à ceux des autres, des commentaires inutiles et des pages abandonnées trop tôt. « La mémoire ne demande pas que tu approuves tout ce qui est arrivé », murmure Solenne. « Elle demande seulement que tu cesses de prétendre que cela n’a rien changé. »`,
`The second ink sleeps inside the lantern, but its flame is fading. To awaken it, you must keep the light alive while Solenne opens the memory. Place your hand upon the circle and do not lift it, even when the shadows show drawings compared with other people’s work, careless comments, and pages abandoned too soon. “Memory does not ask you to approve of everything that happened,” Solenne whispers. “It only asks you to stop pretending it changed nothing.”`),type:'hold'},
{c:2,img:'garden',s:B('LA LANTERNE','THE LANTERN'),title:B('Ce que la lumière révèle','What the Light Reveals'),text:B(
`Dans la flamme apparaît une petite table couverte de crayons. Une enfant y dessine sans mesurer le temps. Elle ne connaît pas encore les règles de perspective, l’anatomie ou les noms des styles. Elle sait seulement qu’une ligne courbe peut devenir un sourire, qu’un manteau peut contenir un ciel, et qu’un personnage inventé peut rendre une mauvaise journée moins lourde. L’image ne te dit pas que tout était facile. Elle te rappelle quelque chose de plus précieux : avant de vouloir être impressionnante, tu voulais créer une présence. Quelqu’un qui resterait sur la page quand la chambre devenait trop silencieuse.`,
`Within the flame appears a small table covered in pencils. A child draws there without measuring time. She does not yet know the rules of perspective, anatomy, or the names of artistic styles. She only knows a curved line can become a smile, a coat can contain a sky, and an invented character can make a difficult day feel lighter. The image does not claim everything was easy. It reminds you of something more precious: before you wanted to be impressive, you wanted to create a presence—someone who would remain on the page when the room became too quiet.`)},
{c:2,img:'garden',s:B('CINDER','CINDER'),title:B('La page imparfaite','The Imperfect Page'),text:B(
`Cinder se réveille et dépose devant toi le dessin ancien. Une main est trop grande; un œil est plus haut que l’autre; le papier porte la marque d’une gomme utilisée jusqu’à presque le trouer. Une voix dans le bassin te propose de le corriger. Elle pourrait rendre les lignes propres, équilibrer les couleurs et effacer chaque preuve d’hésitation. Solenne ne t’arrête pas. « Peut-être que le réparer te fera du bien. Peut-être que le garder intact protège autre chose. Je ne peux pas connaître la différence à ta place. » Le dessin attend ton geste sans avoir honte.`,
`Cinder wakes and places the old drawing before you. One hand is too large; one eye sits higher than the other; the paper bears the mark of an eraser used nearly through it. A voice in the pool offers to correct it. It could clean every line, balance every color, and erase every sign of hesitation. Solenne does not stop you. “Perhaps repairing it will help. Perhaps keeping it unchanged protects something else. I cannot know the difference for you.” The drawing waits for your gesture without feeling ashamed.`),type:'choice',key:'imperfection',options:[
{v:'preserve',trait:'kindness',label:B('Le garder exactement ainsi','Keep it exactly as it is'),detail:B('Son histoire vit dans ses marques.','Its history lives in its marks.'),feedback:B('La page se réchauffe comme une main tenue.','The page warms like a hand being held.')},
{v:'redraw',trait:'courage',label:B('Le redessiner à côté','Redraw it beside the original'),detail:B('Honorer le chemin parcouru.','Honor how far you have come.'),feedback:B('Deux versions se regardent sans se faire concurrence.','Two versions face each other without competing.')},
{v:'ask',trait:'wonder',label:B('Demander au dessin ce qu’il veut','Ask the drawing what it wants'),detail:B('Peut-être possède-t-il sa propre réponse.','Perhaps it has its own answer.'),feedback:B('Le personnage dessiné choisit une nouvelle aventure.','The drawn character chooses a new adventure.')}
]},
{c:2,img:'garden',s:B('LE BASSIN','THE POOL'),title:B('L’énigme du reflet','The Reflection’s Riddle'),text:B(
`Le bassin s’illumine et pose sa question : « Je deviens plus grand lorsqu’on me partage. Je peux survivre à l’oubli, mais pas à l’indifférence. Je n’exige ni talent ni permission. On me trouve dans un dessin offert, un personnage gardé et une histoire racontée juste avant de dormir. Que suis-je? » Les gardiens gardent le silence. Même Meridian cache ses calculs. Cette réponse doit venir de toi, non parce que l’Atelier aime les examens, mais parce que certains mots changent de valeur lorsqu’on les choisit soi-même.`,
`The pool glows and asks its question: “I grow larger when shared. I can survive being forgotten, but not being treated as meaningless. I require neither talent nor permission. I am found in a drawing given away, a character kept, and a story told just before sleep. What am I?” The guardians remain silent. Even Meridian hides his calculations. The answer must come from you, not because the Atelier enjoys tests, but because certain words change their value when you choose them yourself.`),type:'choice',key:'riddle',options:[
{v:'love',trait:'kindness',label:B('L’affection','Care'),detail:B('Ce qui dit : tu comptes pour moi.','What says: you matter to me.'),feedback:B('Le bassin répond : « Oui. Et l’affection laisse des traces. »','The pool answers: “Yes. And care leaves traces.”')},
{v:'imagination',trait:'wonder',label:B('L’imagination','Imagination'),detail:B('Ce qui devient réel lorsqu’on le partage.','What becomes real when shared.'),feedback:B('Les fleurs répondent : « Oui. Un monde attendait ce mot. »','The flowers answer: “Yes. A world was waiting for that word.”')},
{v:'courage',trait:'courage',label:B('Le courage de montrer','The courage to show'),detail:B('Ce qui refuse de rester caché.','What refuses to remain hidden.'),feedback:B('La lanterne répond : « Oui. Être vu est aussi un risque. »','The lantern answers: “Yes. Being seen is also a risk.”')}
]},
{c:2,img:'garden',s:B('VIGIL','VIGIL'),title:B('Le sentinel retire son casque','The Sentinel Removes His Helm'),text:B(
`Vigil s’agenouille devant le bassin. Pour la première fois, le grand sentinel retire son casque. Il n’y a pas de visage dessous, seulement une surface de papier vierge. Tu comprends qu’il n’a jamais été terminé. Chaque artiste qui l’a rencontré a supposé que quelqu’un d’autre dessinerait ses traits plus tard. Pourtant, il a protégé l’Atelier pendant des années sans bouche pour demander merci ni yeux pour pleurer. Tu prends ton crayon, mais il secoue la tête. Il ne veut pas un visage choisi à sa place. Il veut simplement la promesse qu’une page inachevée peut encore appartenir à l’histoire.`,
`Vigil kneels beside the pool. For the first time, the tall sentinel removes his helm. Beneath it is no face, only a surface of blank paper. You understand that he was never finished. Every artist who met him assumed someone else would add his features later. Yet he protected the Atelier for years without a mouth to ask for thanks or eyes with which to cry. You lift your pencil, but he shakes his head. He does not want a face chosen for him. He only wants the promise that an unfinished page may still belong to the story.`)},
{c:2,img:'garden',s:B('SOLENNE','SOLENNE'),title:B('La deuxième encre','The Second Ink'),text:B(
`La lanterne s’ouvre. L’Encre de Mémoire n’est pas triste comme tu l’imaginais; elle est couleur d’ambre, chaude et vivante. Elle ne conserve pas chaque détail. Elle garde plutôt la sensation qui explique pourquoi un moment compte encore : la fierté d’un premier personnage, le calme trouvé en dessinant tard, la surprise de voir quelqu’un aimer ce que tu avais presque jeté. Lorsque la fiole rejoint ton carnet, Solenne semble plus légère. « Un souvenir partagé n’est plus une pièce fermée », dit-elle. « Il devient une fenêtre. » Au loin, cependant, toutes les autres fenêtres commencent à devenir blanches.`,
`The lantern opens. The Ink of Memory is not sad as you expected; it is amber, warm and alive. It does not preserve every detail. Instead, it keeps the feeling that explains why a moment still matters: pride in a first character, calm found while drawing late, the surprise of seeing someone love what you nearly discarded. When the vial enters your sketchbook, Solenne seems lighter. “A memory shared is no longer a locked room,” she says. “It becomes a window.” In the distance, however, every other window begins turning white.`)},
{c:3,img:'storm',s:B('LE BLANC','THE BLANK'),title:B('« Je peux tout rendre facile. »','“I Can Make Everything Easy.”'),text:B(
`Le Blanc arrive sans bruit. Il ne ressemble pas à un monstre. Il ressemble à une page parfaitement propre, immense et paisible, qui avance en effaçant les bibliothèques. Sa voix est douce. « Tu es fatiguée de recommencer. Fatiguée de comparer. Donne-moi les dessins qui pourraient décevoir quelqu’un. Je garderai seulement ceux dont tu peux être fière. Plus de maladresse, plus de gêne, plus de risque. » Pendant une seconde, son offre ressemble au repos. Puis tu remarques qu’il efface aussi les rires, les surprises et les petits personnages dessinés pour traverser une mauvaise soirée. Il ne distingue pas la douleur de ce qui a survécu à la douleur.`,
`The Blank arrives without sound. It does not resemble a monster. It resembles a perfectly clean page, enormous and peaceful, moving forward as libraries disappear. Its voice is gentle. “You are tired of beginning again. Tired of comparing. Give me the drawings that might disappoint someone. I will keep only those you can be proud of. No more awkwardness, embarrassment, or risk.” For one second, the offer feels like rest. Then you notice it is also erasing laughter, surprises, and the little characters drawn to survive a difficult evening. It cannot distinguish pain from what survived the pain.`)},
{c:3,img:'storm',s:B('VEY','VEY'),title:B('Attrape les ombres d’encre','Catch the Ink Shadows'),text:B(
`Vey découvre que le Blanc ne peut effacer ce qui possède encore une ombre. Cinq taches d’encre courent sur les murs : les derniers reflets de personnages disparus. Touche-les avant qu’elles atteignent la lumière vide. Chacune retrouvera brièvement sa forme — une danseuse aux pieds trop grands, un dragon minuscule, un robot qui collectionne les fleurs, une héroïne sans nom, un animal impossible. Elles n’ont pas besoin d’un chapitre complet. Pour l’instant, il suffit que quelqu’un les remarque et dise, sans rire : « Je t’ai vue. »`,
`Vey discovers the Blank cannot erase anything that still possesses a shadow. Five ink marks race across the walls: the final reflections of vanished characters. Touch them before they reach the empty light. Each will briefly recover its form—a dancer with oversized feet, a tiny dragon, a robot who collects flowers, a nameless heroine, an impossible animal. They do not need an entire chapter. For now, they only need someone to notice them and say, without laughing, “I saw you.”`),type:'shadows'},
{c:3,img:'storm',s:B('MERIDIAN','MERIDIAN'),title:B('Un plan qui accepte d’échouer','A Plan Allowed to Fail'),text:B(
`Meridian déroule un plan comportant exactement quarante-deux étapes. À la troisième, un morceau de plafond détruit les étapes quatre à trente-neuf. Il fixe le papier pendant une longue seconde, puis le plie en avion et l’envoie vers Cinder. « Révision scientifique », annonce-t-il. « Nous improvisons. » Les gardiens combinent leurs pouvoirs de façons absurdes et merveilleuses : Aster lance des pages jusqu’à Lyra, Solenne allume leurs bords, Vey dessine des portes sur les murs, et Cinder transporte l’Encre de Mémoire dans une théière. Pour la première fois, Meridian rit de quelque chose qui n’était pas prévu.`,
`Meridian unrolls a plan containing exactly forty-two steps. At step three, a falling piece of ceiling destroys steps four through thirty-nine. He studies the paper for a long moment, folds it into an airplane, and sends it toward Cinder. “Scientific revision,” he announces. “We improvise.” The guardians combine their abilities in absurd and wonderful ways: Aster throws pages to Lyra, Solenne lights their edges, Vey draws doors upon walls, and Cinder carries the Ink of Memory inside a teapot. For the first time, Meridian laughs at something that was not planned.`)},
{c:3,img:'storm',s:B('LE BLANC','THE BLANK'),title:B('Que réponds-tu au vide?','What Do You Tell the Emptiness?'),text:B(
`Le Blanc te bloque au pied de la Reliure. « Tu ne peux pas sauver toutes les idées », dit-il. C’est vrai. « Tu ne termineras pas chaque dessin. » C’est vrai aussi. « Certaines personnes ne comprendront jamais ce que tu crées. » Encore vrai. Les gardiens attendent. Ils ne veulent pas que tu nies ces peurs, car une réponse fausse ne produirait qu’une lumière fragile. Tu dois choisir une phrase assez honnête pour contenir la peur sans lui donner toute la page.`,
`The Blank blocks you at the foot of the Binding. “You cannot save every idea,” it says. True. “You will not finish every drawing.” Also true. “Some people will never understand what you create.” True again. The guardians wait. They do not want you to deny these fears, because a false answer would create only fragile light. You must choose a sentence honest enough to contain the fear without giving it the entire page.`),type:'choice',key:'answer',options:[
{v:'begin',trait:'courage',label:B('« Je peux quand même commencer. »','“I can begin anyway.”'),detail:B('La peur n’obtient pas le premier trait.','Fear does not get the first line.'),feedback:B('L’Encre de Courage apparaît entre tes doigts.','The Ink of Courage appears between your fingers.')},
{v:'few',trait:'kindness',label:B('« Quelques idées suffisent pour compter. »','“A few ideas are enough to matter.”'),detail:B('La valeur ne dépend pas du nombre.','Worth is not a number.'),feedback:B('Les pages sauvées se rapprochent autour de toi.','The rescued pages gather around you.')},
{v:'change',trait:'wonder',label:B('« Alors mes dessins changeront avec moi. »','“Then my drawings will change with me.”'),detail:B('Une histoire vivante n’est jamais figée.','A living story is never frozen.'),feedback:B('Le ciel blanc se fend d’une ligne violette.','A violet line splits the white sky.')}
]},
{c:3,img:'finale',s:B('LES SEPT GARDIENS','THE SEVEN GUARDIANS'),title:B('La dernière encre','The Final Ink'),text:B(
`L’Encre de Courage n’est pas rouge ni dorée. Elle prend la couleur de la ligne que tu dessines avec elle. Les sept gardiens se rassemblent : Aster apporte la force de rester, Lyra la permission d’être étrange, Meridian la capacité de changer de plan, Solenne la mémoire, Vey les chemins cachés, Cinder la petite chaleur qui survit, et Vigil l’espace encore inachevé. Ils ne forment pas une armée. Ils forment une boîte à outils. La Reliure ne peut pas être réparée par le personnage le plus puissant. Elle doit être redessinée par quelqu’un qui accepte que chaque trait puisse trembler.`,
`The Ink of Courage is neither red nor gold. It becomes the color of whatever line you draw with it. The seven guardians gather: Aster brings the strength to remain, Lyra permission to be strange, Meridian the ability to change a plan, Solenne memory, Vey hidden roads, Cinder the small warmth that survives, and Vigil the space still unfinished. They are not an army. They are a toolbox. The Binding cannot be repaired by the most powerful character. It must be redrawn by someone willing to let every line tremble.`)},
{c:4,img:'finale',s:B('{guide}','{guide}'),title:B('Le trait qui relie tout','The Line That Connects Everything'),text:B(
`Tu poses ton carnet devant la déchirure. Les encres d’Émerveillement et de Mémoire tourbillonnent autour du crayon. La troisième naît dans ta main. Derrière toi, les pages retrouvées forment une constellation qui reproduit la toute première feuille : les personnages réconfortants, dessinés ensemble sans décor, simplement parce que leur présence faisait du bien. Tu comprends enfin que la Reliure n’a jamais été un objet. C’est le geste qui relie une idée à quelqu’un : dessiner, montrer, offrir, raconter. Le Blanc ne peut supprimer ce lien, mais il peut encore te convaincre de ne pas le créer.`,
`You place your sketchbook before the tear. The Inks of Wonder and Memory circle the pencil. The third is born within your hand. Behind you, the recovered pages form a constellation recreating the very first sheet: comfort characters drawn together without scenery, simply because their presence felt good. At last, you understand that the Binding was never an object. It is the act connecting an idea to someone—drawing, showing, giving, telling. The Blank cannot erase that connection, but it can still persuade you not to create it.`)},
{c:4,img:'finale',s:B('LE NARRATEUR','THE NARRATOR'),title:B('Quel symbole traces-tu?','What Symbol Do You Draw?'),text:B(
`Il reste assez d’encre pour un seul symbole au centre du ciel. Ce symbole deviendra la nouvelle règle de l’Atelier. Aucun gardien ne te conseille; cette fois, même {guide} recule. Peut-être dessineras-tu une porte, pour que les idées puissent revenir après une longue absence. Peut-être une flamme, afin qu’aucune création offerte avec tendresse ne se sente seule. Peut-être une étoile incomplète, rappelant que l’émerveillement n’attend pas la perfection. Ton choix ne donnera pas une meilleure fin. Il révélera seulement la sorte de lumière que tu portes le plus naturellement.`,
`There is enough ink for one symbol at the center of the sky. That symbol will become the Atelier’s new rule. No guardian advises you; this time, even {guide} steps back. Perhaps you will draw a door, so ideas can return after a long absence. Perhaps a flame, so no creation offered with care ever feels alone. Perhaps an unfinished star, reminding everyone that wonder does not wait for perfection. Your choice will not create a better ending. It will simply reveal the kind of light you carry most naturally.`),type:'choice',key:'sigil',options:[
{v:'door',trait:'courage',label:B('Une porte ouverte','An Open Door'),detail:B('Toujours pouvoir recommencer.','Always be able to begin again.'),feedback:B('Une poignée dorée apparaît dans le ciel.','A golden handle appears in the sky.')},
{v:'flame',trait:'kindness',label:B('Une flamme partagée','A Shared Flame'),detail:B('Créer pour que quelqu’un se sente moins seul.','Create so someone feels less alone.'),feedback:B('Chaque lanterne de l’Atelier s’allume.','Every lantern in the Atelier ignites.')},
{v:'star',trait:'wonder',label:B('Une étoile inachevée','An Unfinished Star'),detail:B('Laisser de la place à l’impossible.','Leave room for the impossible.'),feedback:B('Une nouvelle constellation invente son propre nom.','A new constellation invents its own name.')}
]},
{c:4,img:'finale',s:B('LE NARRATEUR','THE NARRATOR'),title:B('L’Atelier se redessine','The Atelier Redraws Itself'),text:B(
`Ton symbole traverse la déchirure. Le ciel ne se referme pas comme si rien ne s’était produit; il se recoud avec une cicatrice lumineuse, visible entre les étoiles. Les bibliothèques reviennent différentes. Des espaces vides demeurent sur certaines tablettes, non comme des pertes, mais comme des invitations. Vigil remet son casque sans cacher la page blanche de son visage. Meridian laisse volontairement une ligne vide dans son prochain plan. Solenne ouvre sa lanterne pour que les souvenirs puissent entrer et sortir. Le Blanc rapetisse jusqu’à devenir une simple feuille neuve sur ton bureau. Il n’était pas destiné à être détruit. Il attendait que tu décides quoi y faire.`,
`Your symbol crosses the tear. The sky does not close as though nothing happened; it stitches itself together with a luminous scar, visible among the stars. The libraries return changed. Empty spaces remain upon certain shelves, not as losses but as invitations. Vigil replaces his helm without hiding the white page of his face. Meridian deliberately leaves one line empty in his next plan. Solenne opens her lantern so memories may enter and leave. The Blank shrinks until it becomes an ordinary new sheet upon your desk. It was never meant to be destroyed. It was waiting for you to decide what to make upon it.`)},
{c:4,img:'garden',s:B('{guide}','{guide}'),title:B('Avant le réveil','Before Waking'),text:B(
`Le chemin vers ta chambre réapparaît dans le bassin du jardin. {guide} marche avec toi jusqu’au bord. « Au réveil, tu te demanderas si nous étions réels », dit le gardien. « C’est une question raisonnable, mais pas très utile. Demande plutôt si ce que tu as ressenti était réel. » Cinder glisse dans ta poche un fragment de papier. Lyra promet de déplacer une étoile si tu tardes trop à revenir. Aster prétend ne pas être ému; ses cornes brillent pourtant comme deux lunes. Solenne te confie une dernière lumière : le souvenir d’avoir été attendue quelque part par des personnages qui n’exigeaient rien, sauf une autre page.`,
`The path to your bedroom reappears within the garden pool. {guide} walks with you to the edge. “When you wake, you will wonder whether we were real,” the guardian says. “That is a reasonable question, but not a useful one. Ask instead whether what you felt was real.” Cinder slips a paper fragment into your pocket. Lyra promises to move a star if you take too long to return. Aster insists he is not emotional, although his horns shine like twin moons. Solenne gives you one final light: the memory of being awaited somewhere by characters who demanded nothing except another page.`)},
{c:4,img:'cover',s:B('LE NARRATEUR','THE NARRATOR'),title:B('23 h 59, encore une fois','11:59, Once More'),text:B(
`Tu te réveilles à ton bureau une minute avant minuit. Le carnet est fermé. Le crayon repose exactement où tu l’avais laissé. Pendant un instant, rien ne prouve ton voyage. Puis tu ouvres la couverture. Entre deux pages anciennes se trouve une illustration que tu ne te rappelles pas avoir terminée : sept gardiens autour d’une jeune artiste, sous un ciel réparé par une ligne brillante. Dans la marge, une huitième silhouette attend seulement quelques traits. Tu souris. Il n’est pas nécessaire de savoir déjà qui elle deviendra. Tu poses le crayon sur le papier, et l’Atelier retient doucement son souffle.`,
`You wake at your desk one minute before midnight. The sketchbook is closed. The pencil rests exactly where you left it. For a moment, nothing proves your journey. Then you open the cover. Between two older pages lies an illustration you do not remember completing: seven guardians around a young artist beneath a sky repaired by a shining line. In the margin, an eighth silhouette waits for only a few marks. You smile. You do not need to know who they will become yet. You lower the pencil to the paper, and the Atelier gently holds its breath.`)}
];

let lang=localStorage.getItem('atelierLang')||'fr',state={index:0,name:'',guide:'aster',path:'garden',scores:{courage:0,wonder:0,kindness:0},history:[]},voiceOn=false,soundOn=true,audioCtx,ambient=[],timers=[],locked=false;
const images={cover:'assets/atelier/atelier-cover-v1.png',storm:'assets/atelier/atelier-storm-v1.png',garden:'assets/atelier/atelier-garden-v1.png',finale:'assets/atelier/atelier-finale-v1.png'};
const names={fr:{lyra:'Lyra',aster:'Aster',solenne:'Solenne',margins:'les marges sauvages',frames:'la salle des cadres',garden:'le jardin des souvenirs'},en:{lyra:'Lyra',aster:'Aster',solenne:'Solenne',margins:'the Wild Margins',frames:'the Hall of Frames',garden:'the Garden of Memories'}};
function t(v){return typeof v==='string'?v:v?.[lang]||''}
function format(v){return t(v).replaceAll('{name}',state.name).replaceAll('{guide}',names[lang][state.guide]||'Aster').replaceAll('{path}',names[lang][state.path]||'')}
function applyUI(){document.documentElement.lang=lang;document.title=lang==='fr'?'L’Atelier entre les rêves | DanPC':'The Atelier Between Dreams | DanPC';document.querySelectorAll('[data-ui]').forEach(el=>el.textContent=ui[lang][el.dataset.ui]);document.querySelectorAll('[data-ui-placeholder]').forEach(el=>el.placeholder=ui[lang][el.dataset.uiPlaceholder]);$('#langBtn').textContent=lang.toUpperCase();localStorage.setItem('atelierLang',lang);if(!storyScreen.classList.contains('hidden'))renderScene()}
function snapshot(){return{index:state.index,name:state.name,guide:state.guide,path:state.path,scores:{...state.scores},rescue:state.rescue,imperfection:state.imperfection,riddle:state.riddle,answer:state.answer,sigil:state.sigil}}
function save(){localStorage.setItem('atelierSave',JSON.stringify(snapshot()))}
function restore(s){state={...state,...s,scores:{courage:0,wonder:0,kindness:0,...s.scores},history:state.history||[]}}
function clearTimers(){timers.forEach(clearTimeout);timers=[];window.speechSynthesis?.cancel()}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1500)}
function changeBg(key){sceneBg.style.backgroundImage=`url("${images[key]}")`;sceneBg.style.filter=key==='storm'?'saturate(.9) contrast(1.05)':key==='garden'?'saturate(.9) brightness(.92)':key==='finale'?'saturate(1.12) brightness(1.02)':'saturate(.92)'}
function pushHistory(){state.history.push(snapshot());if(state.history.length>30)state.history.shift()}
function next(){if(locked)return;locked=true;pushHistory();state.index++;pageSound();if(state.index>=scenes.length){showEnding();return}save();renderScene()}
function back(){const prior=state.history.pop();if(!prior)return;restore(prior);save();renderScene()}
function renderScene(){clearTimers();locked=false;const sc=scenes[state.index];if(!sc)return;endingScreen.classList.add('hidden');startScreen.classList.add('hidden');storyScreen.classList.remove('hidden');changeBg(sc.img);const ch=chapters[sc.c][lang];$('#chapterNo').textContent=ch[0];$('#chapterTitle').textContent=ch[1];$('#speaker').textContent=format(sc.s);$('#sceneTitle').textContent=format(sc.title);storyText.innerHTML='';const p=document.createElement('p');p.textContent=format(sc.text);storyText.appendChild(p);$('#progressBar').style.width=`${((state.index+1)/scenes.length)*100}%`;$('#timeLeft').textContent=`≈ ${Math.max(1,Math.ceil((scenes.length-state.index)*1.05))} ${ui[lang].minutes}`;interaction.innerHTML='';continueBtn.classList.toggle('hidden',!!sc.type);$('#backBtn').disabled=!state.history.length;$('#backBtn').onclick=back;if(sc.type==='choice')renderChoices(sc);if(sc.type==='fragments')renderFragments();if(sc.type==='sequence')renderSequence();if(sc.type==='hold')renderHold();if(sc.type==='shadows')renderShadows();save();if(voiceOn)narrate()}
function renderChoices(sc){const wrap=document.createElement('div');wrap.className='choices';sc.options.forEach(opt=>{const b=document.createElement('button');b.className='choice';const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=t(opt.label);small.textContent=t(opt.detail);b.append(strong,small);b.onclick=()=>{if(locked)return;locked=true;wrap.querySelectorAll('button').forEach(x=>x.disabled=true);pushHistory();state[sc.key]=opt.v;if(sc.key==='guide')state.guide=opt.v;if(sc.key==='path')state.path=opt.v;state.scores[opt.trait]++;chime();toast(t(opt.feedback));state.index++;save();timers.push(setTimeout(renderScene,850))};wrap.appendChild(b)});interaction.appendChild(wrap)}
function renderFragments(){let found=0;const field=document.createElement('div'),status=document.createElement('div');field.className='fragment-field';status.className='action-status';const icons=['♈','✦','♨','◈','✎'],pos=[[8,20],[37,61],[68,14],[79,62],[20,69]];icons.forEach((icon,i)=>{const b=document.createElement('button');b.className='fragment';b.textContent=icon;b.style.left=pos[i][0]+'%';b.style.top=pos[i][1]+'%';b.style.animationDelay=(i*.25)+'s';b.setAttribute('aria-label',`${i+1}/5`);b.onclick=()=>{if(b.classList.contains('found'))return;b.classList.add('found');found++;chime(440+found*70);status.textContent=`${found}/5 ${ui[lang].fragments}`;if(found===5){pushHistory();state.scores.wonder++;state.index++;save();timers.push(setTimeout(renderScene,900))}};field.appendChild(b)});status.textContent=`0/5 ${ui[lang].fragments}`;interaction.append(field,status)}
function renderSequence(){const target=['✦','☾','♨','✦'];let entered=[];const preview=document.createElement('div'),wrap=document.createElement('div'),status=document.createElement('div');preview.className='sequence-preview';preview.textContent=target.join('  ');wrap.className='sequence';status.className='action-status';status.textContent=ui[lang].sequence;interaction.append(preview,wrap,status);timers.push(setTimeout(()=>{preview.textContent='·  ·  ·  ·';['✦','☾','♨'].forEach(symbol=>{const b=document.createElement('button');b.className='action-btn';b.textContent=symbol;b.onclick=()=>{entered.push(symbol);chime(520+entered.length*80);preview.textContent=entered.join('  ');const okay=entered.every((v,i)=>v===target[i]);if(!okay){entered=[];status.textContent=ui[lang].tryAgain;preview.textContent='·  ·  ·  ·';lowTone();return}if(entered.length===target.length){pushHistory();state.scores.wonder++;state.index++;save();timers.push(setTimeout(renderScene,800))}};wrap.appendChild(b)})},2400))}
function renderHold(){const wrap=document.createElement('div'),orb=document.createElement('div'),button=document.createElement('button');wrap.className='hold-wrap';orb.className='hold-orb';button.className='hold-button';button.innerHTML=`<span>${ui[lang].hold}</span>`;wrap.append(orb,button);interaction.appendChild(wrap);let start=0,raf=0,complete=false;const stop=()=>{if(complete)return;cancelAnimationFrame(raf);start=0;button.style.setProperty('--hold','0%')};const tick=now=>{if(!start)start=now;const progress=Math.min(1,(now-start)/3200);button.style.setProperty('--hold',`${progress*100}%`);if(progress>=1){complete=true;chime(760);pushHistory();state.scores.kindness++;state.index++;save();timers.push(setTimeout(renderScene,850));return}raf=requestAnimationFrame(tick)};button.onpointerdown=e=>{e.preventDefault();button.setPointerCapture?.(e.pointerId);raf=requestAnimationFrame(tick)};button.onpointerup=button.onpointercancel=stop;button.onpointerleave=stop}
function renderShadows(){let found=0;const field=document.createElement('div'),status=document.createElement('div');field.className='shadow-field';status.className='action-status';const pos=[[6,15],[28,58],[49,13],[67,61],[84,27]];pos.forEach((p,i)=>{const b=document.createElement('button');b.className='shadow-mark';b.textContent=['♬','♢','✿','☆','?'][i];b.style.left=p[0]+'%';b.style.top=p[1]+'%';b.style.animationDelay=(i*.2)+'s';b.onclick=()=>{if(b.classList.contains('found'))return;b.classList.add('found');found++;chime(350+found*90);status.textContent=`${found}/5`;if(found===5){pushHistory();state.scores.courage++;state.index++;save();timers.push(setTimeout(renderScene,800))}};field.appendChild(b)});status.textContent='0/5';interaction.append(field,status)}
function trait(){return Object.entries(state.scores).sort((a,b)=>b[1]-a[1])[0][0]}
function showEnding(){clearTimers();storyScreen.classList.add('hidden');endingScreen.classList.remove('hidden');changeBg('finale');const tr=trait(),endings={fr:{courage:['La Gardienne de la Porte','Tu n’attends pas que la peur disparaisse pour avancer. Tu lui laisses une place, puis tu dessines quand même. Dans ton Atelier, chaque commencement est déjà une victoire.','LE COURAGE DE COMMENCER'],wonder:['La Cartographe des Possibles','Tu regardes une page vide et tu n’y vois pas un manque : tu y vois un endroit où l’impossible n’a pas encore choisi sa forme. Ton Atelier restera toujours plus grand à l’intérieur.','L’ÉMERVEILLEMENT'],kindness:['La Gardienne des Lumières','Tu remarques ce qui risque d’être laissé seul. Tes créations deviennent des refuges, non parce qu’elles sont parfaites, mais parce qu’elles savent rester près de quelqu’un.','LA FORCE DOUCE']},en:{courage:['Keeper of the Open Door','You do not wait for fear to disappear before moving. You give it a place, then draw anyway. In your Atelier, every beginning is already a victory.','THE COURAGE TO BEGIN'],wonder:['Cartographer of Possibilities','You look at a blank page and see no absence. You see a place where the impossible has not yet chosen its shape. Your Atelier will always be larger on the inside.','WONDER'],kindness:['Keeper of the Lights','You notice what might be left alone. Your creations become refuges, not because they are perfect, but because they know how to remain beside someone.','GENTLE STRENGTH']}}[lang][tr];$('#endingTitle').textContent=endings[0];$('#endingText').textContent=endings[1];$('#endingTrait').textContent=endings[2];localStorage.removeItem('atelierSave');chime(880);if(voiceOn){const u=new SpeechSynthesisUtterance(`${endings[0]}. ${endings[1]}`);u.lang=lang==='fr'?'fr-CA':'en-CA';u.rate=.9;speechSynthesis.speak(u)}}
function startStory(saved=false){initAudio();if(saved){const data=JSON.parse(localStorage.getItem('atelierSave'));restore(data);$('#playerName').value=state.name}else{state={index:0,name:$('#playerName').value.trim()||(lang==='fr'?'L’Artiste':'The Artist'),guide:'aster',path:'garden',scores:{courage:0,wonder:0,kindness:0},history:[]};save()}startScreen.classList.add('hidden');endingScreen.classList.add('hidden');storyScreen.classList.remove('hidden');renderScene()}
function narrate(){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const sc=scenes[state.index];if(!sc)return;const u=new SpeechSynthesisUtterance(`${format(sc.s)}. ${format(sc.title)}. ${format(sc.text)}`);u.lang=lang==='fr'?'fr-CA':'en-CA';u.rate=.9;u.pitch=1;const voices=speechSynthesis.getVoices(),match=voices.find(v=>v.lang.toLowerCase().startsWith(lang));if(match)u.voice=match;speechSynthesis.speak(u)}
function initAudio(){if(audioCtx)return;audioCtx=new(window.AudioContext||window.webkitAudioContext)();const master=audioCtx.createGain();master.gain.value=soundOn ? .035 : 0;master.connect(audioCtx.destination);for(const [freq,type]of[[73.42,'sine'],[110,'triangle']]){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=.35;o.connect(g);g.connect(master);o.start();ambient.push(o)}ambient.master=master}
function chime(freq=660){if(!soundOn)return;initAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),n=audioCtx.currentTime;o.type='sine';o.frequency.setValueAtTime(freq,n);o.frequency.exponentialRampToValueAtTime(freq*1.5,n+.35);g.gain.setValueAtTime(.08,n);g.gain.exponentialRampToValueAtTime(.001,n+.5);o.connect(g);g.connect(audioCtx.destination);o.start(n);o.stop(n+.52)}
function lowTone(){if(!soundOn)return;initAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),n=audioCtx.currentTime;o.frequency.setValueAtTime(160,n);o.frequency.exponentialRampToValueAtTime(90,n+.25);g.gain.setValueAtTime(.06,n);g.gain.exponentialRampToValueAtTime(.001,n+.3);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(n+.31)}
function pageSound(){if(!soundOn)return;chime(300+Math.random()*80)}
function toggleSound(){soundOn=!soundOn;$('#soundBtn').classList.toggle('active',soundOn);if(audioCtx)ambient.master.gain.setTargetAtTime(soundOn ? .035 : 0,audioCtx.currentTime,.2);toast(soundOn?ui[lang].soundOn:ui[lang].soundOff)}
function toggleVoice(){voiceOn=!voiceOn;$('#voiceBtn').classList.toggle('active',voiceOn);toast(voiceOn?ui[lang].voiceOn:ui[lang].voiceOff);if(voiceOn&&!storyScreen.classList.contains('hidden'))narrate();else window.speechSynthesis?.cancel()}
function openSketch(){clearTimers();$('#sketchModal').classList.remove('hidden')}
function closeSketch(){$('#sketchModal').classList.add('hidden');if(voiceOn&&!storyScreen.classList.contains('hidden'))narrate()}
function makePaper(){const box=$('#paperDrift');for(let i=0;i<16;i++){const p=document.createElement('i');p.className='paper';p.style.left=Math.random()*100+'%';p.style.setProperty('--d',(11+Math.random()*13)+'s');p.style.setProperty('--x',(-90+Math.random()*180)+'px');p.style.setProperty('--r',(-30+Math.random()*60)+'deg');p.style.animationDelay=(-Math.random()*20)+'s';box.appendChild(p)}}
function stars(){const canvas=$('#stars'),ctx=canvas.getContext('2d');let points=[];function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);points=Array.from({length:Math.min(120,Math.floor(innerWidth/10))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.3+Math.random()*1.2,a:Math.random()*6}))}function draw(t){ctx.clearRect(0,0,innerWidth,innerHeight);for(const p of points){const a=.25+Math.sin(t*.001+p.a)*.25;ctx.fillStyle=`rgba(255,224,164,${a})`;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}addEventListener('resize',resize);resize();requestAnimationFrame(draw)}
$('#beginBtn').onclick=()=>startStory(false);$('#resumeBtn').onclick=()=>startStory(true);continueBtn.onclick=next;$('#langBtn').onclick=()=>{lang=lang==='fr'?'en':'fr';applyUI()};$('#soundBtn').onclick=toggleSound;$('#voiceBtn').onclick=toggleVoice;$('#sketchBtn').onclick=openSketch;$('#revealBtn').onclick=openSketch;$('#closeSketch').onclick=closeSketch;$('#sketchModal').onclick=e=>{if(e.target.id==='sketchModal')closeSketch()};$('#replayBtn').onclick=()=>{localStorage.removeItem('atelierSave');state.history=[];endingScreen.classList.add('hidden');startScreen.classList.remove('hidden');changeBg('cover')};addEventListener('keydown',e=>{if(e.key==='Escape')closeSketch()});
const saved=localStorage.getItem('atelierSave');if(saved){try{const data=JSON.parse(saved);if(data?.name){$('#resumeBtn').classList.remove('hidden');$('#playerName').value=data.name}}catch{localStorage.removeItem('atelierSave')}}applyUI();makePaper();stars();
})();
