const menu=document.querySelector('#menu'),play=document.querySelector('#play'),area=document.querySelector('#gameArea');
const instruction=document.querySelector('#instruction'),newRound=document.querySelector('#newRound');
const starCount=document.querySelector('#starCount'),celebration=document.querySelector('#celebration');
const encouragement=document.querySelector('#encouragement'),rewardIcon=document.querySelector('#rewardIcon');
const rewardTitle=document.querySelector('#rewardTitle'),rewardText=document.querySelector('#rewardText');
const themeButton=document.querySelector('#themeButton'),languageButton=document.querySelector('#languageButton');
let stars=0,currentGame='',soundOn=true,audioContext,audioMaster,audioCompressor,audioEffects,audioMusic,crowdYayBuffer,crowdYayLoading,praiseIndex=0,theme='cosmos',language='fr',lastMemorySignature='',lastMazeSignature='',storyStep=0,storyRewarded=false,storyVoiceToken=0,currentStoryKey='',ambience=null,mazeAnimation=0;

const copy={
  fr:{home:'Accueil',welcomeKicker:'MISSION DES PETITS EXPLORATEURS',welcomeTitle:'Choisis un jeu!',welcomeText:'Sans pub. Sans achat. Joue autant que tu veux.',parent:'💜 Conçu pour les petites mains — aucun lien caché dans les jeux.',play:'Jouer',listen:'Écouter',again:'Encore! 🔄',newDrawing:'Nouveau dessin! 🎨',themeCosmos:'Mode Cosmos',themeUnicorn:'Mode Licorne',soundOn:'Désactiver les sons',soundOff:'Activer les sons',
    cards:{shapes:['MISSION FORMES','Les formes','Trouve les paires'],memory:['MISSION MÉMOIRE','Mémoire spatiale','De nouvelles cartes chaque fois'],counting:['MISSION ÉTOILES','Compte les étoiles','Choisis le bon nombre'],pattern:['MISSION LOGIQUE','La suite magique','Quelle image vient après?'],maze:['MISSION CLÉS','Le labyrinthe magique','Trouve les clés et ouvre la porte'],trace:['MISSION DESSIN','Dessine avec moi','Repasse sur les modèles'],paint:['MISSION PEINTURE','Peinture magique','Une grande page pour créer'],story:['MISSION DODO','L’histoire du dodo','Écoute, choisis et continue l’aventure']},
    instructions:{shapes:'Touche une forme, puis sa maison pareille!',memory:'Trouve les deux images pareilles!',counting:'Combien vois-tu d’étoiles?',pattern:'Quelle image vient après?',maze:'Glisse ton doigt ou la souris. Trouve les trois clés puis la sortie!',trace:'Choisis une image et dessine sur les petits traits!',paint:'Dessine tout ce que tu imagines!',story:'Écoute l’histoire et choisis pour continuer.'},
    mazeKeys:'clés trouvées',mazeOneKey:'Bravo! Une clé magique!',mazeAllKeys:'Youpi! La porte est ouverte!',mazeExit:'Va maintenant jusqu’à la porte!',mazeLocked:'Il faut encore trouver les clés!',
    retry:'Essaie encore!',almost:'Presque! Essaie encore!',countAgain:'Compte encore une fois!',lookAgain:'Regarde bien la suite!',soundsOn:'Les sons sont activés!',read:'🔊 Écouter',goodNight:'Bonne nuit, petit rêveur!',reread:'Relire l’histoire 🌙',chooseStory:'Choisis ton histoire du soir',shortStory:'Petite histoire douce · 4 pages',mediumStory:'Aventure sous-marine · 6 pages',longStory:'Grande aventure calme · 7 pages',pandaTitle:'Bao et Tiko, la course de l’amitié',pandaDesc:'Un panda patient et un guépard rapide découvrent qu’avancer ensemble est encore mieux.',oceanTitle:'Mila et la baleine des rêves',oceanDesc:'Une petite tortue rassemble les sons les plus doux de l’océan pour créer une berceuse.',cosmosStory:'Lumi et l’étoile endormie',unicornStory:'Plume au château des nuages',turnPage:'Touche la page pour continuer 👆',listening:'Écoute la réponse… 🎵',anotherStory:'Choisir une autre histoire 📚',choosePicture:'Choisis ton dessin',colors:'Choisis une couleur',smallBrush:'Petit',mediumBrush:'Moyen',largeBrush:'Gros',eraser:'Gomme',undo:'Retour',clear:'Effacer tout',clearAgain:'Touche encore!',saveDrawing:'Garder l’image',drawingSaved:'Ton dessin est prêt!',finishedDrawing:'J’ai fini!'},
  en:{home:'Home',welcomeKicker:'LITTLE EXPLORERS MISSION',welcomeTitle:'Choose a game!',welcomeText:'No ads. No purchases. Play as much as you like.',parent:'💜 Made for little hands — no hidden links inside the games.',play:'Play',listen:'Listen',again:'Again! 🔄',newDrawing:'New drawing! 🎨',themeCosmos:'Cosmos Mode',themeUnicorn:'Unicorn Mode',soundOn:'Turn sounds off',soundOff:'Turn sounds on',
    cards:{shapes:['SHAPES MISSION','Shapes','Match every shape'],memory:['MEMORY MISSION','Magic Memory','New pictures every time'],counting:['COUNTING MISSION','Count the stars','Choose the right number'],pattern:['LOGIC MISSION','Magic Pattern','Which picture comes next?'],maze:['KEY MISSION','The magic maze','Find the keys and open the door'],trace:['DRAWING MISSION','Draw with me','Trace the friendly pictures'],paint:['PAINTING MISSION','Magic Paint','A big blank page to create'],story:['BEDTIME MISSION','The bedtime story','Listen, choose and continue the adventure']},
    instructions:{shapes:'Touch a shape, then its matching home!',memory:'Find the two matching pictures!',counting:'How many stars can you see?',pattern:'Which picture comes next?',maze:'Slide your finger or mouse. Find all three keys, then reach the exit!',trace:'Choose a picture and draw over the little lines!',paint:'Draw anything you can imagine!',story:'Listen to the story and choose what happens next.'},
    mazeKeys:'keys found',mazeOneKey:'Great! A magic key!',mazeAllKeys:'Yay! The door is open!',mazeExit:'Now travel to the door!',mazeLocked:'We still need to find the keys!',
    retry:'Try again!',almost:'Almost! Try again!',countAgain:'Count one more time!',lookAgain:'Look carefully at the pattern!',soundsOn:'The sounds are on!',read:'🔊 Listen',goodNight:'Good night, little dreamer!',reread:'Read the story again 🌙',chooseStory:'Choose your bedtime story',shortStory:'A gentle short story · 4 pages',mediumStory:'An underwater adventure · 6 pages',longStory:'A calm big adventure · 7 pages',pandaTitle:'Bao and Tiko’s Friendship Race',pandaDesc:'A patient panda and a speedy cheetah discover that moving together is even better.',oceanTitle:'Mila and the Dream Whale',oceanDesc:'A little turtle gathers the ocean’s softest sounds to make a bedtime song.',cosmosStory:'Lumi and the Sleepy Star',unicornStory:'Plume at the Cloud Castle',turnPage:'Touch the page to continue 👆',listening:'Listen to the answer… 🎵',anotherStory:'Choose another story 📚',choosePicture:'Choose your picture',colors:'Choose a colour',smallBrush:'Small',mediumBrush:'Medium',largeBrush:'Big',eraser:'Eraser',undo:'Undo',clear:'Clear all',clearAgain:'Tap again!',saveDrawing:'Keep picture',drawingSaved:'Your picture is ready!',finishedDrawing:'I’m finished!'}
};
Object.assign(copy.fr,{evaStory:'Les vacances enchantées de la princesse Eva',evaStoryLength:'Vacances en famille · 7 pages',evaDesc:'Carnaval, plage, souper coloré et dodo joyeux avec la princesse Marie.'});
Object.assign(copy.en,{evaStory:"Princess Eva’s Enchanted Vacation",evaStoryLength:'A family vacation · 7 pages',evaDesc:'Carnival rides, beach play, a colourful dinner, and joyful bedtime with Princess Marie.'});
const themeData={
  cosmos:{brand:'Cosmo Kids',avatar:'👽',brandIcon:'🪐',icons:{shapes:'🔷',memory:'🚀',counting:'⭐',pattern:'🛸',maze:'🔑',trace:'✏️',paint:'🎨',story:'🌙'},countIcon:'⭐',memory:['🚀','🪐','👽','🌙','🛸','⭐','☄️','🌎','☀️','🔭','🛰️','🌌','🌠','🤖','🌈','💫'],patterns:[['🚀','🌙'],['👽','🛸'],['⭐','🪐'],['🌎','🌙','☀️'],['🤖','🚀','⭐']],storyImage:'assets/cosmo-kids/bedtime-cosmos-v1.png'},
  unicorn:{brand:'Licorne Kids',avatar:'🦄',brandIcon:'🌈',icons:{shapes:'💎',memory:'🦄',counting:'🌸',pattern:'🦋',maze:'🗝️',trace:'✏️',paint:'🎨',story:'🌙'},countIcon:'🌸',memory:['🦄','🌈','🌸','🦋','👑','💖','✨','🌙','☁️','🍓','🧁','🎀','💎','🧚','🌺','⭐'],patterns:[['🦄','🌈'],['🌸','🦋'],['💖','✨'],['👑','💎','🎀'],['☁️','🌙','⭐']],storyImage:'assets/cosmo-kids/bedtime-unicorn-v1.png'}
};
const storyPageArt={
  cosmos:{src:'assets/cosmo-kids/bedtime-cosmos-pages-v2.png',columns:2,rows:2},
  unicorn:{src:'assets/cosmo-kids/bedtime-unicorn-pages-v2.png',columns:2,rows:2},
  panda:{src:'assets/cosmo-kids/bedtime-panda-pages-v2.png',columns:2,rows:4},
  ocean:{src:'assets/cosmo-kids/bedtime-ocean-pages-v2.png',columns:2,rows:3},
  eva:{src:'assets/cosmo-kids/bedtime-princess-eva-pages-v1.png',columns:2,rows:4}
};
const praiseSets={
  fr:[['Bravo!','Tu as réussi!','🌟'],['Super!','Quel beau travail!','🚀'],['Youpi!','Tu es fantastique!','🌈'],['Hourra!','Mission accomplie!','🪐'],['Yay!','Encore une victoire!','🎉'],['Magnifique!','Continue comme ça!','💫']],
  en:[['Bravo!','You did it!','🌟'],['Amazing!','Wonderful work!','🚀'],['Yay!','You are fantastic!','🌈'],['Hooray!','Mission complete!','🪐'],['Woohoo!','Another victory!','🎉'],['Wonderful!','Keep going!','💫']]
};
const encouragementSets={fr:['Oui, c’est ça!','Super choix!','Tu l’as trouvé!','Bravo, exploratrice!','Quelle championne!'],en:['Yes, that’s it!','Great choice!','You found it!','Well done, explorer!','You are a champion!']};
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const stories={
  cosmos:{
    fr:[
      {text:'La nuit est douce sur la petite lune. Lumi et Bibi suivent un sentier de lumière vers leur maison-fusée.',question:'Qui brille au-dessus du chemin?',choices:[['La petite étoile ⭐','La petite étoile bâille et éclaire doucement leurs pas.'],['La lune souriante 🌙','La lune sourit et dépose une lumière calme sur le chemin.']]},
      {text:'Dans le jardin lunaire, les fleurs ferment lentement leurs pétales. Bibi roule tout doucement pour ne pas les réveiller.',question:'De quelle couleur est la fleur la plus endormie?',choices:[['Violette 💜','La fleur violette fait un tout petit bâillement.'],['Bleue 💙','La fleur bleue se blottit sous une feuille.']]},
      {text:'Un petit nuage a peur d’être seul. Lumi lui tend la main et Bibi allume une veilleuse ronde.',question:'Que peuvent-ils dire au petit nuage?',choices:[['Bonne nuit 🌙','Le nuage se sent rassuré et ferme les yeux.'],['Nous sommes là 💛','Le nuage sourit. Il sait maintenant qu’il a des amis.']]},
      {text:'La porte de la maison-fusée s’ouvre. À l’intérieur, les couvertures sont chaudes et la petite étoile chante très bas.',question:'Que font Lumi et Bibi avant de dormir?',choices:[['Un gros câlin 🤗','Le câlin est doux comme un nuage.'],['Une grande respiration 🌬️','Ils inspirent doucement… puis soufflent lentement.']]}
    ],
    en:[
      {text:'The night is gentle on the little moon. Lumi and Bibi follow a glowing path toward their cozy rocket home.',question:'Who is shining above the path?',choices:[['The little star ⭐','The little star yawns and softly lights their steps.'],['The smiling moon 🌙','The moon smiles and lays calm light on the path.']]},
      {text:'In the moon garden, the flowers slowly close their petals. Bibi rolls very quietly so they can sleep.',question:'What color is the sleepiest flower?',choices:[['Purple 💜','The purple flower gives one tiny yawn.'],['Blue 💙','The blue flower snuggles beneath a leaf.']]},
      {text:'A small cloud is afraid to be alone. Lumi holds out a hand and Bibi turns on a round night-light.',question:'What can they say to the little cloud?',choices:[['Good night 🌙','The cloud feels safe and closes its eyes.'],['We are here 💛','The cloud smiles. Now it knows it has friends.']]},
      {text:'The rocket-home door opens. Inside, the blankets are warm and the little star sings very softly.',question:'What do Lumi and Bibi do before sleep?',choices:[['A big cuddle 🤗','The cuddle is as soft as a cloud.'],['One deep breath 🌬️','They breathe in gently… then breathe out slowly.']]}
    ],
    endings:{fr:'Lumi et Bibi se glissent sous leur couverture. La maison-fusée ferme ses petites lumières. Toute la lune se repose. Chut… bonne nuit.',en:'Lumi and Bibi snuggle under their blanket. The rocket home dims its little lights. The whole moon rests. Shhh… good night.'}
  },
  unicorn:{
    fr:[
      {text:'Plume la petite licorne et Lila la luciole suivent un arc-en-ciel endormi jusqu’au château des nuages.',question:'Comment avancent-elles sans réveiller les fleurs?',choices:[['Sur la pointe des sabots 🦄','Plume marche si doucement que les gouttes de rosée restent immobiles.'],['En volant tout bas 🪽','Lila montre un chemin léger juste au-dessus des pétales.']]},
      {text:'Une petite fleur rose bâille au bord du chemin. Ses pétales ont travaillé toute la journée.',question:'Que peut lui dire Plume?',choices:[['Bonne nuit, petite fleur 🌸','La fleur sourit et replie ses pétales.'],['Fais de beaux rêves ✨','La fleur imagine déjà un merveilleux rêve.']]},
      {text:'Un bébé nuage ne retrouve plus sa famille. Plume s’arrête et Lila fait briller sa lumière rose.',question:'Comment peuvent-elles aider le nuage?',choices:[['Suivre la luciole 💡','Le nuage suit la lumière de Lila et retrouve son chemin.'],['Tenir le sabot de Plume 💜','Le bébé nuage se sent courageux près de Plume.']]},
      {text:'Au château, un lit de nuages attend Plume. La lune souriante baisse la lumière du ciel.',question:'Que choisit Plume avant de dormir?',choices:[['Une petite histoire 📖','Lila raconte une histoire avec une voix toute douce.'],['Un câlin de nuage ☁️','Le nuage entoure Plume comme une couverture.']]}
    ],
    en:[
      {text:'Plume the little unicorn and Lila the firefly follow a sleepy rainbow toward the cloud castle.',question:'How do they move without waking the flowers?',choices:[['On tiptoe hooves 🦄','Plume walks so softly that the dew drops stay still.'],['Flying very low 🪽','Lila shows a light path just above the petals.']]},
      {text:'A small pink flower yawns beside the path. Its petals worked hard all day.',question:'What can Plume say to the flower?',choices:[['Good night, little flower 🌸','The flower smiles and folds up its petals.'],['Sweet dreams ✨','The flower is already imagining a wonderful dream.']]},
      {text:'A baby cloud cannot find its family. Plume stops and Lila makes her pink light glow.',question:'How can they help the cloud?',choices:[['Follow the firefly 💡','The cloud follows Lila’s light and finds the way home.'],['Hold Plume’s hoof 💜','The baby cloud feels brave beside Plume.']]},
      {text:'At the castle, a cloud bed is waiting for Plume. The smiling moon turns down the sky lights.',question:'What does Plume choose before sleep?',choices:[['A little story 📖','Lila tells a story in a very soft voice.'],['A cloud cuddle ☁️','The cloud wraps around Plume like a blanket.']]}
    ],
    endings:{fr:'Plume ferme les yeux. Lila devient une minuscule veilleuse rose. Le château flotte doucement sous la lune. Chut… bonne nuit.',en:'Plume closes her eyes. Lila becomes a tiny pink night-light. The castle floats gently beneath the moon. Shhh… good night.'}
  }
};

stories.panda={
  fr:[
    {text:'Ce soir, la forêt de bambous prépare la fête des lanternes. Bao le panda avance tranquillement. Tiko le jeune guépard bondit près de lui et propose une course amicale jusqu’à la lanterne de la colline.',question:'Comment Tiko veut-il commencer?',choices:[['Courir tout de suite! 🐆','Tiko part comme une flèche, pendant que Bao sourit et commence à marcher.'],['S’échauffer doucement 🌿','Tiko étire ses pattes. Bao lui montre comment respirer calmement avant de partir.']]},
    {text:'Tiko disparaît rapidement derrière les bambous. Bao continue pas à pas, en écoutant les grillons et le petit ruisseau qui chante entre les pierres.',question:'Comment Bao traverse-t-il le ruisseau?',choices:[['Sur les pierres rondes 🪨','Bao pose chaque patte avec soin et traverse sans éclabousser les poissons endormis.'],['En suivant les lucioles ✨','Les lucioles dessinent un petit pont de lumière au-dessus des pierres.']]},
    {text:'Plus loin, Tiko s’arrête devant deux sentiers. Il a couru si vite qu’il n’a pas vu le panneau. Bao se rappelle les conseils du vieux hibou.',question:'Quel chemin doivent-ils choisir?',choices:[['Le chemin sous les étoiles ⭐','Bao reconnaît les étoiles dessinées sur les pierres. C’est le bon sentier.'],['Demander au hibou 🦉','Le hibou ouvre un œil et indique gentiment le sentier qui monte.']]},
    {text:'Une pluie très légère commence. Les feuilles brillent et le chemin devient glissant. Tiko baisse les oreilles, car courir est maintenant difficile.',question:'Comment Bao aide-t-il son ami?',choices:[['Partager une grande feuille ☘️','Ils marchent ensemble sous la feuille, au rythme des petites gouttes.'],['Lui proposer de ralentir 🐾','Tiko essaie les petits pas de Bao et se sent tout de suite plus stable.']]},
    {text:'Un bambou tombé bloque le sentier. Tiko pousse très vite, mais le tronc ne bouge pas. Bao place ses pattes contre le bambou et compte doucement.',question:'Comment peuvent-ils déplacer le bambou?',choices:[['Pousser ensemble 🤝','Un, deux, trois… leurs forces réunies font rouler le bambou sur le côté.'],['Chercher un passage 🌱','Bao découvre un passage tranquille sous les feuilles et Tiko l’aide à l’élargir.']]},
    {text:'La colline est proche, mais Tiko est fatigué. Bao reste à ses côtés. Ils entendent déjà le petit carillon de la lanterne au sommet.',question:'Que dit Bao pour encourager Tiko?',choices:[['Un petit pas à la fois 💚','Tiko respire, fait un petit pas, puis un autre. La montée semble plus douce.'],['Nous finirons ensemble 🌙','Tiko sourit. Il n’a plus besoin d’être le premier, seulement d’être avec son ami.']]},
    {text:'Bao et Tiko atteignent la lanterne exactement au même moment. Les animaux de la forêt applaudissent doucement. Tiko comprend que Bao n’était pas le plus rapide, mais qu’il n’a jamais abandonné.',question:'Que font les deux amis avant de rentrer?',choices:[['Ils se disent merci 💛','Tiko remercie Bao pour sa patience, et Bao remercie Tiko pour son courage.'],['Ils regardent la lune 🌕','Assis côte à côte, ils regardent la lune et respirent lentement.']]}
  ],
  en:[
    {text:'Tonight, the bamboo forest is preparing its lantern festival. Bao the panda walks peacefully. Tiko the young cheetah bounces beside him and suggests a friendly race to the hilltop lantern.',question:'How does Tiko want to begin?',choices:[['Run right away! 🐆','Tiko shoots ahead like an arrow while Bao smiles and starts walking.'],['Warm up gently 🌿','Tiko stretches his paws. Bao shows him how to breathe calmly before they begin.']]},
    {text:'Tiko quickly disappears behind the bamboo. Bao continues step by step, listening to the crickets and the little stream singing between the stones.',question:'How does Bao cross the stream?',choices:[['On the round stones 🪨','Bao places each paw carefully and crosses without waking the sleepy fish.'],['By following fireflies ✨','The fireflies draw a tiny bridge of light above the stones.']]},
    {text:'Farther along, Tiko stops where the trail splits in two. He ran so fast that he missed the sign. Bao remembers the old owl’s advice.',question:'Which trail should they choose?',choices:[['The trail under the stars ⭐','Bao recognizes the stars painted on the stones. It is the right trail.'],['Ask the owl 🦉','The owl opens one eye and kindly points toward the climbing trail.']]},
    {text:'A very gentle rain begins. The leaves sparkle and the trail becomes slippery. Tiko lowers his ears because running is difficult now.',question:'How does Bao help his friend?',choices:[['Share a big leaf ☘️','They walk together beneath the leaf to the rhythm of tiny raindrops.'],['Ask him to slow down 🐾','Tiko tries Bao’s little steps and immediately feels steadier.']]},
    {text:'A fallen bamboo blocks the trail. Tiko pushes very quickly, but the trunk does not move. Bao puts his paws against it and counts slowly.',question:'How can they move the bamboo?',choices:[['Push together 🤝','One, two, three… their combined strength rolls the bamboo aside.'],['Find a passage 🌱','Bao discovers a quiet path beneath the leaves and Tiko helps make it wider.']]},
    {text:'The hilltop is close, but Tiko is tired. Bao stays beside him. They can already hear the lantern’s little chime above them.',question:'What does Bao say to encourage Tiko?',choices:[['One small step at a time 💚','Tiko breathes, takes one little step, then another. The climb feels softer.'],['We will finish together 🌙','Tiko smiles. He no longer needs to be first; he only needs to be with his friend.']]},
    {text:'Bao and Tiko reach the lantern at exactly the same moment. The forest animals clap softly. Tiko understands that Bao was not the fastest, but he never gave up.',question:'What do the friends do before going home?',choices:[['They say thank you 💛','Tiko thanks Bao for his patience, and Bao thanks Tiko for his courage.'],['They watch the moon 🌕','Sitting side by side, they watch the moon and breathe slowly.']]}
  ],
  endings:{fr:'Bao et Tiko redescendent ensemble sous les lucioles. La forêt devient silencieuse, les bambous se balancent doucement et la grande lanterne veille sur leurs rêves. Chut… bonne nuit.',en:'Bao and Tiko walk home together beneath the fireflies. The forest grows quiet, the bamboo sways gently, and the great lantern watches over their dreams. Shhh… good night.'}
};

stories.ocean={
  fr:[
    {text:'Sous la lumière de la lune, Mila la petite tortue n’arrive pas encore à dormir. Au loin, Lune la grande baleine fredonne une chanson si douce que les bulles dansent autour d’elle.',question:'Quel son Mila veut-elle écouter en premier?',choices:[['Les petites bulles 🫧','Ploc, ploc, ploc… les bulles montent lentement comme de minuscules notes de musique.'],['Les algues qui se balancent 🌿','Les algues font chuuut, chuuut, comme une couverture qui glisse sur le lit.']]},
    {text:'Mila et Lune décident de recueillir les sons les plus calmes de l’océan. Près du jardin de corail, une bulle musicale est coincée entre deux branches violettes.',question:'Comment peuvent-elles libérer la bulle?',choices:[['Souffler tout doucement 🌬️','Mila souffle un minuscule courant. La bulle se libère et fait ding en tournoyant.'],['Demander au petit crabe 🦀','Le crabe écarte délicatement les branches avec ses pinces et salue la bulle.']]},
    {text:'Plus loin, une famille de poissons-bébés cherche un endroit tranquille pour dormir. Le courant remue encore leurs petites couvertures d’algues.',question:'Comment Mila peut-elle calmer le courant?',choices:[['Nager avec de petits mouvements 🐢','Mila bouge ses nageoires très lentement. Le courant devient doux comme une caresse.'],['Suivre Lune de très près 🐋','Lune nage au ralenti et protège les poissons dans son grand sillage calme.']]},
    {text:'Le chemin passe devant une grotte sombre. Mila hésite un peu. Lune reste près d’elle et les méduses allument leurs veilleuses roses.',question:'Qu’est-ce qui aide Mila à se sentir courageuse?',choices:[['Une coquille lumineuse 🐚','Mila tient la petite coquille. Sa lumière chaude dessine un chemin rassurant.'],['Toucher la nageoire de Lune 💙','Près de son amie, Mila respire doucement et la grotte ne semble plus si grande.']]},
    {text:'Toutes les notes sont maintenant réunies: les bulles, les algues, le courant et les petites veilleuses. Il manque seulement le son qui terminera la berceuse.',question:'Quel dernier son choisissent-elles?',choices:[['Le cœur calme de Lune 💗','Boum… boum… le cœur de Lune donne à la chanson un rythme lent et rassurant.'],['Le tintement de la lune ✨','Un rayon touche les coquillages: ding, ding… toute la mer devient silencieuse pour écouter.']]},
    {text:'Mila rapporte la berceuse jusqu’à sa maison-coquillage. Autour d’elle, les poissons ferment les yeux et les méduses baissent leurs lumières. Lune chante une dernière note.',question:'Que fait Mila avant de s’endormir?',choices:[['Une grande respiration 🌊','Mila inspire lentement… puis souffle une petite bulle qui monte vers la lune.'],['Un câlin à sa couverture 🐚','Mila se blottit dans sa couverture douce et remercie Lune pour la belle aventure.']]}
  ],
  en:[
    {text:'Under the moonlight, Mila the little turtle is not quite ready to sleep. Far away, Lune the great whale hums a song so gentle that bubbles dance around her.',question:'Which sound does Mila want to hear first?',choices:[['The tiny bubbles 🫧','Pop, pop, pop… the bubbles float slowly upward like little music notes.'],['The swaying sea grass 🌿','The sea grass whispers shhh, shhh, like a blanket sliding over a bed.']]},
    {text:'Mila and Lune decide to gather the ocean’s calmest sounds. Near the coral garden, a musical bubble is caught between two purple branches.',question:'How can they free the bubble?',choices:[['Blow very gently 🌬️','Mila blows a tiny current. The bubble comes free and sings ding as it spins.'],['Ask the little crab 🦀','The crab carefully opens the branches with his claws and waves to the bubble.']]},
    {text:'Farther along, a family of baby fish is looking for a quiet place to sleep. The current keeps stirring their little sea-grass blankets.',question:'How can Mila calm the current?',choices:[['Swim with tiny movements 🐢','Mila moves her flippers very slowly. The current becomes as gentle as a cuddle.'],['Stay close behind Lune 🐋','Lune swims slowly and shelters the fish inside her wide, peaceful wake.']]},
    {text:'The path passes a dark cave. Mila hesitates. Lune stays close, and the jellyfish turn on their pink night-lights.',question:'What helps Mila feel brave?',choices:[['A glowing seashell 🐚','Mila holds the little shell. Its warm glow draws a safe path ahead.'],['Touch Lune’s flipper 💙','Beside her friend, Mila breathes gently and the cave no longer feels so big.']]},
    {text:'All the notes are ready now: bubbles, sea grass, the current and tiny night-lights. They need just one final sound to finish the lullaby.',question:'Which last sound do they choose?',choices:[['Lune’s peaceful heartbeat 💗','Thump… thump… Lune’s heart gives the song a slow and comforting rhythm.'],['The moon’s little chime ✨','A moonbeam touches the shells: ding, ding… the whole sea grows quiet to listen.']]},
    {text:'Mila carries the lullaby home to her shell house. Around her, the fish close their eyes and the jellyfish dim their lights. Lune sings one last note.',question:'What does Mila do before falling asleep?',choices:[['Take one deep breath 🌊','Mila breathes in slowly… then blows one small bubble toward the moon.'],['Cuddle her blanket 🐚','Mila snuggles into her soft blanket and thanks Lune for their lovely adventure.']]}
  ],
  endings:{fr:'La berceuse voyage doucement dans tout l’océan. Mila ferme les yeux dans sa maison-coquillage, Lune veille au loin et même les vagues s’endorment. Chut… bonne nuit.',en:'The lullaby drifts gently across the whole ocean. Mila closes her eyes inside her shell home, Lune watches nearby, and even the waves fall asleep. Shhh… good night.'}
};

stories.eva={
  fr:[
    {text:'Ce matin-là, la princesse Eva ouvre les rideaux avec un grand sourire: les vacances en famille commencent! Maman plie les chapeaux, papa ferme la petite valise et la princesse Marie, sa douce licorne, trotte près de la porte.',question:'Quel trésor Eva place-t-elle dans sa valise?',choices:[['Son maillot étoilé ⭐','Eva le dépose soigneusement sur ses vêtements. Elle imagine déjà les vagues qui chatouillent ses pieds.'],['Son toutou préféré 🧸','Le petit toutou aura lui aussi une place bien douce pour le voyage.']]},
    {text:'Après le voyage, la famille arrive dans une ville au bord de la mer. Le carnaval brille de mille lumières. Un carrousel tourne doucement pendant qu’une musique joyeuse flotte dans l’air.',question:'Quel manège Eva veut-elle essayer en premier?',choices:[['Le beau carrousel 🎠','Eva choisit un cheval blanc. La princesse Marie galope doucement à côté comme si elle faisait partie du manège.'],['Le petit train 🚂','Toute la famille monte à bord. Tchou-tchou! Le train fait tranquillement le tour du carnaval.']]},
    {text:'Puis Eva, Marie, maman et papa montent dans la grande roue. La cabine s’élève lentement. En haut, l’océan ressemble à une couverture bleue et les lumières du carnaval scintillent comme des étoiles.',question:'Que préfère regarder Eva tout en haut?',choices:[['L’océan qui brille 🌊','Un rayon doré danse sur l’eau. Eva respire doucement et admire le grand bleu.'],['Les petites lumières ✨','Eva compte les lumières une à une pendant que Marie regarde les couleurs tourner.']]},
    {text:'Le lendemain, tout le monde va à la plage. Eva et la princesse Marie construisent un immense château de sable. Maman et papa restent tout près sous un parasol turquoise et corail.',question:'Que faut-il ajouter au château?',choices:[['Une couronne de coquillages 🐚','Eva place les coquillages tout en haut. Le château devient digne de deux princesses.'],['Un drapeau arc-en-ciel 🌈','Marie touche le petit drapeau avec sa corne. Il se met à flotter dans la brise.']]},
    {text:'Au bord de l’eau, les vagues arrivent doucement puis repartent en laissant de minuscules traces. Eva et Marie éclaboussent leurs pieds sans aller trop loin. Soudain, une coquille étincelante apparaît dans le sable.',question:'Que font-elles avec la coquille?',choices:[['Elles écoutent la mer 👂','Eva approche la coquille de son oreille. Elle entend un doux chuuut, comme une chanson de l’océan.'],['Elles la montrent à la famille 💖','Maman et papa admirent la découverte. Puis Eva la remet délicatement près de l’eau.']]},
    {text:'Quand le soleil devient orange, la famille se lave les mains et s’assoit pour souper. La table est remplie de couleurs: légumes croquants, riz, un bon plat nourrissant, fruits frais et grands verres d’eau.',question:'Comment Eva transforme-t-elle le souper en fête?',choices:[['Elle goûte une couleur à la fois 🥦','Vert, rouge, orange… Eva découvre que chaque couleur a un goût différent et délicieux.'],['Elle porte un toast à la famille 🥤','Tout le monde lève son verre d’eau. À nos belles vacances et à cette merveilleuse journée!']]},
    {text:'De retour dans la chambre, Eva prend son bain, brosse ses dents et enfile son pyjama turquoise couvert d’étoiles. Elle reçoit un câlin de maman, un bisou de papa, puis raconte à Marie ses moments préférés.',question:'Quelle pensée Eva choisit-elle avant de dormir?',choices:[['Trois moments heureux 💛','Eva pense au carrousel, au château de sable et au souper en famille. Son cœur devient tout léger.'],['Un souhait de bonne nuit 🌙','Elle souhaite bonne nuit à la mer, au carnaval, à sa famille et à la princesse Marie.']]}
  ],
  en:[
    {text:'That morning, Princess Eva opens the curtains with a giant smile: the family vacation is beginning! Mom folds the hats, Dad closes the little suitcase, and Princess Marie, her gentle unicorn, trots beside the door.',question:'Which treasure does Eva pack in her suitcase?',choices:[['Her starry swimsuit ⭐','Eva carefully lays it over her clothes. She can already imagine the waves tickling her feet.'],['Her favourite teddy 🧸','The little teddy will have a soft place to rest during the journey too.']]},
    {text:'After the journey, the family arrives in a town beside the sea. The carnival glows with a thousand lights. A carousel turns gently while cheerful music floats through the air.',question:'Which ride does Eva want to try first?',choices:[['The beautiful carousel 🎠','Eva chooses a white horse. Princess Marie trots gently beside her as if she belongs on the ride.'],['The little train 🚂','The whole family climbs aboard. Choo-choo! The train makes a peaceful loop around the carnival.']]},
    {text:'Next, Eva, Marie, Mom, and Dad ride the Ferris wheel. Their car rises slowly. From the top, the ocean looks like a blue blanket, and the carnival lights sparkle like stars.',question:'What does Eva like watching from the top?',choices:[['The shining ocean 🌊','A golden beam dances over the water. Eva breathes softly and admires the great blue sea.'],['The tiny lights ✨','Eva counts the lights one by one while Marie watches the colours turn.']]},
    {text:'The next day, everyone goes to the beach. Eva and Princess Marie build an enormous sandcastle. Mom and Dad stay very close beneath a turquoise-and-coral umbrella.',question:'What should they add to the castle?',choices:[['A seashell crown 🐚','Eva places the shells at the very top. The castle is now worthy of two princesses.'],['A rainbow flag 🌈','Marie touches the tiny flag with her horn. It begins to flutter in the breeze.']]},
    {text:'At the water’s edge, gentle waves arrive and leave tiny tracks behind. Eva and Marie splash their feet without going too far. Suddenly, a sparkling shell appears in the sand.',question:'What do they do with the shell?',choices:[['Listen to the sea 👂','Eva holds the shell to her ear. She hears a soft shhh, like an ocean song.'],['Show it to the family 💖','Mom and Dad admire their discovery. Then Eva gently returns it near the water.']]},
    {text:'When the sun turns orange, the family washes their hands and sits down for dinner. The table is full of colour: crunchy vegetables, rice, a wholesome main dish, fresh fruit, and big glasses of water.',question:'How does Eva turn dinner into a celebration?',choices:[['Taste one colour at a time 🥦','Green, red, orange… Eva discovers that every colour has a different delicious taste.'],['Make a family toast 🥤','Everyone lifts a glass of water. To our lovely vacation and this wonderful day!']]},
    {text:'Back in the room, Eva has her bath, brushes her teeth, and puts on turquoise pajamas covered in stars. Mom gives her a cuddle, Dad gives her a kiss, and she tells Marie about her favourite moments.',question:'Which thought does Eva choose before sleep?',choices:[['Three happy moments 💛','Eva remembers the carousel, the sandcastle, and family dinner. Her heart feels light and peaceful.'],['A good-night wish 🌙','She wishes good night to the sea, the carnival, her family, and Princess Marie.']]}
  ],
  endings:{fr:'Eva ferme les yeux avec un sourire. La princesse Marie se blottit près du lit. Les bons aliments ont donné de la force à son corps, les câlins ont rempli son cœur et tous les beaux souvenirs commencent à danser dans ses rêves. Chut… bonnes vacances et bonne nuit.',en:'Eva closes her eyes with a smile. Princess Marie curls up beside the bed. Good food gave her body strength, cuddles filled her heart, and every beautiful memory begins dancing through her dreams. Shhh… happy vacation and good night.'}
};

function audioReady(){if(!soundOn)return;if(!audioContext){audioContext=new(window.AudioContext||window.webkitAudioContext)();audioMaster=audioContext.createGain();audioMaster.gain.value=1.2;audioCompressor=audioContext.createDynamicsCompressor();audioCompressor.threshold.value=-18;audioCompressor.knee.value=22;audioCompressor.ratio.value=6;audioCompressor.attack.value=.004;audioCompressor.release.value=.24;audioEffects=audioContext.createGain();audioEffects.gain.value=2.45;audioMusic=audioContext.createGain();audioMusic.gain.value=2.05;audioEffects.connect(audioCompressor);audioMusic.connect(audioCompressor);audioCompressor.connect(audioMaster);audioMaster.connect(audioContext.destination)}if(audioContext.state==='suspended')audioContext.resume();preloadCrowdYay();return audioContext}
function preloadCrowdYay(){
  if(crowdYayBuffer||crowdYayLoading||!audioContext)return;crowdYayLoading=fetch('assets/cosmo-kids/kids-crowd-yay.mp3').then(response=>{if(!response.ok)throw new Error('crowd sound');return response.arrayBuffer()}).then(data=>audioContext.decodeAudioData(data)).then(buffer=>crowdYayBuffer=buffer).catch(()=>null)
}
function tone(frequency,delay=0,duration=.14,volume=.08,wave='sine',endFrequency=frequency){
  const ctx=audioReady();if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain(),now=ctx.currentTime+delay;
  o.connect(g);g.connect(audioEffects);o.type=wave;o.frequency.setValueAtTime(frequency,now);o.frequency.exponentialRampToValueAtTime(Math.max(40,endFrequency),now+duration);
  g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(volume,now+.018);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.start(now);o.stop(now+duration+.02);
}
function stopAmbience(){if(!ambience)return;clearInterval(ambience.timer);ambience.nodes.forEach(node=>{try{node.stop()}catch{}try{node.disconnect()}catch{}});try{ambience.master.disconnect()}catch{}ambience=null}
function ambientNote(frequency,duration=.75,volume=.035){if(!ambience)return;const ctx=audioContext,o=ctx.createOscillator(),g=ctx.createGain(),now=ctx.currentTime;o.type='sine';o.frequency.value=frequency;g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(volume,now+.08);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g);g.connect(ambience.master);o.start(now);o.stop(now+duration+.05)}
function startAmbience(kind='dream'){
  stopAmbience();const ctx=audioReady();if(!ctx)return;const master=ctx.createGain();master.gain.value=kind==='forest'?.032:kind==='ocean'?.027:.024;master.connect(audioMusic);const nodes=[];
  const buffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.16;const breeze=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),breezeGain=ctx.createGain();breeze.buffer=buffer;breeze.loop=true;filter.type='lowpass';filter.frequency.value=kind==='forest'?760:kind==='ocean'?340:430;breezeGain.gain.value=kind==='forest'?.22:kind==='ocean'?.18:.14;breeze.connect(filter);filter.connect(breezeGain);breezeGain.connect(master);breeze.start();nodes.push(breeze);
  for(const frequency of kind==='forest'?[98,147]:kind==='ocean'?[82,123]:[110,165]){const drone=ctx.createOscillator(),gain=ctx.createGain();drone.type='sine';drone.frequency.value=frequency;gain.gain.value=.035;drone.connect(gain);gain.connect(master);drone.start();nodes.push(drone)}
  ambience={kind,master,nodes,timer:setInterval(()=>{if(kind==='forest'){ambientNote(1900+Math.random()*900,.16,.026);setTimeout(()=>ambientNote(2200+Math.random()*700,.12,.018),180)}else if(kind==='ocean'){ambientNote([262,330,392][Math.floor(Math.random()*3)],1.6,.021);setTimeout(()=>ambientNote(720+Math.random()*260,.22,.012),700)}else{ambientNote([392,523,659][Math.floor(Math.random()*3)],1.25,.025)}},kind==='forest'?3900:kind==='ocean'?4700:5200)};
}
function applause(){
  const ctx=audioReady();if(!ctx)return;
  for(let i=0;i<16;i++){const start=ctx.currentTime+.05+i*.045+Math.random()*.035,buffer=ctx.createBuffer(1,Math.floor(ctx.sampleRate*.055),ctx.sampleRate),data=buffer.getChannelData(0);
    for(let j=0;j<data.length;j++)data[j]=(Math.random()*2-1)*(1-j/data.length);
    const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=buffer;filter.type='bandpass';filter.frequency.value=900+Math.random()*1200;gain.gain.value=.035+Math.random()*.025;
    source.connect(filter);filter.connect(gain);gain.connect(audioEffects);source.start(start)}
}
function kidsCrowdYay(){
  const ctx=audioReady();if(!ctx)return;const start=ctx.currentTime+.025;
  if(crowdYayBuffer){const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=crowdYayBuffer;gain.gain.value=.42;source.connect(gain);gain.connect(audioEffects);source.start(start);source.stop(start+Math.min(2.9,crowdYayBuffer.duration))}
  const crowd=ctx.createGain();crowd.gain.value=.88;crowd.connect(audioEffects);
  for(let i=0;i<10;i++){const when=start+Math.random()*.15,duration=.95+Math.random()*.38,pitch=245+Math.random()*95,voice=ctx.createOscillator(),voiceGain=ctx.createGain(),pan=ctx.createStereoPanner?ctx.createStereoPanner():ctx.createGain();voice.type=i%3?'sawtooth':'square';voice.frequency.setValueAtTime(pitch,when);voice.frequency.exponentialRampToValueAtTime(pitch*1.25,when+duration*.45);voice.frequency.exponentialRampToValueAtTime(pitch*.94,when+duration);voiceGain.gain.setValueAtTime(.001,when);voiceGain.gain.linearRampToValueAtTime(.022+Math.random()*.012,when+.07);voiceGain.gain.setValueAtTime(.026,when+duration*.68);voiceGain.gain.exponentialRampToValueAtTime(.001,when+duration);if(pan.pan)pan.pan.value=-.85+Math.random()*1.7;voiceGain.connect(pan);pan.connect(crowd);[[620,360,7],[1850,2450,8],[2700,3200,10]].forEach(([from,to,q],index)=>{const filter=ctx.createBiquadFilter();filter.type='bandpass';filter.Q.value=q;filter.frequency.setValueAtTime(from+(Math.random()-.5)*120,when);filter.frequency.exponentialRampToValueAtTime(to+(Math.random()-.5)*160,when+duration);voice.connect(filter);filter.connect(voiceGain)});voice.start(when);voice.stop(when+duration+.03)}
}
function speak(text,calm=false,onDone){
  if(!soundOn||!('speechSynthesis'in window)){if(onDone)setTimeout(onDone,350);return}
  speechSynthesis.cancel();const voice=new SpeechSynthesisUtterance(text);voice.lang=language==='fr'?'fr-CA':'en-CA';voice.pitch=calm?1.08:1.35;voice.rate=calm?.78:.92;voice.volume=1;
  if(onDone){let finished=false,fallback;const finish=()=>{if(finished)return;finished=true;clearTimeout(fallback);setTimeout(onDone,700)};voice.onend=finish;voice.onerror=finish;fallback=setTimeout(finish,Math.min(15000,Math.max(6500,text.length*130)))}speechSynthesis.speak(voice)
}
function speakPraise(text){speak(text)}
function sound(type='good'){
  const fx=window.DanArcadeFX;
  if(type==='flip')fx?.play('card',{enabled:soundOn,volume:.1,rate:1.28,cooldown:80});
  if(type==='key')fx?.play('magic',{enabled:soundOn,volume:.12,rate:1.18,cooldown:160});
  if(type==='unlock'){fx?.play('door',{enabled:soundOn,volume:.12,rate:1.35,duration:.65});fx?.burst(document.querySelector('.game-area'),'#ffd978',18)}
  if(type==='tap'){tone(430,0,.07,.045,'sine',520);return}if(type==='flip'){tone(330,0,.08,.05,'triangle',520);return}
  if(type==='no'){tone(210,0,.13,.065,'triangle',155);tone(155,.12,.14,.05,'triangle',120);return}
  if(type==='match'){tone(520,0,.1,.065);tone(660,.09,.1,.07);tone(820,.18,.13,.075);return}
  if(type==='step'){tone(280,0,.055,.028,'sine',340);return}
  if(type==='key'){tone(660,0,.12,.075,'triangle',880);tone(880,.09,.15,.08,'sine',1180);tone(1180,.18,.2,.07,'sine',1500);return}
  if(type==='unlock'){[523,659,784,1047].forEach((f,i)=>tone(f,i*.08,.28,.075,'triangle',f*1.08));return}
  tone(520,0,.12,.075);tone(660,.09,.12,.08);tone(880,.18,.2,.09);
}
function cheer(message){const options=encouragementSets[language];encouragement.textContent=message||options[Math.floor(Math.random()*options.length)];encouragement.classList.remove('show');void encouragement.offsetWidth;encouragement.classList.add('show');setTimeout(()=>encouragement.classList.remove('show'),900)}
function burst(){const icons=theme==='cosmos'?['⭐','✨','💜','💚']:['🌸','✨','💖','🌈'];for(let i=0;i<18;i++){const p=document.createElement('i');p.className='spark';p.textContent=icons[i%icons.length];p.style.setProperty('--x',`${(Math.random()-.5)*520}px`);p.style.setProperty('--y',`${-100-Math.random()*330}px`);p.style.setProperty('--r',`${Math.random()*540-270}deg`);celebration.append(p);setTimeout(()=>p.remove(),1500)}}
function celebrate(onComplete){
  stars++;starCount.textContent=stars;starCount.parentElement.classList.remove('score-pop');void starCount.offsetWidth;starCount.parentElement.classList.add('score-pop');
  const praises=praiseSets[language],praise=praises[praiseIndex++%praises.length];rewardTitle.textContent=praise[0];rewardText.textContent=praise[1];rewardIcon.textContent=praise[2];
  sound('good');setTimeout(kidsCrowdYay,70);setTimeout(applause,180);setTimeout(()=>speakPraise(`${praise[0]} ${praise[1]}`),1450);celebration.classList.add('show');celebration.setAttribute('aria-hidden','false');burst();
  setTimeout(()=>{celebration.classList.remove('show');celebration.setAttribute('aria-hidden','true');if(onComplete){newRound.classList.add('hidden');onComplete()}else newRound.classList.remove('hidden')},2700);
}
function labels(){return copy[language]}
function cardCopy(game){const base=[...labels().cards[game]];if(game==='memory')base[1]=theme==='cosmos'?(language==='fr'?'Mémoire spatiale':'Space Memory'):(language==='fr'?'Mémoire enchantée':'Enchanted Memory');if(game==='counting'){base[0]=language==='fr'?(theme==='cosmos'?'MISSION ÉTOILES':'MISSION FLEURS'):(theme==='cosmos'?'STAR MISSION':'FLOWER MISSION');base[1]=language==='fr'?(theme==='cosmos'?'Compte les étoiles':'Compte les fleurs'):(theme==='cosmos'?'Count the stars':'Count the flowers')}return base}
function refreshInterface(){
  const t=labels(),data=themeData[theme];document.body.dataset.theme=theme;document.documentElement.lang=language;document.querySelector('#homeLabel').textContent=t.home;document.querySelector('#welcomeKicker').textContent=t.welcomeKicker;document.querySelector('#welcomeTitle').textContent=t.welcomeTitle;document.querySelector('#welcomeText').textContent=t.welcomeText;document.querySelector('#parentNote').textContent=t.parent;document.querySelector('#brandIcon').textContent=data.brandIcon;document.querySelector('#brandName').textContent=data.brand;document.querySelector('#welcomeAvatar').textContent=data.avatar;document.querySelector('#themeIcon').textContent=theme==='cosmos'?'🦄':'🪐';document.querySelector('#themeLabel').textContent=theme==='cosmos'?t.themeUnicorn:t.themeCosmos;languageButton.textContent=language==='fr'?'EN':'FR';languageButton.setAttribute('aria-label',language==='fr'?'English':'Français');themeButton.setAttribute('aria-label',theme==='cosmos'?t.themeUnicorn:t.themeCosmos);
  document.querySelectorAll('[data-game]').forEach(button=>{const game=button.dataset.game,c=cardCopy(game);button.querySelector('.game-icon').textContent=data.icons[game];button.querySelector('b').textContent=c[1];button.querySelector('small').textContent=c[2];button.querySelector('em').textContent=game==='story'?t.listen:t.play});const orbit=theme==='cosmos'?['⭐','🚀','🌈','🪐']:['🌸','🦄','🌈','🦋'];document.querySelectorAll('.celebration-orbit i').forEach((item,i)=>item.textContent=orbit[i]);document.querySelector('.reward em').textContent=data.avatar;newRound.textContent=currentGame==='story'?t.reread:['trace','paint'].includes(currentGame)?t.newDrawing:t.again;document.querySelector('#soundButton').setAttribute('aria-label',soundOn?t.soundOn:t.soundOff);
  if(currentGame){const c=cardCopy(currentGame);document.querySelector('#gameKicker').textContent=c[0];document.querySelector('#gameTitle').textContent=c[1]}
}
function openGame(game){currentGame=game;menu.classList.remove('active');play.classList.add('active');const c=cardCopy(game);document.querySelector('#gameKicker').textContent=c[0];document.querySelector('#gameTitle').textContent=c[1];newRound.classList.add('hidden');sound('tap');buildGame();window.scrollTo({top:0,behavior:'smooth'})}
function buildGame(){cancelAnimationFrame(mazeAnimation);mazeAnimation=0;area.innerHTML='';newRound.classList.add('hidden');newRound.textContent=currentGame==='story'?labels().reread:['trace','paint'].includes(currentGame)?labels().newDrawing:labels().again;({shapes:buildShapes,memory:buildMemory,counting:buildCounting,pattern:buildPattern,maze:buildMaze,trace:buildTrace,paint:buildPaint,story:buildStory}[currentGame])()}

function buildShapes(){
  instruction.textContent=labels().instructions.shapes;const colors={circle:'#ff6b9d',square:'#62f2d1',triangle:'#ffd760',star:'#9c7bff'},kinds=Object.keys(colors),order=shuffle(kinds);
  area.innerHTML='<div class="shape-board"><div class="pieces"></div><div class="targets"></div></div>';const pieces=area.querySelector('.pieces'),targets=area.querySelector('.targets');let selected=null,matched=0;
  shuffle(kinds).forEach(kind=>{const b=document.createElement('button');b.className='shape';b.dataset.kind=kind;b.setAttribute('aria-label',kind);b.innerHTML=`<span style="background:${colors[kind]}"></span>`;b.onclick=()=>{sound('tap');pieces.querySelectorAll('.shape').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b};pieces.append(b)});
  order.forEach(kind=>{const b=document.createElement('button');b.className='shape target';b.dataset.kind=kind;b.setAttribute('aria-label',`${language==='fr'?'Maison':'Home'} ${kind}`);b.innerHTML=`<span style="background:${colors[kind]};opacity:.25"></span>`;b.onclick=()=>{if(!selected)return;if(selected.dataset.kind===kind){b.classList.add('matched');selected.classList.add('done');selected=null;sound('match');cheer();if(++matched===kinds.length)setTimeout(celebrate,450)}else{sound('no');cheer(labels().retry);b.animate([{transform:'translateX(-7px)'},{transform:'translateX(7px)'},{transform:'none'}],{duration:300})}};targets.append(b)});
}
function buildMemory(){
  instruction.textContent=labels().instructions.memory;let icons,signature,attempts=0;do{icons=shuffle(themeData[theme].memory).slice(0,6);signature=[...icons].sort().join('')}while(signature===lastMemorySignature&&attempts++<8);lastMemorySignature=signature;let open=[],lock=false,pairs=0;const board=document.createElement('div');board.className='memory-board';area.append(board);
  shuffle([...icons,...icons]).forEach(icon=>{const b=document.createElement('button');b.className='memory-card';b.dataset.icon=icon;b.setAttribute('aria-label',language==='fr'?'Carte cachée':'Hidden card');b.textContent=icon;b.onclick=()=>{if(lock||b.classList.contains('open')||b.classList.contains('matched'))return;b.classList.add('open');open.push(b);sound('flip');if(open.length===2){lock=true;if(open[0].dataset.icon===open[1].dataset.icon){open.forEach(x=>x.classList.add('matched'));open=[];lock=false;sound('match');cheer();if(++pairs===icons.length)setTimeout(celebrate,450)}else setTimeout(()=>{open.forEach(x=>x.classList.remove('open'));open=[];lock=false;sound('no');cheer(labels().almost)},700)}};board.append(b)});
}
function buildCounting(){
  instruction.textContent=theme==='cosmos'?labels().instructions.counting:(language==='fr'?'Combien vois-tu de fleurs?':'How many flowers can you see?');const answer=1+Math.floor(Math.random()*7),cloud=document.createElement('div');cloud.className='count-stars';for(let i=0;i<answer;i++){const s=document.createElement('span');s.textContent=themeData[theme].countIcon;s.style.animationDelay=`${i*.06}s`;cloud.append(s)}
  const choices=new Set([answer]);while(choices.size<3)choices.add(1+Math.floor(Math.random()*7));const buttons=document.createElement('div');buttons.className='answers';shuffle([...choices]).forEach(n=>{const b=document.createElement('button');b.className='answer';b.textContent=n;b.onclick=()=>{if(n===answer){b.classList.add('right');buttons.querySelectorAll('button').forEach(x=>x.disabled=true);sound('match');cheer();setTimeout(celebrate,350)}else{sound('no');cheer(labels().countAgain);b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),400)}};buttons.append(b)});area.append(cloud,buttons);
}
function buildPattern(){
  instruction.textContent=labels().instructions.pattern;const sets=themeData[theme].patterns,base=sets[Math.floor(Math.random()*sets.length)],seq=[];for(let i=0;i<5;i++)seq.push(base[i%base.length]);const answer=base[5%base.length],row=document.createElement('div');row.className='pattern-row';seq.forEach(x=>{const s=document.createElement('span');s.className='pattern-item';s.textContent=x;row.append(s)});const q=document.createElement('span');q.className='pattern-question';q.textContent='?';row.append(q);
  const pool=new Set([answer]);themeData[theme].memory.filter(x=>!base.includes(x)).sort(()=>Math.random()-.5).slice(0,2).forEach(x=>pool.add(x));const buttons=document.createElement('div');buttons.className='pattern-answers';shuffle([...pool]).forEach(x=>{const b=document.createElement('button');b.className='answer';b.textContent=x;b.onclick=()=>{if(x===answer){q.textContent=answer;b.classList.add('right');buttons.querySelectorAll('button').forEach(y=>y.disabled=true);sound('match');cheer();setTimeout(celebrate,350)}else{sound('no');cheer(labels().lookAgain);b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),400)}};buttons.append(b)});area.append(row,buttons);
}

function buildMaze(){
  instruction.textContent=labels().instructions.maze;const cols=10,rows=7,width=900,height=620,margin=34,cellW=(width-margin*2)/cols,cellH=(height-margin*2)/rows;
  const directions=[{dx:0,dy:-1,wall:0,opposite:2},{dx:1,dy:0,wall:1,opposite:3},{dx:0,dy:1,wall:2,opposite:0},{dx:-1,dy:0,wall:3,opposite:1}];let cells,mazeSignature;
  do{
    cells=Array.from({length:rows},()=>Array.from({length:cols},()=>({walls:[true,true,true,true],visited:false})));const stack=[[0,0]];cells[0][0].visited=true;
    while(stack.length){const [x,y]=stack[stack.length-1],choices=shuffle(directions).filter(d=>{const nx=x+d.dx,ny=y+d.dy;return nx>=0&&nx<cols&&ny>=0&&ny<rows&&!cells[ny][nx].visited});if(!choices.length){stack.pop();continue}const d=choices[0],nx=x+d.dx,ny=y+d.dy;cells[y][x].walls[d.wall]=false;cells[ny][nx].walls[d.opposite]=false;cells[ny][nx].visited=true;stack.push([nx,ny])}
    for(let i=0;i<9;i++){const x=Math.floor(Math.random()*cols),y=Math.floor(Math.random()*rows),available=directions.filter(d=>x+d.dx>=0&&x+d.dx<cols&&y+d.dy>=0&&y+d.dy<rows);if(!available.length)continue;const d=available[Math.floor(Math.random()*available.length)],nx=x+d.dx,ny=y+d.dy;cells[y][x].walls[d.wall]=false;cells[ny][nx].walls[d.opposite]=false}
    mazeSignature=cells.flat().map(cell=>cell.walls.map(Number).join('')).join('');
  }while(mazeSignature===lastMazeSignature);
  lastMazeSignature=mazeSignature;
  const candidates=[];for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)if(x+y>=4&&!(x===cols-1&&y===rows-1))candidates.push([x,y]);
  const keyCells=shuffle(candidates).slice(0,3),keys=new Map(keyCells.map(([x,y],i)=>[`${x},${y}`,i])),player={x:0,y:0},trail=[[0,0]];let found=0,completed=false,dragging=false,lastMove=0,lastBump=0,lockedNotice=0;
  area.innerHTML=`<div class="kids-maze"><div class="maze-hud"><span>🔑 <b>0</b>/3 ${labels().mazeKeys}</span><em>${theme==='cosmos'?'👽 🚀':'🦄 🏰'}</em></div><div class="kids-maze-frame"><canvas class="kids-maze-canvas" width="${width}" height="${height}" aria-label="${labels().cards.maze[1]}"></canvas></div><div class="maze-pad" aria-label="${language==='fr'?'Flèches du labyrinthe':'Maze arrows'}"><button data-dx="0" data-dy="-1" aria-label="${language==='fr'?'Monter':'Up'}">▲</button><button data-dx="-1" data-dy="0" aria-label="${language==='fr'?'Gauche':'Left'}">◀</button><button data-dx="0" data-dy="1" aria-label="${language==='fr'?'Descendre':'Down'}">▼</button><button data-dx="1" data-dy="0" aria-label="${language==='fr'?'Droite':'Right'}">▶</button></div></div>`;
  const canvas=area.querySelector('canvas'),ctx=canvas.getContext('2d'),hudCount=area.querySelector('.maze-hud b'),frame=area.querySelector('.kids-maze-frame');
  const cellCentre=(x,y)=>[margin+x*cellW+cellW/2,margin+y*cellH+cellH/2];
  function checkCell(){
    const id=`${player.x},${player.y}`;
    if(keys.has(id)){keys.delete(id);found++;hudCount.textContent=found;frame.classList.remove('key-found');void frame.offsetWidth;frame.classList.add('key-found');sound('key');cheer(labels().mazeOneKey);if(found===3){setTimeout(()=>sound('unlock'),260);instruction.textContent=labels().mazeExit;frame.classList.add('unlocked');setTimeout(()=>{cheer(labels().mazeAllKeys);speak(labels().mazeAllKeys)},320)}else speak(labels().mazeOneKey)}
    if(player.x===cols-1&&player.y===rows-1){if(found<3){const now=performance.now();if(now-lockedNotice>900){lockedNotice=now;sound('no');cheer(labels().mazeLocked)}}else if(!completed){completed=true;dragging=false;sound('unlock');setTimeout(()=>celebrate(()=>{if(currentGame==='maze'&&play.classList.contains('active'))buildGame()}),420)}}
  }
  function move(dx,dy){
    if(completed)return false;const dir=dx===1?1:dx===-1?3:dy===1?2:0;if(cells[player.y][player.x].walls[dir]){const now=performance.now();if(now-lastBump>550){lastBump=now;sound('no')}return false}player.x+=dx;player.y+=dy;trail.push([player.x,player.y]);if(trail.length>35)trail.shift();sound('step');checkCell();return true
  }
  function pointerCell(event){const rect=canvas.getBoundingClientRect(),px=(event.clientX-rect.left)*width/rect.width,py=(event.clientY-rect.top)*height/rect.height;return{x:Math.max(0,Math.min(cols-1,Math.floor((px-margin)/cellW))),y:Math.max(0,Math.min(rows-1,Math.floor((py-margin)/cellH)))}}
  function moveToward(event){if(!dragging||completed)return;event.preventDefault();const now=performance.now();if(now-lastMove<58)return;const target=pointerCell(event),dx=target.x-player.x,dy=target.y-player.y;if(!dx&&!dy)return;lastMove=now;const horizontal=Math.abs(dx)>=Math.abs(dy);if(horizontal){if(dx&&!move(Math.sign(dx),0)&&dy)move(0,Math.sign(dy))}else if(dy&&!move(0,Math.sign(dy))&&dx)move(Math.sign(dx),0)}
  canvas.addEventListener('pointerdown',event=>{dragging=true;canvas.setPointerCapture?.(event.pointerId);moveToward(event)});canvas.addEventListener('pointermove',moveToward);canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);
  area.querySelectorAll('.maze-pad button').forEach(button=>button.onclick=()=>move(Number(button.dataset.dx),Number(button.dataset.dy)));
  function draw(now){
    if(!canvas.isConnected||currentGame!=='maze')return;ctx.clearRect(0,0,width,height);const unicorn=theme==='unicorn',background=ctx.createLinearGradient(0,0,width,height);background.addColorStop(0,unicorn?'#41245f':'#101c4b');background.addColorStop(.55,unicorn?'#713c83':'#183d66');background.addColorStop(1,unicorn?'#a4578e':'#294978');ctx.fillStyle=background;ctx.fillRect(0,0,width,height);
    ctx.globalAlpha=.16;ctx.fillStyle=unicorn?'#ffe1f2':'#79f8e0';for(let i=0;i<18;i++){const x=(i*173+37)%width,y=(i*97+41)%height;ctx.beginPath();ctx.arc(x,y,2+(i%3),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
    ctx.fillStyle=unicorn?'#ffffff12':'#0af7dc0b';for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){ctx.fillRect(margin+x*cellW+5,margin+y*cellH+5,cellW-10,cellH-10)}
    ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=unicorn?'#ffd0ef':'#70ffe2';ctx.shadowColor=unicorn?'#ff75c8':'#4bf5d5';ctx.shadowBlur=9;ctx.lineWidth=8;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const left=margin+x*cellW,top=margin+y*cellH,right=left+cellW,bottom=top+cellH,w=cells[y][x].walls;ctx.beginPath();if(w[0]){ctx.moveTo(left,top);ctx.lineTo(right,top)}if(w[1]){ctx.moveTo(right,top);ctx.lineTo(right,bottom)}if(w[2]){ctx.moveTo(right,bottom);ctx.lineTo(left,bottom)}if(w[3]){ctx.moveTo(left,bottom);ctx.lineTo(left,top)}ctx.stroke()}ctx.shadowBlur=0;
    ctx.strokeStyle=unicorn?'#ffe8f788':'#b7fff088';ctx.lineWidth=6;ctx.beginPath();trail.forEach(([x,y],i)=>{const [cx,cy]=cellCentre(x,y);i?ctx.lineTo(cx,cy):ctx.moveTo(cx,cy)});ctx.stroke();
    const [exitX,exitY]=cellCentre(cols-1,rows-1);ctx.save();ctx.translate(exitX,exitY);ctx.fillStyle=found===3?(unicorn?'#ffe568':'#a4ff69'):'#17233c';ctx.shadowColor=found===3?(unicorn?'#ffe568':'#a4ff69'):'#000';ctx.shadowBlur=found===3?20:5;ctx.beginPath();ctx.arc(0,0,Math.min(cellW,cellH)*.32,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.font=`${Math.min(cellW,cellH)*.48}px "Segoe UI Emoji"`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(found===3?(unicorn?'🏰':'🛸'):'🔒',0,2);ctx.restore();
    ctx.font=`${Math.min(cellW,cellH)*.48}px "Segoe UI Emoji"`;ctx.textAlign='center';ctx.textBaseline='middle';keys.forEach((_,id)=>{const [x,y]=id.split(',').map(Number),[cx,cy]=cellCentre(x,y),bob=Math.sin(now/280+x+y)*5;ctx.save();ctx.translate(cx,cy+bob);ctx.rotate(Math.sin(now/410+x)*.12);ctx.fillText(unicorn?'🗝️':'🔑',0,0);ctx.restore()});
    const [px,py]=cellCentre(player.x,player.y),bounce=Math.sin(now/150)*2;ctx.save();ctx.translate(px,py+bounce);ctx.shadowColor=unicorn?'#ffb8e6':'#74ffe4';ctx.shadowBlur=18;ctx.fillStyle='#ffffffdd';ctx.beginPath();ctx.arc(0,0,Math.min(cellW,cellH)*.3,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.font=`${Math.min(cellW,cellH)*.52}px "Segoe UI Emoji"`;ctx.fillText(themeData[theme].avatar,0,2);ctx.restore();mazeAnimation=requestAnimationFrame(draw)
  }
  mazeAnimation=requestAnimationFrame(draw);
}

const drawingTemplateNames={
  fr:{star:'Étoile',flower:'Fleur',rocket:'Fusée',cat:'Petit chat',butterfly:'Papillon',unicorn:'Licorne'},
  en:{star:'Star',flower:'Flower',rocket:'Rocket',cat:'Kitten',butterfly:'Butterfly',unicorn:'Unicorn'}
};
const drawingTemplateIcons={star:'⭐',flower:'🌸',rocket:'🚀',cat:'🐱',butterfly:'🦋',unicorn:'🦄'};
const drawingColours=[
  ['#ef476f','🔴'],['#ff8c42','🟠'],['#ffd93d','🟡'],['#45c96b','🟢'],['#35a7ff','🔵'],
  ['#7655e8','🟣'],['#f56fbd','🌸'],['#8b5e3c','🟤'],['#17233c','⚫']
];

function prepareTemplatePen(ctx){
  ctx.strokeStyle=theme==='cosmos'?'#9b86d8':'#cc82b8';ctx.lineWidth=5;ctx.lineCap='round';ctx.lineJoin='round';ctx.setLineDash([14,11]);
}
function drawStarTemplate(ctx){
  const cx=450,cy=305,outer=190,inner=82;ctx.beginPath();for(let i=0;i<10;i++){const angle=-Math.PI/2+i*Math.PI/5,r=i%2?inner:outer,x=cx+Math.cos(angle)*r,y=cy+Math.sin(angle)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke();
  ctx.beginPath();ctx.arc(390,292,8,0,Math.PI*2);ctx.moveTo(518,292);ctx.arc(510,292,8,0,Math.PI*2);ctx.moveTo(390,347);ctx.quadraticCurveTo(450,390,510,347);ctx.stroke();
}
function drawFlowerTemplate(ctx){
  const cx=450,cy=260;for(let i=0;i<8;i++){const a=i*Math.PI/4,x=cx+Math.cos(a)*105,y=cy+Math.sin(a)*105;ctx.beginPath();ctx.ellipse(x,y,58,86,a+Math.PI/2,0,Math.PI*2);ctx.stroke()}ctx.beginPath();ctx.arc(cx,cy,72,0,Math.PI*2);ctx.moveTo(cx,332);ctx.bezierCurveTo(430,410,470,475,446,550);ctx.moveTo(448,455);ctx.bezierCurveTo(375,420,350,458,406,490);ctx.moveTo(452,474);ctx.bezierCurveTo(530,425,558,470,494,507);ctx.stroke();
}
function drawRocketTemplate(ctx){
  ctx.beginPath();ctx.moveTo(450,80);ctx.bezierCurveTo(335,165,330,335,365,445);ctx.lineTo(535,445);ctx.bezierCurveTo(570,335,565,165,450,80);ctx.closePath();ctx.stroke();ctx.beginPath();ctx.arc(450,255,58,0,Math.PI*2);ctx.moveTo(365,350);ctx.lineTo(290,455);ctx.lineTo(375,430);ctx.moveTo(535,350);ctx.lineTo(610,455);ctx.lineTo(525,430);ctx.moveTo(410,445);ctx.quadraticCurveTo(385,520,450,565);ctx.quadraticCurveTo(515,520,490,445);ctx.stroke();
}
function drawCatTemplate(ctx){
  ctx.beginPath();ctx.moveTo(330,225);ctx.lineTo(310,100);ctx.lineTo(405,160);ctx.quadraticCurveTo(450,145,495,160);ctx.lineTo(590,100);ctx.lineTo(570,225);ctx.bezierCurveTo(615,390,535,480,450,480);ctx.bezierCurveTo(365,480,285,390,330,225);ctx.closePath();ctx.stroke();ctx.beginPath();ctx.ellipse(398,285,12,20,0,0,Math.PI*2);ctx.moveTo(514,285);ctx.ellipse(502,285,12,20,0,0,Math.PI*2);ctx.moveTo(430,345);ctx.lineTo(450,360);ctx.lineTo(470,345);ctx.moveTo(450,360);ctx.quadraticCurveTo(425,392,400,370);ctx.moveTo(450,360);ctx.quadraticCurveTo(475,392,500,370);ctx.moveTo(370,345);ctx.lineTo(270,320);ctx.moveTo(370,370);ctx.lineTo(265,380);ctx.moveTo(530,345);ctx.lineTo(630,320);ctx.moveTo(530,370);ctx.lineTo(635,380);ctx.stroke();
}
function drawButterflyTemplate(ctx){
  ctx.beginPath();ctx.moveTo(435,205);ctx.bezierCurveTo(330,70,150,130,230,300);ctx.bezierCurveTo(125,405,265,535,420,395);ctx.moveTo(465,205);ctx.bezierCurveTo(570,70,750,130,670,300);ctx.bezierCurveTo(775,405,635,535,480,395);ctx.stroke();ctx.beginPath();ctx.ellipse(450,325,34,150,0,0,Math.PI*2);ctx.moveTo(435,180);ctx.quadraticCurveTo(375,115,350,95);ctx.moveTo(465,180);ctx.quadraticCurveTo(525,115,550,95);ctx.stroke();
}
function drawUnicornTemplate(ctx){
  ctx.beginPath();ctx.moveTo(335,190);ctx.quadraticCurveTo(260,250,285,390);ctx.quadraticCurveTo(315,510,470,485);ctx.quadraticCurveTo(620,460,610,315);ctx.quadraticCurveTo(605,210,520,175);ctx.quadraticCurveTo(430,140,335,190);ctx.closePath();ctx.stroke();ctx.beginPath();ctx.moveTo(425,155);ctx.lineTo(480,42);ctx.lineTo(505,172);ctx.moveTo(330,205);ctx.quadraticCurveTo(245,125,250,255);ctx.moveTo(540,185);ctx.quadraticCurveTo(650,105,615,300);ctx.moveTo(375,310);ctx.ellipse(365,310,10,19,0,0,Math.PI*2);ctx.moveTo(545,310);ctx.ellipse(535,310,10,19,0,0,Math.PI*2);ctx.moveTo(410,385);ctx.quadraticCurveTo(455,425,500,385);ctx.moveTo(510,205);ctx.quadraticCurveTo(585,230,610,330);ctx.stroke();
}
function drawGuide(ctx,key){
  ctx.save();prepareTemplatePen(ctx);({star:drawStarTemplate,flower:drawFlowerTemplate,rocket:drawRocketTemplate,cat:drawCatTemplate,butterfly:drawButterflyTemplate,unicorn:drawUnicornTemplate}[key])(ctx);ctx.restore();
}
function buildTrace(){buildDrawingStudio(true)}
function buildPaint(){buildDrawingStudio(false)}
function buildDrawingStudio(withGuide){
  const t=labels();instruction.textContent=t.instructions[withGuide?'trace':'paint'];area.innerHTML='';
  const studio=document.createElement('div');studio.className=`art-studio ${withGuide?'guided-drawing':'free-paint'}`;
  if(withGuide){const picker=document.createElement('section');picker.className='template-picker';const title=document.createElement('b');title.textContent=t.choosePicture;const buttons=document.createElement('div');buttons.className='template-buttons';Object.keys(drawingTemplateIcons).forEach((key,index)=>{const button=document.createElement('button');button.className='template-choice';button.dataset.template=key;button.innerHTML=`<span>${drawingTemplateIcons[key]}</span><small>${drawingTemplateNames[language][key]}</small>`;button.setAttribute('aria-pressed',index===0?'true':'false');if(index===0)button.classList.add('active');buttons.append(button)});picker.append(title,buttons);studio.append(picker)}
  const toolbar=document.createElement('section');toolbar.className='paint-tools';toolbar.innerHTML=`<div class="tool-group colour-tools"><b>${t.colors}</b><div class="colour-buttons"></div></div><div class="tool-group brush-tools"><b>🖌️</b><div class="brush-buttons"></div></div><div class="tool-group action-tools"><b>✨</b><div><button class="tool-action eraser" type="button">🧽 <span>${t.eraser}</span></button><button class="tool-action undo" type="button">↩️ <span>${t.undo}</span></button><button class="tool-action clear" type="button">🗑️ <span>${t.clear}</span></button><button class="tool-action save" type="button">💾 <span>${t.saveDrawing}</span></button></div></div>`;
  const colourButtons=toolbar.querySelector('.colour-buttons');drawingColours.forEach(([colour,icon],index)=>{const button=document.createElement('button');button.className='colour-choice';button.type='button';button.style.setProperty('--swatch',colour);button.textContent=icon;button.setAttribute('aria-label',`${t.colors} ${index+1}`);button.setAttribute('aria-pressed',index===4?'true':'false');if(index===4)button.classList.add('active');button.dataset.colour=colour;colourButtons.append(button)});
  [[8,t.smallBrush],[18,t.mediumBrush],[34,t.largeBrush]].forEach(([size,name],index)=>{const button=document.createElement('button');button.className='brush-choice';button.type='button';button.dataset.size=size;button.innerHTML=`<i style="--brush:${size}px"></i><span>${name}</span>`;button.setAttribute('aria-pressed',index===1?'true':'false');if(index===1)button.classList.add('active');toolbar.querySelector('.brush-buttons').append(button)});
  const canvasShell=document.createElement('div');canvasShell.className='canvas-shell';const canvas=document.createElement('canvas');canvas.className='drawing-canvas';canvas.width=900;canvas.height=620;canvas.setAttribute('aria-label',withGuide?t.instructions.trace:t.instructions.paint);canvasShell.append(canvas);
  const finish=document.createElement('button');finish.className='finish-art';finish.type='button';finish.textContent=`🌟 ${t.finishedDrawing}`;const status=document.createElement('p');status.className='art-status';status.setAttribute('aria-live','polite');studio.append(toolbar,canvasShell,finish,status);area.append(studio);
  const ctx=canvas.getContext('2d'),paper='#fffdf8';let template='star',colour='#35a7ff',size=18,erasing=false,drawing=false,currentStroke=null,strokes=[],clearReady=false,clearTimer;
  const drawDot=(stroke,point)=>{ctx.save();ctx.fillStyle=stroke.colour;ctx.beginPath();ctx.arc(point.x,point.y,stroke.size/2,0,Math.PI*2);ctx.fill();ctx.restore()};
  const drawWholeStroke=stroke=>{if(stroke.points.length===1){drawDot(stroke,stroke.points[0]);return}ctx.save();ctx.strokeStyle=stroke.colour;ctx.lineWidth=stroke.size;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(stroke.points[0].x,stroke.points[0].y);stroke.points.slice(1).forEach(point=>ctx.lineTo(point.x,point.y));ctx.stroke();ctx.restore()};
  const render=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle=paper;ctx.fillRect(0,0,canvas.width,canvas.height);if(withGuide)drawGuide(ctx,template);strokes.forEach(stroke=>drawWholeStroke(stroke))};
  const pointFrom=event=>{const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height}};
  const begin=event=>{event.preventDefault();drawing=true;canvas.setPointerCapture?.(event.pointerId);const point=pointFrom(event);currentStroke={colour:erasing?paper:colour,size:erasing?48:size,points:[point]};strokes.push(currentStroke);drawDot(currentStroke,point);sound('tap')};
  const move=event=>{if(!drawing||!currentStroke)return;event.preventDefault();const point=pointFrom(event),previous=currentStroke.points[currentStroke.points.length-1];currentStroke.points.push(point);ctx.save();ctx.strokeStyle=currentStroke.colour;ctx.lineWidth=currentStroke.size;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(previous.x,previous.y);ctx.lineTo(point.x,point.y);ctx.stroke();ctx.restore()};
  const end=event=>{if(!drawing)return;drawing=false;currentStroke=null;try{canvas.releasePointerCapture?.(event.pointerId)}catch{}};
  canvas.addEventListener('pointerdown',begin);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('pointerleave',event=>{if(event.pointerType==='mouse')end(event)});
  studio.querySelectorAll('.colour-choice').forEach(button=>button.onclick=()=>{erasing=false;colour=button.dataset.colour;studio.querySelectorAll('.colour-choice,.eraser').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});button.classList.add('active');button.setAttribute('aria-pressed','true');sound('tap')});
  studio.querySelectorAll('.brush-choice').forEach(button=>button.onclick=()=>{size=Number(button.dataset.size);studio.querySelectorAll('.brush-choice').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});button.classList.add('active');button.setAttribute('aria-pressed','true');sound('tap')});
  const eraser=studio.querySelector('.eraser');eraser.setAttribute('aria-pressed','false');eraser.onclick=()=>{erasing=true;studio.querySelectorAll('.colour-choice').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});eraser.classList.add('active');eraser.setAttribute('aria-pressed','true');sound('tap')};
  studio.querySelector('.undo').onclick=()=>{strokes.pop();render();sound('flip')};
  const clear=studio.querySelector('.clear');clear.onclick=()=>{if(!clearReady){clearReady=true;clear.classList.add('confirm');clear.querySelector('span').textContent=t.clearAgain;clearTimeout(clearTimer);clearTimer=setTimeout(()=>{clearReady=false;clear.classList.remove('confirm');clear.querySelector('span').textContent=t.clear},2200);sound('no');return}clearReady=false;clearTimeout(clearTimer);clear.classList.remove('confirm');clear.querySelector('span').textContent=t.clear;strokes=[];render();sound('flip')};
  studio.querySelector('.save').onclick=()=>{const link=document.createElement('a');link.href=canvas.toDataURL('image/png');link.download=language==='fr'?'mon-dessin-cosmo-kids.png':'my-cosmo-kids-picture.png';document.body.append(link);link.click();link.remove();status.textContent=t.drawingSaved;cheer(t.drawingSaved);sound('match')};
  finish.onclick=()=>{finish.disabled=true;finish.classList.add('done');status.textContent=t.drawingSaved;celebrate()};
  if(withGuide)studio.querySelectorAll('.template-choice').forEach(button=>button.onclick=()=>{template=button.dataset.template;strokes=[];studio.querySelectorAll('.template-choice').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});button.classList.add('active');button.setAttribute('aria-pressed','true');render();sound('tap')});
  render();
}

function buildStory(){showStoryLibrary()}
function showStoryLibrary(){
  storyVoiceToken++;stopAmbience();if('speechSynthesis'in window)speechSynthesis.cancel();currentStoryKey='';storyStep=0;storyRewarded=false;instruction.textContent=labels().chooseStory;newRound.classList.add('hidden');area.innerHTML='';const library=document.createElement('div');library.className='story-library';const heading=document.createElement('div');heading.className='story-library-heading';heading.innerHTML=`<span>📚</span><h3>${labels().chooseStory}</h3>`;const grid=document.createElement('div');grid.className='story-library-grid';const choices=[{key:'eva',title:labels().evaStory,description:`${labels().evaStoryLength}<br>${labels().evaDesc}`,image:'assets/cosmo-kids/bedtime-princess-eva-cover-v1.png',icon:'👸'},{key:'theme',title:theme==='cosmos'?labels().cosmosStory:labels().unicornStory,description:labels().shortStory,image:themeData[theme].storyImage,icon:theme==='cosmos'?'🌙':'🦄'},{key:'panda',title:labels().pandaTitle,description:`${labels().longStory}<br>${labels().pandaDesc}`,image:'assets/cosmo-kids/bedtime-panda-cheetah-v1.png',icon:'🐼'},{key:'ocean',title:labels().oceanTitle,description:`${labels().mediumStory}<br>${labels().oceanDesc}`,image:'assets/cosmo-kids/bedtime-ocean-v1.png',icon:'🐢'}];choices.forEach(choice=>{const button=document.createElement('button');button.className='story-pick';button.innerHTML=`<img src="${choice.image}" alt=""><span><em>${choice.icon}</em><b></b><small></small></span>`;button.querySelector('b').textContent=choice.title;button.querySelector('small').innerHTML=choice.description;button.onclick=()=>{sound('tap');startStory(choice.key)};grid.append(button)});library.append(heading,grid);area.append(library)
}
function activeStory(){return currentStoryKey==='theme'?stories[theme]:stories[currentStoryKey]}
function activeStoryArt(){
  const key=currentStoryKey==='theme'?theme:currentStoryKey,art=storyPageArt[key],index=Math.min(storyStep,art.columns*art.rows-1),column=index%art.columns,row=Math.floor(index/art.columns);
  return{...art,x:art.columns===1?0:column/(art.columns-1)*100,y:art.rows===1?0:row/(art.rows-1)*100}
}
function storyAmbienceKind(){return currentStoryKey==='panda'?'forest':['ocean','eva'].includes(currentStoryKey)?'ocean':'dream'}
function storyEndingIcon(){return currentStoryKey==='eva'?'👸':currentStoryKey==='panda'?'🐼':currentStoryKey==='ocean'?'🐢':theme==='cosmos'?'🌙':'🦄'}
function storyEndingMarks(){return currentStoryKey==='eva'?'🦄 💤 🌊':currentStoryKey==='panda'?'🐾 💤 🎋':currentStoryKey==='ocean'?'🫧 💤 🐋':theme==='cosmos'?'✨ 💤 🪐':'🌙 💤 🌈'}
function startStory(key){currentStoryKey=key;storyStep=0;storyRewarded=false;newRound.classList.add('hidden');startAmbience(storyAmbienceKind());renderStory()}
function rewardStory(ending){
  if(storyRewarded)return;storyRewarded=true;stars++;starCount.textContent=stars;starCount.parentElement.classList.remove('score-pop');void starCount.offsetWidth;starCount.parentElement.classList.add('score-pop');tone(392,0,.35,.035,'sine',523);tone(523,.28,.5,.03,'sine',659);setTimeout(()=>speak(ending,true),250);newRound.textContent=labels().reread;newRound.classList.remove('hidden');
}
function renderStory(){
  clearTimeout(renderStory.advance);clearTimeout(renderStory.voice);const renderToken=++storyVoiceToken;instruction.textContent=labels().instructions.story;const story=activeStory(),pages=story[language],art=activeStoryArt();area.innerHTML='';const book=document.createElement('div');book.className='story-book';const pictureWrap=document.createElement('div');pictureWrap.className='story-picture-wrap';const picture=document.createElement('div');picture.className='story-picture';picture.style.backgroundImage=`url("${art.src}")`;picture.style.backgroundSize=`${art.columns*100}% ${art.rows*100}%`;picture.style.backgroundPosition=`${art.x}% ${art.y}%`;picture.setAttribute('role','img');let pictureLabel=currentStoryKey==='panda'?(language==='fr'?'Une nouvelle scène de Bao le panda et Tiko le guépard':'A new scene with Bao the panda and Tiko the cheetah'):theme==='cosmos'?(language==='fr'?'Une nouvelle scène de Lumi et Bibi sur la petite lune':'A new scene with Lumi and Bibi on the little moon'):(language==='fr'?'Une nouvelle scène de Plume et Lila au pays des nuages':'A new scene with Plume and Lila in the cloud kingdom');if(currentStoryKey==='ocean')pictureLabel=language==='fr'?'Une nouvelle scène de Mila la tortue et Lune la baleine':'A new scene with Mila the turtle and Lune the whale';picture.setAttribute('aria-label',pictureLabel);const progress=document.createElement('div');progress.className='story-progress';progress.textContent=pages.map((_,i)=>i<storyStep?'●':i===storyStep?'◉':'○').join(' ');pictureWrap.append(picture,progress);const page=document.createElement('div');page.className='story-page';book.append(pictureWrap,page);area.append(book);
  if(currentStoryKey==='eva')picture.setAttribute('aria-label',language==='fr'?'Une nouvelle scène des vacances de la princesse Eva et de la princesse Marie':'A new vacation scene with Princess Eva and Princess Marie');
  if(storyStep>=pages.length){const ending=story.endings[language],endIcon=storyEndingIcon(),endMarks=storyEndingMarks();progress.textContent=pages.map(()=>'●').join(' ');page.innerHTML=`<div class="story-ending"><span>${endIcon}</span><h3>${labels().goodNight}</h3><p></p><em class="story-rest">${endMarks}</em><button class="story-another">${labels().anotherStory}</button></div>`;page.querySelector('p').textContent=ending;page.querySelector('.story-another').onclick=showStoryLibrary;instruction.textContent=labels().goodNight;rewardStory(ending);return}
  const chapter=pages[storyStep],listen=document.createElement('button');listen.className='story-listen';listen.type='button';listen.textContent=labels().read;listen.onclick=()=>speak(chapter.text,true);const text=document.createElement('p');text.className='story-text';text.textContent=chapter.text;const question=document.createElement('div');question.className='story-question';const prompt=document.createElement('b');prompt.textContent=chapter.question;const choices=document.createElement('div');choices.className='story-choices';chapter.choices.forEach(([choice,response])=>{const button=document.createElement('button');button.className='story-choice';button.textContent=choice;button.onclick=()=>{choices.querySelectorAll('button').forEach(x=>x.disabled=true);button.classList.add('selected');sound('match');const answer=document.createElement('p');answer.className='story-response';answer.setAttribute('aria-live','polite');answer.textContent=response;const cue=document.createElement('p');cue.className='story-turn-cue waiting';cue.textContent=labels().listening;question.append(answer,cue);let pageReady=false;const advance=event=>{if(!pageReady||renderToken!==storyVoiceToken)return;if(event?.target?.closest?.('.story-listen'))return;pageReady=false;book.classList.remove('ready-to-turn');sound('flip');book.classList.add('page-turning');renderStory.advance=setTimeout(()=>{if(renderToken!==storyVoiceToken)return;storyStep++;renderStory()},420)};book.addEventListener('click',advance);book.addEventListener('keydown',event=>{if(pageReady&&(event.key==='Enter'||event.key===' ')){event.preventDefault();advance(event)}});const ready=()=>{if(renderToken!==storyVoiceToken)return;pageReady=true;choices.classList.add('answered');listen.disabled=true;cue.textContent=labels().turnPage;cue.classList.remove('waiting');cue.classList.add('ready');book.classList.add('ready-to-turn');book.tabIndex=0;book.setAttribute('aria-label',labels().turnPage)};speak(response,true,ready)};choices.append(button)});question.append(prompt,choices);page.append(listen,text,question);renderStory.voice=setTimeout(()=>speak(chapter.text,true),350);
}

document.querySelectorAll('[data-game]').forEach(button=>button.addEventListener('click',()=>openGame(button.dataset.game)));
document.querySelector('#backButton').onclick=()=>{sound('tap');clearTimeout(renderStory.advance);clearTimeout(renderStory.voice);if('speechSynthesis'in window)speechSynthesis.cancel();if(currentGame==='story'&&currentStoryKey){showStoryLibrary();return}stopAmbience();play.classList.remove('active');menu.classList.add('active');area.innerHTML='';currentGame='';refreshInterface()};
document.querySelector('#soundButton').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'🔊':'🔇';e.currentTarget.setAttribute('aria-label',soundOn?labels().soundOn:labels().soundOff);if(soundOn){sound('match');cheer(labels().soundsOn);if(currentGame==='story'&&currentStoryKey)startAmbience(storyAmbienceKind())}else{stopAmbience();if('speechSynthesis'in window)speechSynthesis.cancel()}};
themeButton.onclick=()=>{theme=theme==='cosmos'?'unicorn':'cosmos';sound('tap');refreshInterface();if(play.classList.contains('active'))buildGame()};
languageButton.onclick=()=>{language=language==='fr'?'en':'fr';sound('tap');refreshInterface();if(play.classList.contains('active')){if(currentGame==='story'){if(currentStoryKey)renderStory();else showStoryLibrary()}else buildGame()}};
newRound.onclick=()=>{sound('tap');if(currentGame==='story'&&currentStoryKey)startStory(currentStoryKey);else buildGame()};
refreshInterface();
