const menu=document.querySelector('#menu'),play=document.querySelector('#play'),area=document.querySelector('#gameArea');
const instruction=document.querySelector('#instruction'),newRound=document.querySelector('#newRound');
const starCount=document.querySelector('#starCount'),celebration=document.querySelector('#celebration');
const encouragement=document.querySelector('#encouragement'),rewardIcon=document.querySelector('#rewardIcon');
const rewardTitle=document.querySelector('#rewardTitle'),rewardText=document.querySelector('#rewardText');
const themeButton=document.querySelector('#themeButton'),languageButton=document.querySelector('#languageButton');
let stars=0,currentGame='',soundOn=true,audioContext,praiseIndex=0,theme='cosmos',language='fr',lastMemorySignature='',storyStep=0,storyRewarded=false,storyVoiceToken=0,currentStoryKey='',ambience=null;

const copy={
  fr:{home:'Accueil',welcomeKicker:'MISSION DES PETITS EXPLORATEURS',welcomeTitle:'Choisis un jeu!',welcomeText:'Sans pub. Sans achat. Joue autant que tu veux.',parent:'💜 Conçu pour les petites mains — aucun lien caché dans les jeux.',play:'Jouer',listen:'Écouter',again:'Encore! 🔄',themeCosmos:'Mode Cosmos',themeUnicorn:'Mode Licorne',soundOn:'Désactiver les sons',soundOff:'Activer les sons',
    cards:{shapes:['MISSION FORMES','Les formes','Trouve les paires'],memory:['MISSION MÉMOIRE','Mémoire spatiale','De nouvelles cartes chaque fois'],counting:['MISSION ÉTOILES','Compte les étoiles','Choisis le bon nombre'],pattern:['MISSION LOGIQUE','La suite magique','Quelle image vient après?'],story:['MISSION DODO','L’histoire du dodo','Écoute, choisis et continue l’aventure']},
    instructions:{shapes:'Touche une forme, puis sa maison pareille!',memory:'Trouve les deux images pareilles!',counting:'Combien vois-tu d’étoiles?',pattern:'Quelle image vient après?',story:'Écoute l’histoire et choisis pour continuer.'},
    retry:'Essaie encore!',almost:'Presque! Essaie encore!',countAgain:'Compte encore une fois!',lookAgain:'Regarde bien la suite!',soundsOn:'Les sons sont activés!',read:'🔊 Écouter',goodNight:'Bonne nuit, petit rêveur!',reread:'Relire l’histoire 🌙',chooseStory:'Choisis ton histoire du soir',shortStory:'Petite histoire douce · 4 pages',mediumStory:'Aventure sous-marine · 6 pages',longStory:'Grande aventure calme · 7 pages',pandaTitle:'Bao et Tiko, la course de l’amitié',pandaDesc:'Un panda patient et un guépard rapide découvrent qu’avancer ensemble est encore mieux.',oceanTitle:'Mila et la baleine des rêves',oceanDesc:'Une petite tortue rassemble les sons les plus doux de l’océan pour créer une berceuse.',cosmosStory:'Lumi et l’étoile endormie',unicornStory:'Plume au château des nuages',turnPage:'Touche la page pour continuer 👆',listening:'Écoute la réponse… 🎵',anotherStory:'Choisir une autre histoire 📚'},
  en:{home:'Home',welcomeKicker:'LITTLE EXPLORERS MISSION',welcomeTitle:'Choose a game!',welcomeText:'No ads. No purchases. Play as much as you like.',parent:'💜 Made for little hands — no hidden links inside the games.',play:'Play',listen:'Listen',again:'Again! 🔄',themeCosmos:'Cosmos Mode',themeUnicorn:'Unicorn Mode',soundOn:'Turn sounds off',soundOff:'Turn sounds on',
    cards:{shapes:['SHAPES MISSION','Shapes','Match every shape'],memory:['MEMORY MISSION','Magic Memory','New pictures every time'],counting:['COUNTING MISSION','Count the stars','Choose the right number'],pattern:['LOGIC MISSION','Magic Pattern','Which picture comes next?'],story:['BEDTIME MISSION','The bedtime story','Listen, choose and continue the adventure']},
    instructions:{shapes:'Touch a shape, then its matching home!',memory:'Find the two matching pictures!',counting:'How many stars can you see?',pattern:'Which picture comes next?',story:'Listen to the story and choose what happens next.'},
    retry:'Try again!',almost:'Almost! Try again!',countAgain:'Count one more time!',lookAgain:'Look carefully at the pattern!',soundsOn:'The sounds are on!',read:'🔊 Listen',goodNight:'Good night, little dreamer!',reread:'Read the story again 🌙',chooseStory:'Choose your bedtime story',shortStory:'A gentle short story · 4 pages',mediumStory:'An underwater adventure · 6 pages',longStory:'A calm big adventure · 7 pages',pandaTitle:'Bao and Tiko’s Friendship Race',pandaDesc:'A patient panda and a speedy cheetah discover that moving together is even better.',oceanTitle:'Mila and the Dream Whale',oceanDesc:'A little turtle gathers the ocean’s softest sounds to make a bedtime song.',cosmosStory:'Lumi and the Sleepy Star',unicornStory:'Plume at the Cloud Castle',turnPage:'Touch the page to continue 👆',listening:'Listen to the answer… 🎵',anotherStory:'Choose another story 📚'}
};
const themeData={
  cosmos:{brand:'Cosmo Kids',avatar:'👽',brandIcon:'🪐',icons:{shapes:'🔷',memory:'🚀',counting:'⭐',pattern:'🛸',story:'🌙'},countIcon:'⭐',memory:['🚀','🪐','👽','🌙','🛸','⭐','☄️','🌎','☀️','🔭','🛰️','🌌','🌠','🤖','🌈','💫'],patterns:[['🚀','🌙'],['👽','🛸'],['⭐','🪐'],['🌎','🌙','☀️'],['🤖','🚀','⭐']],storyImage:'assets/cosmo-kids/bedtime-cosmos-v1.png'},
  unicorn:{brand:'Licorne Kids',avatar:'🦄',brandIcon:'🌈',icons:{shapes:'💎',memory:'🦄',counting:'🌸',pattern:'🦋',story:'🌙'},countIcon:'🌸',memory:['🦄','🌈','🌸','🦋','👑','💖','✨','🌙','☁️','🍓','🧁','🎀','💎','🧚','🌺','⭐'],patterns:[['🦄','🌈'],['🌸','🦋'],['💖','✨'],['👑','💎','🎀'],['☁️','🌙','⭐']],storyImage:'assets/cosmo-kids/bedtime-unicorn-v1.png'}
};
const praiseSets={
  fr:[['Bravo!','Tu as réussi!','🌟'],['Super!','Quel beau travail!','🚀'],['Youpi!','Tu es fantastique!','🌈'],['Hourra!','Mission accomplie!','🪐'],['Yay!','Encore une victoire!','🎉'],['Magnifique!','Continue comme ça!','💫']],
  en:[['Bravo!','You did it!','🌟'],['Amazing!','Wonderful work!','🚀'],['Yay!','You are fantastic!','🌈'],['Hooray!','Mission complete!','🪐'],['Woohoo!','Another victory!','🎉'],['Wonderful!','Keep going!','💫']]
};
const encouragementSets={fr:['Oui, c’est ça!','Super choix!','Tu l’as trouvé!','Bravo, exploratrice!','Quelle championne!'],en:['Yes, that’s it!','Great choice!','You found it!','Well done, explorer!','You are a champion!']};
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const stories={
  cosmos:{
    fr:[
      {text:'La nuit est douce sur la petite lune. Lumi et Bibi suivent un sentier de lumière vers leur maison-fusée.',question:'Qui brille au-dessus du chemin?',choices:[['La petite étoile ⭐','La petite étoile bâille et éclaire doucement leurs pas.'],['La lune souriante 🌙','La lune sourit et dépose une lumière calme sur le chemin.']]},
      {text:'Dans le jardin lunaire, les fleurs ferment lentement leurs pétales. Bibi roule tout doucement pour ne pas les réveiller.',question:'De quelle couleur est la fleur la plus endormie?',choices:[['Violette 💜','La fleur violette fait un tout petit bâillement.'],['Bleue 💙','La fleur bleue se blottit sous une feuille.']]},
      {text:'Un petit nuage a peur d’être seul. Lumi lui tend la main et Bibi allume une veilleuse ronde.',question:'Que peuvent-ils dire au petit nuage?',choices:[['Bonne nuit 🌙','Le nuage se sent rassuré et ferme les yeux.'],['Nous sommes là 💛','Le nuage sourit. Il sait maintenant qu’il a des amis.']]},
      {text:'La porte de la maison-fusée s’ouvre. À l’intérieur, les couvertures sont chaudes et la petite étoile chante très bas.',question:'Que font Lumi et Bibi avant de dormir?',choices:[['Un gros câlin 🤗','Le câlin est doux comme un nuage.'],['Une grande respiration 🌬️','Ils inspirent doucement… puis soufflent lentement.']]}
    ],
    en:[
      {text:'The night is gentle on the little moon. Lumi and Bibi follow a glowing path toward their cozy rocket home.',question:'Who is shining above the path?',choices:[['The little star ⭐','The little star yawns and softly lights their steps.'],['The smiling moon 🌙','The moon smiles and lays calm light on the path.']]},
      {text:'In the moon garden, the flowers slowly close their petals. Bibi rolls very quietly so they can sleep.',question:'What color is the sleepiest flower?',choices:[['Purple 💜','The purple flower gives one tiny yawn.'],['Blue 💙','The blue flower snuggles beneath a leaf.']]},
      {text:'A small cloud is afraid to be alone. Lumi holds out a hand and Bibi turns on a round night-light.',question:'What can they say to the little cloud?',choices:[['Good night 🌙','The cloud feels safe and closes its eyes.'],['We are here 💛','The cloud smiles. Now it knows it has friends.']]},
      {text:'The rocket-home door opens. Inside, the blankets are warm and the little star sings very softly.',question:'What do Lumi and Bibi do before sleep?',choices:[['A big cuddle 🤗','The cuddle is as soft as a cloud.'],['One deep breath 🌬️','They breathe in gently… then breathe out slowly.']]}
    ],
    endings:{fr:'Lumi et Bibi se glissent sous leur couverture. La maison-fusée ferme ses petites lumières. Toute la lune se repose. Chut… bonne nuit.',en:'Lumi and Bibi snuggle under their blanket. The rocket home dims its little lights. The whole moon rests. Shhh… good night.'}
  },
  unicorn:{
    fr:[
      {text:'Plume la petite licorne et Lila la luciole suivent un arc-en-ciel endormi jusqu’au château des nuages.',question:'Comment avancent-elles sans réveiller les fleurs?',choices:[['Sur la pointe des sabots 🦄','Plume marche si doucement que les gouttes de rosée restent immobiles.'],['En volant tout bas 🪽','Lila montre un chemin léger juste au-dessus des pétales.']]},
      {text:'Une petite fleur rose bâille au bord du chemin. Ses pétales ont travaillé toute la journée.',question:'Que peut lui dire Plume?',choices:[['Bonne nuit, petite fleur 🌸','La fleur sourit et replie ses pétales.'],['Fais de beaux rêves ✨','La fleur imagine déjà un merveilleux rêve.']]},
      {text:'Un bébé nuage ne retrouve plus sa famille. Plume s’arrête et Lila fait briller sa lumière rose.',question:'Comment peuvent-elles aider le nuage?',choices:[['Suivre la luciole 💡','Le nuage suit la lumière de Lila et retrouve son chemin.'],['Tenir le sabot de Plume 💜','Le bébé nuage se sent courageux près de Plume.']]},
      {text:'Au château, un lit de nuages attend Plume. La lune souriante baisse la lumière du ciel.',question:'Que choisit Plume avant de dormir?',choices:[['Une petite histoire 📖','Lila raconte une histoire avec une voix toute douce.'],['Un câlin de nuage ☁️','Le nuage entoure Plume comme une couverture.']]}
    ],
    en:[
      {text:'Plume the little unicorn and Lila the firefly follow a sleepy rainbow toward the cloud castle.',question:'How do they move without waking the flowers?',choices:[['On tiptoe hooves 🦄','Plume walks so softly that the dew drops stay still.'],['Flying very low 🪽','Lila shows a light path just above the petals.']]},
      {text:'A small pink flower yawns beside the path. Its petals worked hard all day.',question:'What can Plume say to the flower?',choices:[['Good night, little flower 🌸','The flower smiles and folds up its petals.'],['Sweet dreams ✨','The flower is already imagining a wonderful dream.']]},
      {text:'A baby cloud cannot find its family. Plume stops and Lila makes her pink light glow.',question:'How can they help the cloud?',choices:[['Follow the firefly 💡','The cloud follows Lila’s light and finds the way home.'],['Hold Plume’s hoof 💜','The baby cloud feels brave beside Plume.']]},
      {text:'At the castle, a cloud bed is waiting for Plume. The smiling moon turns down the sky lights.',question:'What does Plume choose before sleep?',choices:[['A little story 📖','Lila tells a story in a very soft voice.'],['A cloud cuddle ☁️','The cloud wraps around Plume like a blanket.']]}
    ],
    endings:{fr:'Plume ferme les yeux. Lila devient une minuscule veilleuse rose. Le château flotte doucement sous la lune. Chut… bonne nuit.',en:'Plume closes her eyes. Lila becomes a tiny pink night-light. The castle floats gently beneath the moon. Shhh… good night.'}
  }
};

stories.panda={
  fr:[
    {text:'Ce soir, la forêt de bambous prépare la fête des lanternes. Bao le panda avance tranquillement. Tiko le jeune guépard bondit près de lui et propose une course amicale jusqu’à la lanterne de la colline.',question:'Comment Tiko veut-il commencer?',choices:[['Courir tout de suite! 🐆','Tiko part comme une flèche, pendant que Bao sourit et commence à marcher.'],['S’échauffer doucement 🌿','Tiko étire ses pattes. Bao lui montre comment respirer calmement avant de partir.']]},
    {text:'Tiko disparaît rapidement derrière les bambous. Bao continue pas à pas, en écoutant les grillons et le petit ruisseau qui chante entre les pierres.',question:'Comment Bao traverse-t-il le ruisseau?',choices:[['Sur les pierres rondes 🪨','Bao pose chaque patte avec soin et traverse sans éclabousser les poissons endormis.'],['En suivant les lucioles ✨','Les lucioles dessinent un petit pont de lumière au-dessus des pierres.']]},
    {text:'Plus loin, Tiko s’arrête devant deux sentiers. Il a couru si vite qu’il n’a pas vu le panneau. Bao se rappelle les conseils du vieux hibou.',question:'Quel chemin doivent-ils choisir?',choices:[['Le chemin sous les étoiles ⭐','Bao reconnaît les étoiles dessinées sur les pierres. C’est le bon sentier.'],['Demander au hibou 🦉','Le hibou ouvre un œil et indique gentiment le sentier qui monte.']]},
    {text:'Une pluie très légère commence. Les feuilles brillent et le chemin devient glissant. Tiko baisse les oreilles, car courir est maintenant difficile.',question:'Comment Bao aide-t-il son ami?',choices:[['Partager une grande feuille ☘️','Ils marchent ensemble sous la feuille, au rythme des petites gouttes.'],['Lui proposer de ralentir 🐾','Tiko essaie les petits pas de Bao et se sent tout de suite plus stable.']]},
    {text:'Un bambou tombé bloque le sentier. Tiko pousse très vite, mais le tronc ne bouge pas. Bao place ses pattes contre le bambou et compte doucement.',question:'Comment peuvent-ils déplacer le bambou?',choices:[['Pousser ensemble 🤝','Un, deux, trois… leurs forces réunies font rouler le bambou sur le côté.'],['Chercher un passage 🌱','Bao découvre un passage tranquille sous les feuilles et Tiko l’aide à l’élargir.']]},
    {text:'La colline est proche, mais Tiko est fatigué. Bao reste à ses côtés. Ils entendent déjà le petit carillon de la lanterne au sommet.',question:'Que dit Bao pour encourager Tiko?',choices:[['Un petit pas à la fois 💚','Tiko respire, fait un petit pas, puis un autre. La montée semble plus douce.'],['Nous finirons ensemble 🌙','Tiko sourit. Il n’a plus besoin d’être le premier, seulement d’être avec son ami.']]},
    {text:'Bao et Tiko atteignent la lanterne exactement au même moment. Les animaux de la forêt applaudissent doucement. Tiko comprend que Bao n’était pas le plus rapide, mais qu’il n’a jamais abandonné.',question:'Que font les deux amis avant de rentrer?',choices:[['Ils se disent merci 💛','Tiko remercie Bao pour sa patience, et Bao remercie Tiko pour son courage.'],['Ils regardent la lune 🌕','Assis côte à côte, ils regardent la lune et respirent lentement.']]}
  ],
  en:[
    {text:'Tonight, the bamboo forest is preparing its lantern festival. Bao the panda walks peacefully. Tiko the young cheetah bounces beside him and suggests a friendly race to the hilltop lantern.',question:'How does Tiko want to begin?',choices:[['Run right away! 🐆','Tiko shoots ahead like an arrow while Bao smiles and starts walking.'],['Warm up gently 🌿','Tiko stretches his paws. Bao shows him how to breathe calmly before they begin.']]},
    {text:'Tiko quickly disappears behind the bamboo. Bao continues step by step, listening to the crickets and the little stream singing between the stones.',question:'How does Bao cross the stream?',choices:[['On the round stones 🪨','Bao places each paw carefully and crosses without waking the sleepy fish.'],['By following fireflies ✨','The fireflies draw a tiny bridge of light above the stones.']]},
    {text:'Farther along, Tiko stops where the trail splits in two. He ran so fast that he missed the sign. Bao remembers the old owl’s advice.',question:'Which trail should they choose?',choices:[['The trail under the stars ⭐','Bao recognizes the stars painted on the stones. It is the right trail.'],['Ask the owl 🦉','The owl opens one eye and kindly points toward the climbing trail.']]},
    {text:'A very gentle rain begins. The leaves sparkle and the trail becomes slippery. Tiko lowers his ears because running is difficult now.',question:'How does Bao help his friend?',choices:[['Share a big leaf ☘️','They walk together beneath the leaf to the rhythm of tiny raindrops.'],['Ask him to slow down 🐾','Tiko tries Bao’s little steps and immediately feels steadier.']]},
    {text:'A fallen bamboo blocks the trail. Tiko pushes very quickly, but the trunk does not move. Bao puts his paws against it and counts slowly.',question:'How can they move the bamboo?',choices:[['Push together 🤝','One, two, three… their combined strength rolls the bamboo aside.'],['Find a passage 🌱','Bao discovers a quiet path beneath the leaves and Tiko helps make it wider.']]},
    {text:'The hilltop is close, but Tiko is tired. Bao stays beside him. They can already hear the lantern’s little chime above them.',question:'What does Bao say to encourage Tiko?',choices:[['One small step at a time 💚','Tiko breathes, takes one little step, then another. The climb feels softer.'],['We will finish together 🌙','Tiko smiles. He no longer needs to be first; he only needs to be with his friend.']]},
    {text:'Bao and Tiko reach the lantern at exactly the same moment. The forest animals clap softly. Tiko understands that Bao was not the fastest, but he never gave up.',question:'What do the friends do before going home?',choices:[['They say thank you 💛','Tiko thanks Bao for his patience, and Bao thanks Tiko for his courage.'],['They watch the moon 🌕','Sitting side by side, they watch the moon and breathe slowly.']]}
  ],
  endings:{fr:'Bao et Tiko redescendent ensemble sous les lucioles. La forêt devient silencieuse, les bambous se balancent doucement et la grande lanterne veille sur leurs rêves. Chut… bonne nuit.',en:'Bao and Tiko walk home together beneath the fireflies. The forest grows quiet, the bamboo sways gently, and the great lantern watches over their dreams. Shhh… good night.'}
};

stories.ocean={
  fr:[
    {text:'Sous la lumière de la lune, Mila la petite tortue n’arrive pas encore à dormir. Au loin, Lune la grande baleine fredonne une chanson si douce que les bulles dansent autour d’elle.',question:'Quel son Mila veut-elle écouter en premier?',choices:[['Les petites bulles 🫧','Ploc, ploc, ploc… les bulles montent lentement comme de minuscules notes de musique.'],['Les algues qui se balancent 🌿','Les algues font chuuut, chuuut, comme une couverture qui glisse sur le lit.']]},
    {text:'Mila et Lune décident de recueillir les sons les plus calmes de l’océan. Près du jardin de corail, une bulle musicale est coincée entre deux branches violettes.',question:'Comment peuvent-elles libérer la bulle?',choices:[['Souffler tout doucement 🌬️','Mila souffle un minuscule courant. La bulle se libère et fait ding en tournoyant.'],['Demander au petit crabe 🦀','Le crabe écarte délicatement les branches avec ses pinces et salue la bulle.']]},
    {text:'Plus loin, une famille de poissons-bébés cherche un endroit tranquille pour dormir. Le courant remue encore leurs petites couvertures d’algues.',question:'Comment Mila peut-elle calmer le courant?',choices:[['Nager avec de petits mouvements 🐢','Mila bouge ses nageoires très lentement. Le courant devient doux comme une caresse.'],['Suivre Lune de très près 🐋','Lune nage au ralenti et protège les poissons dans son grand sillage calme.']]},
    {text:'Le chemin passe devant une grotte sombre. Mila hésite un peu. Lune reste près d’elle et les méduses allument leurs veilleuses roses.',question:'Qu’est-ce qui aide Mila à se sentir courageuse?',choices:[['Une coquille lumineuse 🐚','Mila tient la petite coquille. Sa lumière chaude dessine un chemin rassurant.'],['Toucher la nageoire de Lune 💙','Près de son amie, Mila respire doucement et la grotte ne semble plus si grande.']]},
    {text:'Toutes les notes sont maintenant réunies: les bulles, les algues, le courant et les petites veilleuses. Il manque seulement le son qui terminera la berceuse.',question:'Quel dernier son choisissent-elles?',choices:[['Le cœur calme de Lune 💗','Boum… boum… le cœur de Lune donne à la chanson un rythme lent et rassurant.'],['Le tintement de la lune ✨','Un rayon touche les coquillages: ding, ding… toute la mer devient silencieuse pour écouter.']]},
    {text:'Mila rapporte la berceuse jusqu’à sa maison-coquillage. Autour d’elle, les poissons ferment les yeux et les méduses baissent leurs lumières. Lune chante une dernière note.',question:'Que fait Mila avant de s’endormir?',choices:[['Une grande respiration 🌊','Mila inspire lentement… puis souffle une petite bulle qui monte vers la lune.'],['Un câlin à sa couverture 🐚','Mila se blottit dans sa couverture douce et remercie Lune pour la belle aventure.']]}
  ],
  en:[
    {text:'Under the moonlight, Mila the little turtle is not quite ready to sleep. Far away, Lune the great whale hums a song so gentle that bubbles dance around her.',question:'Which sound does Mila want to hear first?',choices:[['The tiny bubbles 🫧','Pop, pop, pop… the bubbles float slowly upward like little music notes.'],['The swaying sea grass 🌿','The sea grass whispers shhh, shhh, like a blanket sliding over a bed.']]},
    {text:'Mila and Lune decide to gather the ocean’s calmest sounds. Near the coral garden, a musical bubble is caught between two purple branches.',question:'How can they free the bubble?',choices:[['Blow very gently 🌬️','Mila blows a tiny current. The bubble comes free and sings ding as it spins.'],['Ask the little crab 🦀','The crab carefully opens the branches with his claws and waves to the bubble.']]},
    {text:'Farther along, a family of baby fish is looking for a quiet place to sleep. The current keeps stirring their little sea-grass blankets.',question:'How can Mila calm the current?',choices:[['Swim with tiny movements 🐢','Mila moves her flippers very slowly. The current becomes as gentle as a cuddle.'],['Stay close behind Lune 🐋','Lune swims slowly and shelters the fish inside her wide, peaceful wake.']]},
    {text:'The path passes a dark cave. Mila hesitates. Lune stays close, and the jellyfish turn on their pink night-lights.',question:'What helps Mila feel brave?',choices:[['A glowing seashell 🐚','Mila holds the little shell. Its warm glow draws a safe path ahead.'],['Touch Lune’s flipper 💙','Beside her friend, Mila breathes gently and the cave no longer feels so big.']]},
    {text:'All the notes are ready now: bubbles, sea grass, the current and tiny night-lights. They need just one final sound to finish the lullaby.',question:'Which last sound do they choose?',choices:[['Lune’s peaceful heartbeat 💗','Thump… thump… Lune’s heart gives the song a slow and comforting rhythm.'],['The moon’s little chime ✨','A moonbeam touches the shells: ding, ding… the whole sea grows quiet to listen.']]},
    {text:'Mila carries the lullaby home to her shell house. Around her, the fish close their eyes and the jellyfish dim their lights. Lune sings one last note.',question:'What does Mila do before falling asleep?',choices:[['Take one deep breath 🌊','Mila breathes in slowly… then blows one small bubble toward the moon.'],['Cuddle her blanket 🐚','Mila snuggles into her soft blanket and thanks Lune for their lovely adventure.']]}
  ],
  endings:{fr:'La berceuse voyage doucement dans tout l’océan. Mila ferme les yeux dans sa maison-coquillage, Lune veille au loin et même les vagues s’endorment. Chut… bonne nuit.',en:'The lullaby drifts gently across the whole ocean. Mila closes her eyes inside her shell home, Lune watches nearby, and even the waves fall asleep. Shhh… good night.'}
};

function audioReady(){if(!soundOn)return;audioContext||=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();return audioContext}
function tone(frequency,delay=0,duration=.14,volume=.08,wave='sine',endFrequency=frequency){
  const ctx=audioReady();if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain(),now=ctx.currentTime+delay;
  o.connect(g);g.connect(ctx.destination);o.type=wave;o.frequency.setValueAtTime(frequency,now);o.frequency.exponentialRampToValueAtTime(Math.max(40,endFrequency),now+duration);
  g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(volume,now+.018);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.start(now);o.stop(now+duration+.02);
}
function stopAmbience(){if(!ambience)return;clearInterval(ambience.timer);ambience.nodes.forEach(node=>{try{node.stop()}catch{}try{node.disconnect()}catch{}});try{ambience.master.disconnect()}catch{}ambience=null}
function ambientNote(frequency,duration=.75,volume=.035){if(!ambience)return;const ctx=audioContext,o=ctx.createOscillator(),g=ctx.createGain(),now=ctx.currentTime;o.type='sine';o.frequency.value=frequency;g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(volume,now+.08);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g);g.connect(ambience.master);o.start(now);o.stop(now+duration+.05)}
function startAmbience(kind='dream'){
  stopAmbience();const ctx=audioReady();if(!ctx)return;const master=ctx.createGain();master.gain.value=kind==='forest'?.032:kind==='ocean'?.027:.024;master.connect(ctx.destination);const nodes=[];
  const buffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.16;const breeze=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),breezeGain=ctx.createGain();breeze.buffer=buffer;breeze.loop=true;filter.type='lowpass';filter.frequency.value=kind==='forest'?760:kind==='ocean'?340:430;breezeGain.gain.value=kind==='forest'?.22:kind==='ocean'?.18:.14;breeze.connect(filter);filter.connect(breezeGain);breezeGain.connect(master);breeze.start();nodes.push(breeze);
  for(const frequency of kind==='forest'?[98,147]:kind==='ocean'?[82,123]:[110,165]){const drone=ctx.createOscillator(),gain=ctx.createGain();drone.type='sine';drone.frequency.value=frequency;gain.gain.value=.035;drone.connect(gain);gain.connect(master);drone.start();nodes.push(drone)}
  ambience={kind,master,nodes,timer:setInterval(()=>{if(kind==='forest'){ambientNote(1900+Math.random()*900,.16,.026);setTimeout(()=>ambientNote(2200+Math.random()*700,.12,.018),180)}else if(kind==='ocean'){ambientNote([262,330,392][Math.floor(Math.random()*3)],1.6,.021);setTimeout(()=>ambientNote(720+Math.random()*260,.22,.012),700)}else{ambientNote([392,523,659][Math.floor(Math.random()*3)],1.25,.025)}},kind==='forest'?3900:kind==='ocean'?4700:5200)};
}
function applause(){
  const ctx=audioReady();if(!ctx)return;
  for(let i=0;i<16;i++){const start=ctx.currentTime+.05+i*.045+Math.random()*.035,buffer=ctx.createBuffer(1,Math.floor(ctx.sampleRate*.055),ctx.sampleRate),data=buffer.getChannelData(0);
    for(let j=0;j<data.length;j++)data[j]=(Math.random()*2-1)*(1-j/data.length);
    const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=buffer;filter.type='bandpass';filter.frequency.value=900+Math.random()*1200;gain.gain.value=.035+Math.random()*.025;
    source.connect(filter);filter.connect(gain);gain.connect(ctx.destination);source.start(start)}
}
function speak(text,calm=false,onDone){
  if(!soundOn||!('speechSynthesis'in window)){if(onDone)setTimeout(onDone,350);return}
  speechSynthesis.cancel();const voice=new SpeechSynthesisUtterance(text);voice.lang=language==='fr'?'fr-CA':'en-CA';voice.pitch=calm?1.08:1.35;voice.rate=calm?.78:.92;voice.volume=.86;
  if(onDone){let finished=false,fallback;const finish=()=>{if(finished)return;finished=true;clearTimeout(fallback);setTimeout(onDone,700)};voice.onend=finish;voice.onerror=finish;fallback=setTimeout(finish,Math.min(15000,Math.max(6500,text.length*130)))}speechSynthesis.speak(voice)
}
function speakPraise(text){speak(text)}
function sound(type='good'){
  if(type==='tap'){tone(430,0,.07,.045,'sine',520);return}if(type==='flip'){tone(330,0,.08,.05,'triangle',520);return}
  if(type==='no'){tone(210,0,.13,.065,'triangle',155);tone(155,.12,.14,.05,'triangle',120);return}
  if(type==='match'){tone(520,0,.1,.065);tone(660,.09,.1,.07);tone(820,.18,.13,.075);return}
  tone(520,0,.12,.075);tone(660,.09,.12,.08);tone(880,.18,.2,.09);
}
function cheer(message){const options=encouragementSets[language];encouragement.textContent=message||options[Math.floor(Math.random()*options.length)];encouragement.classList.remove('show');void encouragement.offsetWidth;encouragement.classList.add('show');setTimeout(()=>encouragement.classList.remove('show'),900)}
function burst(){const icons=theme==='cosmos'?['⭐','✨','💜','💚']:['🌸','✨','💖','🌈'];for(let i=0;i<18;i++){const p=document.createElement('i');p.className='spark';p.textContent=icons[i%icons.length];p.style.setProperty('--x',`${(Math.random()-.5)*520}px`);p.style.setProperty('--y',`${-100-Math.random()*330}px`);p.style.setProperty('--r',`${Math.random()*540-270}deg`);celebration.append(p);setTimeout(()=>p.remove(),1500)}}
function celebrate(){
  stars++;starCount.textContent=stars;starCount.parentElement.classList.remove('score-pop');void starCount.offsetWidth;starCount.parentElement.classList.add('score-pop');
  const praises=praiseSets[language],praise=praises[praiseIndex++%praises.length];rewardTitle.textContent=praise[0];rewardText.textContent=praise[1];rewardIcon.textContent=praise[2];
  sound('good');setTimeout(applause,180);setTimeout(()=>speakPraise(`${praise[0]} ${praise[1]}`),380);celebration.classList.add('show');celebration.setAttribute('aria-hidden','false');burst();
  setTimeout(()=>{celebration.classList.remove('show');celebration.setAttribute('aria-hidden','true');newRound.classList.remove('hidden')},1900);
}
function labels(){return copy[language]}
function cardCopy(game){const base=[...labels().cards[game]];if(game==='memory')base[1]=theme==='cosmos'?(language==='fr'?'Mémoire spatiale':'Space Memory'):(language==='fr'?'Mémoire enchantée':'Enchanted Memory');if(game==='counting'){base[0]=language==='fr'?(theme==='cosmos'?'MISSION ÉTOILES':'MISSION FLEURS'):(theme==='cosmos'?'STAR MISSION':'FLOWER MISSION');base[1]=language==='fr'?(theme==='cosmos'?'Compte les étoiles':'Compte les fleurs'):(theme==='cosmos'?'Count the stars':'Count the flowers')}return base}
function refreshInterface(){
  const t=labels(),data=themeData[theme];document.body.dataset.theme=theme;document.documentElement.lang=language;document.querySelector('#homeLabel').textContent=t.home;document.querySelector('#welcomeKicker').textContent=t.welcomeKicker;document.querySelector('#welcomeTitle').textContent=t.welcomeTitle;document.querySelector('#welcomeText').textContent=t.welcomeText;document.querySelector('#parentNote').textContent=t.parent;document.querySelector('#brandIcon').textContent=data.brandIcon;document.querySelector('#brandName').textContent=data.brand;document.querySelector('#welcomeAvatar').textContent=data.avatar;document.querySelector('#themeIcon').textContent=theme==='cosmos'?'🦄':'🪐';document.querySelector('#themeLabel').textContent=theme==='cosmos'?t.themeUnicorn:t.themeCosmos;languageButton.textContent=language==='fr'?'EN':'FR';languageButton.setAttribute('aria-label',language==='fr'?'English':'Français');themeButton.setAttribute('aria-label',theme==='cosmos'?t.themeUnicorn:t.themeCosmos);
  document.querySelectorAll('[data-game]').forEach(button=>{const game=button.dataset.game,c=cardCopy(game);button.querySelector('.game-icon').textContent=data.icons[game];button.querySelector('b').textContent=c[1];button.querySelector('small').textContent=c[2];button.querySelector('em').textContent=game==='story'?t.listen:t.play});const orbit=theme==='cosmos'?['⭐','🚀','🌈','🪐']:['🌸','🦄','🌈','🦋'];document.querySelectorAll('.celebration-orbit i').forEach((item,i)=>item.textContent=orbit[i]);document.querySelector('.reward em').textContent=data.avatar;newRound.textContent=currentGame==='story'?t.reread:t.again;document.querySelector('#soundButton').setAttribute('aria-label',soundOn?t.soundOn:t.soundOff);
  if(currentGame){const c=cardCopy(currentGame);document.querySelector('#gameKicker').textContent=c[0];document.querySelector('#gameTitle').textContent=c[1]}
}
function openGame(game){currentGame=game;menu.classList.remove('active');play.classList.add('active');const c=cardCopy(game);document.querySelector('#gameKicker').textContent=c[0];document.querySelector('#gameTitle').textContent=c[1];newRound.classList.add('hidden');sound('tap');buildGame();window.scrollTo({top:0,behavior:'smooth'})}
function buildGame(){area.innerHTML='';newRound.classList.add('hidden');newRound.textContent=currentGame==='story'?labels().reread:labels().again;({shapes:buildShapes,memory:buildMemory,counting:buildCounting,pattern:buildPattern,story:buildStory}[currentGame])()}

function buildShapes(){
  instruction.textContent=labels().instructions.shapes;const colors={circle:'#ff6b9d',square:'#62f2d1',triangle:'#ffd760',star:'#9c7bff'},kinds=Object.keys(colors),order=shuffle(kinds);
  area.innerHTML='<div class="shape-board"><div class="pieces"></div><div class="targets"></div></div>';const pieces=area.querySelector('.pieces'),targets=area.querySelector('.targets');let selected=null,matched=0;
  shuffle(kinds).forEach(kind=>{const b=document.createElement('button');b.className='shape';b.dataset.kind=kind;b.setAttribute('aria-label',kind);b.innerHTML=`<span style="background:${colors[kind]}"></span>`;b.onclick=()=>{sound('tap');pieces.querySelectorAll('.shape').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b};pieces.append(b)});
  order.forEach(kind=>{const b=document.createElement('button');b.className='shape target';b.dataset.kind=kind;b.setAttribute('aria-label',`${language==='fr'?'Maison':'Home'} ${kind}`);b.innerHTML=`<span style="background:${colors[kind]};opacity:.25"></span>`;b.onclick=()=>{if(!selected)return;if(selected.dataset.kind===kind){b.classList.add('matched');selected.classList.add('done');selected=null;sound('match');cheer();if(++matched===kinds.length)setTimeout(celebrate,450)}else{sound('no');cheer(labels().retry);b.animate([{transform:'translateX(-7px)'},{transform:'translateX(7px)'},{transform:'none'}],{duration:300})}};targets.append(b)});
}
function buildMemory(){
  instruction.textContent=labels().instructions.memory;let icons,signature,attempts=0;do{icons=shuffle(themeData[theme].memory).slice(0,6);signature=[...icons].sort().join('')}while(signature===lastMemorySignature&&attempts++<8);lastMemorySignature=signature;let open=[],lock=false,pairs=0;const board=document.createElement('div');board.className='memory-board';area.append(board);
  shuffle([...icons,...icons]).forEach(icon=>{const b=document.createElement('button');b.className='memory-card';b.dataset.icon=icon;b.setAttribute('aria-label',language==='fr'?'Carte cachée':'Hidden card');b.textContent=icon;b.onclick=()=>{if(lock||b.classList.contains('open')||b.classList.contains('matched'))return;b.classList.add('open');open.push(b);sound('flip');if(open.length===2){lock=true;if(open[0].dataset.icon===open[1].dataset.icon){open.forEach(x=>x.classList.add('matched'));open=[];lock=false;sound('match');cheer();if(++pairs===icons.length)setTimeout(celebrate,450)}else setTimeout(()=>{open.forEach(x=>x.classList.remove('open'));open=[];lock=false;sound('no');cheer(labels().almost)},700)}};board.append(b)});
}
function buildCounting(){
  instruction.textContent=theme==='cosmos'?labels().instructions.counting:(language==='fr'?'Combien vois-tu de fleurs?':'How many flowers can you see?');const answer=1+Math.floor(Math.random()*7),cloud=document.createElement('div');cloud.className='count-stars';for(let i=0;i<answer;i++){const s=document.createElement('span');s.textContent=themeData[theme].countIcon;s.style.animationDelay=`${i*.06}s`;cloud.append(s)}
  const choices=new Set([answer]);while(choices.size<3)choices.add(1+Math.floor(Math.random()*7));const buttons=document.createElement('div');buttons.className='answers';shuffle([...choices]).forEach(n=>{const b=document.createElement('button');b.className='answer';b.textContent=n;b.onclick=()=>{if(n===answer){b.classList.add('right');buttons.querySelectorAll('button').forEach(x=>x.disabled=true);sound('match');cheer();setTimeout(celebrate,350)}else{sound('no');cheer(labels().countAgain);b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),400)}};buttons.append(b)});area.append(cloud,buttons);
}
function buildPattern(){
  instruction.textContent=labels().instructions.pattern;const sets=themeData[theme].patterns,base=sets[Math.floor(Math.random()*sets.length)],seq=[];for(let i=0;i<5;i++)seq.push(base[i%base.length]);const answer=base[5%base.length],row=document.createElement('div');row.className='pattern-row';seq.forEach(x=>{const s=document.createElement('span');s.className='pattern-item';s.textContent=x;row.append(s)});const q=document.createElement('span');q.className='pattern-question';q.textContent='?';row.append(q);
  const pool=new Set([answer]);themeData[theme].memory.filter(x=>!base.includes(x)).sort(()=>Math.random()-.5).slice(0,2).forEach(x=>pool.add(x));const buttons=document.createElement('div');buttons.className='pattern-answers';shuffle([...pool]).forEach(x=>{const b=document.createElement('button');b.className='answer';b.textContent=x;b.onclick=()=>{if(x===answer){q.textContent=answer;b.classList.add('right');buttons.querySelectorAll('button').forEach(y=>y.disabled=true);sound('match');cheer();setTimeout(celebrate,350)}else{sound('no');cheer(labels().lookAgain);b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),400)}};buttons.append(b)});area.append(row,buttons);
}

function buildStory(){showStoryLibrary()}
function showStoryLibrary(){
  storyVoiceToken++;stopAmbience();if('speechSynthesis'in window)speechSynthesis.cancel();currentStoryKey='';storyStep=0;storyRewarded=false;instruction.textContent=labels().chooseStory;newRound.classList.add('hidden');area.innerHTML='';const library=document.createElement('div');library.className='story-library';const heading=document.createElement('div');heading.className='story-library-heading';heading.innerHTML=`<span>📚</span><h3>${labels().chooseStory}</h3>`;const grid=document.createElement('div');grid.className='story-library-grid';const choices=[{key:'theme',title:theme==='cosmos'?labels().cosmosStory:labels().unicornStory,description:labels().shortStory,image:themeData[theme].storyImage,icon:theme==='cosmos'?'🌙':'🦄'},{key:'panda',title:labels().pandaTitle,description:`${labels().longStory}<br>${labels().pandaDesc}`,image:'assets/cosmo-kids/bedtime-panda-cheetah-v1.png',icon:'🐼'},{key:'ocean',title:labels().oceanTitle,description:`${labels().mediumStory}<br>${labels().oceanDesc}`,image:'assets/cosmo-kids/bedtime-ocean-v1.png',icon:'🐢'}];choices.forEach(choice=>{const button=document.createElement('button');button.className='story-pick';button.innerHTML=`<img src="${choice.image}" alt=""><span><em>${choice.icon}</em><b></b><small></small></span>`;button.querySelector('b').textContent=choice.title;button.querySelector('small').innerHTML=choice.description;button.onclick=()=>{sound('tap');startStory(choice.key)};grid.append(button)});library.append(heading,grid);area.append(library)
}
function activeStory(){return currentStoryKey==='theme'?stories[theme]:stories[currentStoryKey]}
function activeStoryImage(){return currentStoryKey==='theme'?themeData[theme].storyImage:currentStoryKey==='panda'?'assets/cosmo-kids/bedtime-panda-cheetah-v1.png':'assets/cosmo-kids/bedtime-ocean-v1.png'}
function storyAmbienceKind(){return currentStoryKey==='panda'?'forest':currentStoryKey==='ocean'?'ocean':'dream'}
function startStory(key){currentStoryKey=key;storyStep=0;storyRewarded=false;newRound.classList.add('hidden');startAmbience(storyAmbienceKind());renderStory()}
function rewardStory(ending){
  if(storyRewarded)return;storyRewarded=true;stars++;starCount.textContent=stars;starCount.parentElement.classList.remove('score-pop');void starCount.offsetWidth;starCount.parentElement.classList.add('score-pop');tone(392,0,.35,.035,'sine',523);tone(523,.28,.5,.03,'sine',659);setTimeout(()=>speak(ending,true),250);newRound.textContent=labels().reread;newRound.classList.remove('hidden');
}
function renderStory(){
  clearTimeout(renderStory.advance);clearTimeout(renderStory.voice);const renderToken=++storyVoiceToken;instruction.textContent=labels().instructions.story;const story=activeStory(),pages=story[language],image=activeStoryImage();area.innerHTML='';const book=document.createElement('div');book.className='story-book';const pictureWrap=document.createElement('div');pictureWrap.className='story-picture-wrap';const picture=document.createElement('img');picture.className='story-picture';picture.src=image;picture.alt=currentStoryKey==='panda'?(language==='fr'?'Bao le panda et Tiko le guépard dans la forêt de bambous':'Bao the panda and Tiko the cheetah in the bamboo forest'):theme==='cosmos'?(language==='fr'?'Lumi et Bibi dans un jardin lunaire':'Lumi and Bibi in a moon garden'):(language==='fr'?'Plume et Lila sur le chemin arc-en-ciel':'Plume and Lila on the rainbow path');const progress=document.createElement('div');progress.className='story-progress';progress.textContent=pages.map((_,i)=>i<storyStep?'●':i===storyStep?'◉':'○').join(' ');pictureWrap.append(picture,progress);const page=document.createElement('div');page.className='story-page';book.append(pictureWrap,page);area.append(book);
  if(currentStoryKey==='ocean')picture.alt=language==='fr'?'Mila la tortue et Lune la baleine dans un océan endormi':'Mila the turtle and Lune the whale in a sleepy ocean';
  if(storyStep>=pages.length){const ending=story.endings[language],endIcon=currentStoryKey==='panda'?'🐼':currentStoryKey==='ocean'?'🐢':theme==='cosmos'?'🌙':'🦄';progress.textContent=pages.map(()=>'●').join(' ');page.innerHTML=`<div class="story-ending"><span>${endIcon}</span><h3>${labels().goodNight}</h3><p></p><em class="story-rest">${currentStoryKey==='panda'?'🐾 💤 🎋':currentStoryKey==='ocean'?'🫧 💤 🐋':theme==='cosmos'?'✨ 💤 🪐':'🌙 💤 🌈'}</em><button class="story-another">${labels().anotherStory}</button></div>`;page.querySelector('p').textContent=ending;page.querySelector('.story-another').onclick=showStoryLibrary;instruction.textContent=labels().goodNight;rewardStory(ending);return}
  const chapter=pages[storyStep],listen=document.createElement('button');listen.className='story-listen';listen.type='button';listen.textContent=labels().read;listen.onclick=()=>speak(chapter.text,true);const text=document.createElement('p');text.className='story-text';text.textContent=chapter.text;const question=document.createElement('div');question.className='story-question';const prompt=document.createElement('b');prompt.textContent=chapter.question;const choices=document.createElement('div');choices.className='story-choices';chapter.choices.forEach(([choice,response])=>{const button=document.createElement('button');button.className='story-choice';button.textContent=choice;button.onclick=()=>{choices.querySelectorAll('button').forEach(x=>x.disabled=true);button.classList.add('selected');sound('match');const answer=document.createElement('p');answer.className='story-response';answer.setAttribute('aria-live','polite');answer.textContent=response;const cue=document.createElement('p');cue.className='story-turn-cue waiting';cue.textContent=labels().listening;question.append(answer,cue);let pageReady=false;const advance=event=>{if(!pageReady||renderToken!==storyVoiceToken)return;if(event?.target?.closest?.('.story-listen'))return;pageReady=false;book.classList.remove('ready-to-turn');sound('flip');book.classList.add('page-turning');renderStory.advance=setTimeout(()=>{if(renderToken!==storyVoiceToken)return;storyStep++;renderStory()},420)};book.addEventListener('click',advance);book.addEventListener('keydown',event=>{if(pageReady&&(event.key==='Enter'||event.key===' ')){event.preventDefault();advance(event)}});const ready=()=>{if(renderToken!==storyVoiceToken)return;pageReady=true;choices.classList.add('answered');listen.disabled=true;cue.textContent=labels().turnPage;cue.classList.remove('waiting');cue.classList.add('ready');book.classList.add('ready-to-turn');book.tabIndex=0;book.setAttribute('aria-label',labels().turnPage)};speak(response,true,ready)};choices.append(button)});question.append(prompt,choices);page.append(listen,text,question);renderStory.voice=setTimeout(()=>speak(chapter.text,true),350);
}

document.querySelectorAll('[data-game]').forEach(button=>button.addEventListener('click',()=>openGame(button.dataset.game)));
document.querySelector('#backButton').onclick=()=>{sound('tap');clearTimeout(renderStory.advance);clearTimeout(renderStory.voice);if('speechSynthesis'in window)speechSynthesis.cancel();if(currentGame==='story'&&currentStoryKey){showStoryLibrary();return}stopAmbience();play.classList.remove('active');menu.classList.add('active');area.innerHTML='';currentGame='';refreshInterface()};
document.querySelector('#soundButton').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'🔊':'🔇';e.currentTarget.setAttribute('aria-label',soundOn?labels().soundOn:labels().soundOff);if(soundOn){sound('match');cheer(labels().soundsOn);if(currentGame==='story'&&currentStoryKey)startAmbience(storyAmbienceKind())}else{stopAmbience();if('speechSynthesis'in window)speechSynthesis.cancel()}};
themeButton.onclick=()=>{theme=theme==='cosmos'?'unicorn':'cosmos';sound('tap');refreshInterface();if(play.classList.contains('active'))buildGame()};
languageButton.onclick=()=>{language=language==='fr'?'en':'fr';sound('tap');refreshInterface();if(play.classList.contains('active')){if(currentGame==='story'){if(currentStoryKey)renderStory();else showStoryLibrary()}else buildGame()}};
newRound.onclick=()=>{sound('tap');if(currentGame==='story'&&currentStoryKey)startStory(currentStoryKey);else buildGame()};
refreshInterface();
