(()=>{'use strict';
const $=selector=>document.querySelector(selector);
const canvas=$('#mazeCanvas'),ctx=canvas.getContext('2d'),startScreen=$('#startScreen'),startButton=$('#startButton'),sectorScreen=$('#sectorScreen'),sectorButton=$('#sectorButton'),timerEl=$('#timer'),distanceEl=$('#distanceLabel'),dragHint=$('#dragHint'),objective=$('#objective'),levelLabel=$('#levelLabel'),mapLabel=$('#mapLabel'),nerveFill=$('#nerveFill'),soundToggle=$('#soundToggle'),scareToggle=$('#scareToggle'),jumpScare=$('#jumpScare'),scareMessage=$('#scareMessage'),motionShadow=$('#motionShadow');
const SECTORS=[
  {name:'CONTAINMENT SPINE',cells:10,loops:2,hue:166,scare:19,copy:'The emergency airlock is still transmitting.'},
  {name:'CRYO GUTTERS',cells:12,loops:4,hue:188,scare:17,copy:'Something thawed before you arrived.'},
  {name:'NURSERY VEINS',cells:13,loops:5,hue:104,scare:15,copy:'Do not answer the sounds behind the walls.'},
  {name:'ECHO INTAKE',cells:14,loops:7,hue:278,scare:14,copy:'Your footsteps are no longer the only footsteps.'},
  {name:'BLACK HIVE',cells:15,loops:8,hue:344,scare:12,copy:'The ship has stopped pretending to be empty.'},
  {name:'QUEEN AIRLOCK',cells:17,loops:10,hue:48,scare:10,copy:'One final signal. One final living maze.'}
];
const scareLines=['IT FOUND YOU','DON’T TURN AROUND','THE WALLS ARE WATCHING','YOU ARE NOT ALONE','KEEP MOVING'];
const state={active:false,scaring:false,map:[],width:0,height:0,player:{x:1.5,y:1.5,r:.2},exit:{x:1.5,y:1.5},keys:new Set(),pointer:null,input:{x:0,y:0},startedAt:0,lastTime:0,missionSeed:919,level:0,nextScare:0,nextShadow:0,nerve:100,shakeUntil:0,lastStep:0,soundOn:true,scaresOn:true,completed:false};
const audio={ac:null,master:null,compressor:null,effects:null,music:null,drones:[],timer:null,beat:0};

function seeded(seed){let value=seed>>>0;return()=>((value=Math.imul(value^value>>>15,1|value),value^=value+Math.imul(value^value>>>7,61|value)),((value^value>>>14)>>>0)/4294967296)}
function generateMaze(cells,seed,loops){const random=seeded(seed),size=cells*2+1,map=Array.from({length:size},()=>Array(size).fill(1)),stack=[[1,1]];map[1][1]=0;while(stack.length){const [x,y]=stack[stack.length-1],next=[[2,0],[-2,0],[0,2],[0,-2]].map(([dx,dy])=>[x+dx,y+dy,dx,dy]).filter(([nx,ny])=>nx>0&&ny>0&&nx<size-1&&ny<size-1&&map[ny][nx]===1);if(!next.length){stack.pop();continue}const [nx,ny,dx,dy]=next[Math.floor(random()*next.length)];map[y+dy/2][x+dx/2]=0;map[ny][nx]=0;stack.push([nx,ny])}let opened=0;while(opened<loops){const x=2+Math.floor(random()*(size-4)),y=2+Math.floor(random()*(size-4));if(map[y][x]!==1)continue;const horizontal=map[y][x-1]===0&&map[y][x+1]===0,vertical=map[y-1][x]===0&&map[y+1][x]===0;if(horizontal||vertical){map[y][x]=0;opened++}}state.map=map;state.width=size;state.height=size;state.player.x=1.5;state.player.y=1.5;const far=findFarthest(1,1);state.exit={x:far.x+.5,y:far.y+.5}}
function findFarthest(sx,sy){const queue=[[sx,sy,0]],seen=new Set([`${sx},${sy}`]);let far={x:sx,y:sy,d:0};for(let i=0;i<queue.length;i++){const [x,y,d]=queue[i];if(d>far.d)far={x,y,d};for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,key=`${nx},${ny}`;if(state.map[ny]?.[nx]===0&&!seen.has(key)){seen.add(key);queue.push([nx,ny,d+1])}}}return far}
function resize(){const rect=canvas.getBoundingClientRect(),scale=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(rect.width*scale));canvas.height=Math.max(1,Math.floor(rect.height*scale));ctx.setTransform(scale,0,0,scale,0,0)}
function solidAt(x,y){return y<0||x<0||y>=state.height||x>=state.width||state.map[Math.floor(y)][Math.floor(x)]===1}
function canOccupy(x,y){const r=state.player.r;return !solidAt(x-r,y-r)&&!solidAt(x+r,y-r)&&!solidAt(x-r,y+r)&&!solidAt(x+r,y+r)}
function movementVector(){let x=(state.keys.has('ArrowRight')||state.keys.has('KeyD')?1:0)-(state.keys.has('ArrowLeft')||state.keys.has('KeyA')?1:0)+state.input.x,y=(state.keys.has('ArrowDown')||state.keys.has('KeyS')?1:0)-(state.keys.has('ArrowUp')||state.keys.has('KeyW')?1:0)+state.input.y;const length=Math.hypot(x,y);if(length>.05){x/=Math.max(1,length);y/=Math.max(1,length)}return{x,y,length}}
function move(dt,time){const vector=movementVector();if(vector.length<=.05)return;const speed=(2.6+state.level*.07)*dt,nx=state.player.x+vector.x*speed,ny=state.player.y+vector.y*speed;if(canOccupy(nx,state.player.y))state.player.x=nx;if(canOccupy(state.player.x,ny))state.player.y=ny;if(time-state.lastStep>390-state.level*18){state.lastStep=time;effect('step')}}
function wallColour(x,y,time){const sector=SECTORS[state.level],pulse=.5+.5*Math.sin(time*.001+x*.7+y*.43),light=6+Math.floor(pulse*3);return `hsl(${sector.hue} 34% ${light}%)`}
function drawDirectionArrow(px,py,tile,time){const angle=Math.atan2(state.exit.y-state.player.y,state.exit.x-state.player.x);ctx.save();ctx.translate(px,py);ctx.rotate(angle);ctx.shadowBlur=14;ctx.shadowColor='#a9ff49';ctx.fillStyle=`rgba(169,255,73,${.55+Math.sin(time*.006)*.2})`;ctx.beginPath();ctx.moveTo(tile*.42,0);ctx.lineTo(tile*.25,-tile*.1);ctx.lineTo(tile*.25,tile*.1);ctx.closePath();ctx.fill();ctx.restore()}
function draw(time){const w=canvas.clientWidth,h=canvas.clientHeight,tile=Math.max(50,Math.min(82,Math.min(w,h)/7.7)),shake=time<state.shakeUntil?10:0,cameraX=state.player.x*tile-w/2+(Math.random()-.5)*shake,cameraY=state.player.y*tile-h/2+(Math.random()-.5)*shake,minX=Math.max(0,Math.floor(cameraX/tile)-1),maxX=Math.min(state.width,Math.ceil((cameraX+w)/tile)+1),minY=Math.max(0,Math.floor(cameraY/tile)-1),maxY=Math.min(state.height,Math.ceil((cameraY+h)/tile)+1),sector=SECTORS[state.level];ctx.clearRect(0,0,w,h);ctx.fillStyle='#010405';ctx.fillRect(0,0,w,h);
  for(let y=minY;y<maxY;y++)for(let x=minX;x<maxX;x++){const px=x*tile-cameraX,py=y*tile-cameraY;if(state.map[y][x]){ctx.fillStyle=wallColour(x,y,time);ctx.fillRect(px-.5,py-.5,tile+1,tile+1);ctx.strokeStyle=`hsla(${sector.hue} 90% 65% / .06)`;ctx.lineWidth=1;ctx.strokeRect(px+4,py+4,tile-8,tile-8);if((x*17+y*31)%9===0){ctx.strokeStyle=`hsla(${sector.hue} 90% 62% / ${.07+.04*Math.sin(time*.002+x)})`;ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(px+tile*.12,py+tile*.86);ctx.bezierCurveTo(px+tile*.62,py+tile*.08,px+tile*.3,py+tile*.2,px+tile*.88,py+tile*.08);ctx.stroke()}}else{ctx.fillStyle=(x+y)%2?'#071314':'#081718';ctx.fillRect(px,py,tile,tile);ctx.strokeStyle='rgba(112,255,230,.045)';ctx.strokeRect(px,py,tile,tile);if((x*13+y*7)%17===0){ctx.fillStyle=`hsla(${sector.hue} 80% 60% / ${.09+.05*Math.sin(time*.003+x)})`;ctx.beginPath();ctx.arc(px+tile*.5,py+tile*.5,2+Math.sin(time*.004+y),0,Math.PI*2);ctx.fill()}}}
  const ex=state.exit.x*tile-cameraX,ey=state.exit.y*tile-cameraY,portal=20+Math.sin(time*.005)*5;ctx.save();ctx.shadowBlur=35;ctx.shadowColor='#a9ff49';ctx.strokeStyle='#a9ff49';ctx.lineWidth=4;ctx.beginPath();ctx.arc(ex,ey,portal,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='rgba(112,255,230,.55)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(ex,ey,portal+10,-time*.001,-time*.001+Math.PI*1.25);ctx.stroke();ctx.restore();
  const px=w/2,py=h/2;drawDirectionArrow(px,py,tile,time);ctx.save();ctx.shadowBlur=30;ctx.shadowColor='#70ffe6';ctx.fillStyle='#b9fff3';ctx.beginPath();ctx.arc(px,py,tile*.15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#102d2b';ctx.beginPath();ctx.ellipse(px-4,py-2,2,4,0,0,Math.PI*2);ctx.ellipse(px+4,py-2,2,4,0,0,Math.PI*2);ctx.fill();ctx.restore();
  if(state.pointer){const ox=state.pointer.x-canvas.getBoundingClientRect().left,oy=state.pointer.y-canvas.getBoundingClientRect().top,dx=state.input.x*58,dy=state.input.y*58;ctx.save();ctx.strokeStyle='rgba(112,255,230,.35)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(ox,oy,38,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(169,255,73,.42)';ctx.beginPath();ctx.arc(ox+dx,oy+dy,12,0,Math.PI*2);ctx.fill();ctx.restore()}
  const gradient=ctx.createRadialGradient(px,py,tile*.58,px,py,tile*4.3);gradient.addColorStop(0,'rgba(0,0,0,0)');gradient.addColorStop(.52,'rgba(0,0,0,.12)');gradient.addColorStop(1,`hsla(${sector.hue} 45% 2% / .97)`);ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h)}

function tickEvents(time){if(!state.active||state.scaring)return;if(time>state.nextShadow){showShadow();state.nextShadow=time+6500+Math.random()*6500}if(state.scaresOn&&time>state.nextScare){triggerScare();state.nextScare=time+(SECTORS[state.level].scare+Math.random()*8)*1000}}
function showShadow(){const angle=Math.random()*Math.PI*2,distance=130+Math.random()*180;motionShadow.style.setProperty('--shadow-x',`${Math.cos(angle)*distance}px`);motionShadow.style.setProperty('--shadow-y',`${Math.sin(angle)*distance}px`);motionShadow.style.setProperty('--shadow-scale',`${.65+Math.random()*.8}`);motionShadow.classList.remove('vanish');motionShadow.classList.add('show');effect('whisper');setTimeout(()=>motionShadow.classList.add('vanish'),650);setTimeout(()=>motionShadow.classList.remove('show','vanish'),1500)}
function triggerScare(){state.scaring=true;state.nerve=Math.max(12,state.nerve-(15+state.level*2));nerveFill.style.transform=`scaleX(${state.nerve/100})`;state.shakeUntil=performance.now()+850;scareMessage.textContent=scareLines[Math.floor(Math.random()*scareLines.length)];jumpScare.classList.add('show');jumpScare.setAttribute('aria-hidden','false');effect('scare');navigator.vibrate?.([90,40,140]);setTimeout(()=>{jumpScare.classList.remove('show');jumpScare.setAttribute('aria-hidden','true');state.scaring=false;objective.textContent='MOVE. IT HEARD YOU.';setTimeout(()=>{if(state.active)objective.textContent=SECTORS[state.level].copy},1900)},680)}
function tick(time){const dt=Math.min(.04,(time-state.lastTime)/1000||0);state.lastTime=time;if(state.active&&!state.scaring){move(dt,time);state.nerve=Math.min(100,state.nerve+dt*.48);nerveFill.style.transform=`scaleX(${state.nerve/100})`;const elapsed=Math.floor((performance.now()-state.startedAt)/1000);timerEl.textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`;const distance=Math.hypot(state.exit.x-state.player.x,state.exit.y-state.player.y);distanceEl.textContent=`EXIT SIGNAL: ${Math.ceil(distance*4)}M`;if(distance<.45)completeSector();tickEvents(time)}draw(time);requestAnimationFrame(tick)}

function audioReady(){if(!state.soundOn)return null;if(!audio.ac){audio.ac=new(window.AudioContext||window.webkitAudioContext)();audio.master=audio.ac.createGain();audio.master.gain.value=1.18;audio.compressor=audio.ac.createDynamicsCompressor();audio.compressor.threshold.value=-18;audio.compressor.knee.value=22;audio.compressor.ratio.value=6;audio.compressor.attack.value=.004;audio.compressor.release.value=.24;audio.effects=audio.ac.createGain();audio.effects.gain.value=2.25;audio.music=audio.ac.createGain();audio.music.gain.value=1.8;audio.effects.connect(audio.compressor);audio.music.connect(audio.compressor);audio.compressor.connect(audio.master);audio.master.connect(audio.ac.destination)}if(audio.ac.state==='suspended')audio.ac.resume();return audio.ac}
function tone(frequency,duration=.15,volume=.04,type='sine',slide=.72,delay=0,bus=audio.effects){const ac=audioReady();if(!ac||!bus)return;const oscillator=ac.createOscillator(),gain=ac.createGain(),at=ac.currentTime+delay;oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,at);oscillator.frequency.exponentialRampToValueAtTime(Math.max(30,frequency*slide),at+duration);gain.gain.setValueAtTime(Math.max(.0001,volume),at);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);oscillator.connect(gain);gain.connect(bus);oscillator.start(at);oscillator.stop(at+duration+.03)}
function noise(duration=.1,volume=.03,cutoff=900,delay=0){const ac=audioReady();if(!ac)return;const buffer=ac.createBuffer(1,Math.ceil(ac.sampleRate*duration),ac.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,2);const source=ac.createBufferSource(),filter=ac.createBiquadFilter(),gain=ac.createGain(),at=ac.currentTime+delay;source.buffer=buffer;filter.type=cutoff<600?'lowpass':'bandpass';filter.frequency.value=cutoff;filter.Q.value=1.1;gain.gain.setValueAtTime(volume,at);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);source.connect(filter);filter.connect(gain);gain.connect(audio.effects);source.start(at)}
function effect(kind){if(!state.soundOn)return;if(kind==='step'){noise(.055,.016,240);tone(82,.06,.012,'sine',.58);return}if(kind==='whisper'){noise(.5,.017,780);tone(145,.55,.018,'sine',.45);return}if(kind==='door'){[196,293,440,659].forEach((note,index)=>tone(note,.48,.036,'triangle',1.35,index*.08));noise(.32,.03,1550);return}if(kind==='scare'){noise(.62,.13,1600);noise(.5,.11,270);tone(74,.72,.15,'sawtooth',.25);tone(980,.4,.09,'square',.18,.02);return}if(kind==='start'){tone(120,.7,.045,'sine',1.8);tone(240,.5,.025,'triangle',1.4,.14)}}
function startAmbience(){stopAmbience();const ac=audioReady();if(!ac)return;const root=[42,47,39,52,35,31][state.level];for(const [frequency,type,volume]of[[root,'sine',.025],[root*1.49,'sawtooth',.006],[root*2.02,'triangle',.007]]){const oscillator=ac.createOscillator(),filter=ac.createBiquadFilter(),gain=ac.createGain();oscillator.type=type;oscillator.frequency.value=frequency;filter.type='lowpass';filter.frequency.value=type==='sine'?180:320;gain.gain.value=volume;oscillator.connect(filter);filter.connect(gain);gain.connect(audio.music);oscillator.start();audio.drones.push({oscillator,gain})}audio.timer=setInterval(()=>{if(!state.active||!state.soundOn)return;const urgency=1-state.nerve/100;tone(62,.12,.018+urgency*.028,'sine',.65,0,audio.music);if(++audio.beat%2===0)tone(82,.09,.012+urgency*.018,'triangle',.7,.17,audio.music)},860-state.level*45)}
function stopAmbience(){clearInterval(audio.timer);audio.timer=null;if(!audio.ac)return;const now=audio.ac.currentTime;for(const drone of audio.drones){try{drone.gain.gain.exponentialRampToValueAtTime(.0001,now+.25);drone.oscillator.stop(now+.3)}catch{}}audio.drones=[]}

function startSector(level){state.level=level;const sector=SECTORS[level];generateMaze(sector.cells,state.missionSeed+level*7919,sector.loops);state.active=true;state.scaring=false;state.completed=false;state.startedAt=performance.now();state.lastTime=performance.now();state.nextScare=performance.now()+(sector.scare+Math.random()*5)*1000;state.nextShadow=performance.now()+4500+Math.random()*4000;state.nerve=100;nerveFill.style.transform='scaleX(1)';timerEl.textContent='00:00';levelLabel.textContent=sector.name;mapLabel.textContent=`MAP ${String(level+1).padStart(2,'0')} / ${String(SECTORS.length).padStart(2,'0')}`;objective.textContent=sector.copy;sectorScreen.classList.add('hidden');startScreen.classList.add('hidden');dragHint.style.opacity='1';startAmbience();effect('start')}
function completeSector(){if(state.completed)return;state.completed=true;state.active=false;state.input.x=state.input.y=0;stopAmbience();effect('door');navigator.vibrate?.(80);const final=state.level===SECTORS.length-1;$('#sectorKicker').textContent=final?'VESSEL ESCAPED':`SECTOR ${String(state.level+1).padStart(2,'0')} SURVIVED`;$('#sectorTitle').textContent=final?'YOU LEFT SOMETHING BEHIND':'THE SHIP GOES DEEPER';$('#sectorText').textContent=final?'Six living labyrinths survived. The rescue beacon answers—but something is breathing inside your suit.':`Next: ${SECTORS[state.level+1].name}. The maze is larger, darker, and less empty.`;sectorButton.textContent=final?'BEGIN A NEW DESCENT':'DESCEND TO THE NEXT SECTOR';sectorScreen.classList.remove('hidden')}
function beginCampaign(){state.missionSeed=Date.now()&0xffffffff;startSector(0)}
function pointerVector(event){if(!state.pointer)return;const dx=event.clientX-state.pointer.x,dy=event.clientY-state.pointer.y,length=Math.hypot(dx,dy),limit=70;if(length<8){state.input.x=state.input.y=0;return}state.input.x=dx/Math.max(limit,length);state.input.y=dy/Math.max(limit,length);dragHint.style.opacity='.12'}
canvas.addEventListener('pointerdown',event=>{if(!state.active)return;audioReady();event.preventDefault();canvas.setPointerCapture?.(event.pointerId);state.pointer={id:event.pointerId,x:event.clientX,y:event.clientY};pointerVector(event)});canvas.addEventListener('pointermove',event=>{if(state.pointer?.id===event.pointerId){event.preventDefault();pointerVector(event)}});function release(event){if(state.pointer?.id!==event.pointerId)return;state.pointer=null;state.input.x=state.input.y=0}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
addEventListener('keydown',event=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(event.code))event.preventDefault();state.keys.add(event.code);if(state.active)audioReady()});addEventListener('keyup',event=>state.keys.delete(event.code));addEventListener('resize',resize);
startButton.onclick=beginCampaign;sectorButton.onclick=()=>{if(state.level===SECTORS.length-1){state.missionSeed=Date.now()&0xffffffff;startSector(0)}else startSector(state.level+1)};
soundToggle.onclick=()=>{state.soundOn=!state.soundOn;soundToggle.setAttribute('aria-pressed',String(state.soundOn));soundToggle.textContent=state.soundOn?'◖)) SOUND':'◖)) MUTED';if(state.soundOn){audioReady();if(state.active)startAmbience();effect('start')}else stopAmbience()};
scareToggle.onclick=()=>{state.scaresOn=!state.scaresOn;scareToggle.setAttribute('aria-pressed',String(state.scaresOn));scareToggle.textContent=state.scaresOn?'☠ SCARES':'☠ SAFE';if(!state.scaresOn){jumpScare.classList.remove('show');state.scaring=false}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAmbience();else if(state.active&&state.soundOn)startAmbience()});
generateMaze(SECTORS[0].cells,919,SECTORS[0].loops);resize();requestAnimationFrame(tick);
})();
