(()=>{'use strict';
const core=window.XenoSudokuCore,$=selector=>document.querySelector(selector),boardEl=$('#board'),padEl=$('#numberPad'),messageEl=$('#message'),launch=$('#launchScreen'),map=$('#missionMap'),repair=$('#repairScreen'),victory=$('#victoryScreen');
const SAVE='xenoSudokuSaveV1',PROGRESS='xenoSudokuProgressV1',AUDIO='xenoSudokuAudioV1';
let mission=core.generateMission(1),values=[],notes=[],selected=-1,history=[],mistakes=0,hints=3,elapsed=0,startedAt=0,running=false,notesMode=false,soundOn=localStorage.getItem(AUDIO)!=='off',timerHandle=0,audioCtx=null,ambientTimer=0;
let progress=loadJSON(PROGRESS,{completed:{},best:{}});
function loadJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
function formatTime(seconds){const safe=Math.max(0,Math.floor(seconds));return`${String(Math.floor(safe/60)).padStart(2,'0')}:${String(safe%60).padStart(2,'0')}`}
function peers(a,b){const ar=Math.floor(a/9),ac=a%9,br=Math.floor(b/9),bc=b%9;return ar===br||ac===bc||Math.floor(ar/3)===Math.floor(br/3)&&Math.floor(ac/3)===Math.floor(bc/3)}
function currentElapsed(){return elapsed+(running?Math.floor((Date.now()-startedAt)/1000):0)}
function sound(kind){if(!soundOn)return;const fx=window.DanArcadeFX;if(kind==='select')fx?.play('magic',{enabled:soundOn,volume:.075,rate:1.45,cooldown:45});if(kind==='correct')fx?.play('magic',{enabled:soundOn,volume:.16,rate:1.08,cooldown:55});if(kind==='wrong')fx?.play('metal',{enabled:soundOn,volume:.22,rate:.72,cooldown:70});if(kind==='hint')fx?.play('door',{enabled:soundOn,volume:.13,rate:1.5,duration:.45});if(kind==='victory'){fx?.play('cheer',{enabled:soundOn,volume:.3,duration:2.7});fx?.hit(boardEl,'#baff68',1)}tone(kind)}
function tone(kind){try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const sets={select:[[540,.05,.025]],correct:[[520,.12,.045],[780,.18,.035]],wrong:[[115,.22,.055]],hint:[[440,.18,.035],[880,.35,.025]],victory:[[392,.5,.05],[523,.6,.05],[659,.7,.045],[784,.8,.04]]}[kind]||[];for(const[f,d,v]of sets){const o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime;o.type=kind==='wrong'?'sawtooth':'sine';o.frequency.value=f;g.gain.setValueAtTime(v,now);g.gain.exponentialRampToValueAtTime(.0001,now+d);o.connect(g);g.connect(audioCtx.destination);o.start(now);o.stop(now+d+.02)}}catch{}}
function startAmbience(){clearInterval(ambientTimer);if(!soundOn)return;ambientTimer=setInterval(()=>{if(!running||!soundOn)return;tone(Math.random()>.5?'select':'hint')},6200)}
function save(){if(!running)return;localStorage.setItem(SAVE,JSON.stringify({level:mission.level,values,notes:notes.map(set=>[...set]),mistakes,hints,elapsed:currentElapsed()}))}
function clearSave(){localStorage.removeItem(SAVE)}
function snapshot(){history.push({values:[...values],notes:notes.map(set=>new Set(set)),mistakes,hints});if(history.length>80)history.shift()}
function restoreSnapshot(state){values=[...state.values];notes=state.notes.map(set=>new Set(set));mistakes=state.mistakes;hints=state.hints;render()}
function firstOpen(){return values.findIndex((value,index)=>!mission.puzzle[index]&&!value)}
function setMessage(text,type=''){messageEl.textContent=text;messageEl.className=`message ${type}`}
function startMission(level,stored=null){mission=core.generateMission(level);values=stored?.values?.length===81?[...stored.values]:[...mission.puzzle];notes=stored?.notes?.length===81?stored.notes.map(list=>new Set(list)):Array.from({length:81},()=>new Set());mistakes=stored?.mistakes||0;hints=stored?.hints??3;elapsed=stored?.elapsed||0;startedAt=Date.now();running=true;notesMode=false;history=[];selected=firstOpen();launch.classList.remove('show');map.classList.remove('show');repair.classList.remove('show');victory.classList.remove('show');updateMissionUI();render();startTimer();startAmbience();save();setMessage('ALIEN GRID SYNCHRONIZED','good');sound('select')}
function startTimer(){clearInterval(timerHandle);$('#timer').textContent=formatTime(currentElapsed());timerHandle=setInterval(()=>{$('#timer').textContent=formatTime(currentElapsed());if(Date.now()%5000<1000)save()},1000)}
function updateMissionUI(){const info=mission,$badge=$('#sectorBadge');$('#missionLabel').textContent=`MISSION ${String(info.level).padStart(2,'0')} / 36`;$('#missionTitle').textContent=info.title;$badge.textContent=`${info.sector.name} · ${info.sector.difficulty}`;$badge.style.color=info.sector.color;$('#campaignFill').style.width=`${info.level/36*100}%`;$('#bestTime').textContent=progress.best[info.level]?formatTime(progress.best[info.level]):'—';$('#notesButton').setAttribute('aria-pressed',String(notesMode));$('#notesButton span').textContent=notesMode?'NOTES ON':'NOTES OFF'}
function render(){boardEl.innerHTML='';const selectedValue=selected>=0?values[selected]:0;for(let i=0;i<81;i++){const button=document.createElement('button'),value=values[i];button.className='cell';button.dataset.index=i;button.setAttribute('role','gridcell');button.setAttribute('aria-label',`Row ${Math.floor(i/9)+1}, column ${i%9+1}${value?`, ${value}`:', empty'}`);if(mission.puzzle[i])button.classList.add('fixed');if(i===selected)button.classList.add('selected');else if(selected>=0&&peers(i,selected))button.classList.add('peer');if(selectedValue&&value===selectedValue)button.classList.add('same');if(value&&value!==mission.solution[i])button.classList.add('error');if(value){button.textContent=value}else if(notes[i].size){const grid=document.createElement('span');grid.className='notes';for(let n=1;n<=9;n++){const mark=document.createElement('i');mark.textContent=notes[i].has(n)?n:'';grid.append(mark)}button.append(grid)}button.onclick=()=>selectCell(i);boardEl.append(button)}
  const counts=Array(10).fill(0);values.forEach((value,index)=>{if(value===mission.solution[index])counts[value]++});padEl.querySelectorAll('button').forEach((button,index)=>button.classList.toggle('complete',counts[index+1]===9));$('#filledCount').textContent=`${values.filter(Boolean).length} / 81`;$('#integrity').textContent=`${Math.max(0,100-mistakes*17)}%`;$('#shield').textContent=Array.from({length:3},(_,i)=>i<3-mistakes?'●':'○').join(' ');$('#hintCount').textContent=hints;$('#hintButton').disabled=hints<=0;updateMissionUI()}
function selectCell(index){selected=index;sound('select');render();if(mission.puzzle[index])setMessage('ANCIENT GLYPH · LOCKED');else setMessage(values[index]?'SIGNAL SELECTED':'EMPTY SIGNAL CHAMBER')}
function clearPeerNotes(index,value){for(let i=0;i<81;i++)if(peers(i,index))notes[i].delete(value)}
function enter(value){if(!running||selected<0||mission.puzzle[selected])return;snapshot();if(notesMode&&!values[selected]){notes[selected].has(value)?notes[selected].delete(value):notes[selected].add(value);sound('select');setMessage(`NOTE ${value} ${notes[selected].has(value)?'STORED':'REMOVED'}`);render();save();return}values[selected]=value;notes[selected].clear();if(value===mission.solution[selected]){clearPeerNotes(selected,value);sound('correct');setMessage('SIGNAL ACCEPTED','good');pulseCompletedUnits(selected);if(values.every((entry,index)=>entry===mission.solution[index]))completeMission()}else{mistakes++;sound('wrong');window.DanArcadeFX?.shake(boardEl,.65);setMessage('SIGNAL REJECTED · SHIELD DAMAGED','bad');if(mistakes>=3){const frozen=currentElapsed();save();running=false;elapsed=frozen;clearInterval(timerHandle);setTimeout(()=>repair.classList.add('show'),350)}}render();save()}
function erase(){if(!running||selected<0||mission.puzzle[selected])return;snapshot();values[selected]=0;notes[selected].clear();sound('select');setMessage('SIGNAL ERASED');render();save()}
function undo(){const prior=history.pop();if(!prior){setMessage('NO EARLIER SIGNAL STORED');return}restoreSnapshot(prior);sound('select');setMessage('TIMELINE RESTORED');save()}
function hint(){if(!running||hints<=0)return;let index=selected;if(index<0||mission.puzzle[index]||values[index]===mission.solution[index]){const choices=values.map((value,i)=>!mission.puzzle[i]&&value!==mission.solution[i]?i:-1).filter(i=>i>=0);index=choices[Math.floor(Math.random()*choices.length)]}if(index==null||index<0)return;snapshot();selected=index;values[index]=mission.solution[index];notes[index].clear();clearPeerNotes(index,values[index]);hints--;sound('hint');setMessage('OVERMIND HINT TRANSMITTED','good');render();const cell=boardEl.children[index];cell?.classList.add('hinted','pulse');window.DanArcadeFX?.burst(cell,'#ffbd59',14);if(values.every((entry,i)=>entry===mission.solution[i]))completeMission();save()}
function pulseCompletedUnits(index){const row=Math.floor(index/9),col=index%9,boxRow=Math.floor(row/3)*3,boxCol=Math.floor(col/3)*3,units=[Array.from({length:9},(_,i)=>row*9+i),Array.from({length:9},(_,i)=>i*9+col),Array.from({length:9},(_,i)=>(boxRow+Math.floor(i/3))*9+boxCol+i%3)];for(const unit of units)if(unit.every(i=>values[i]===mission.solution[i])){unit.forEach(i=>boardEl.children[i]?.classList.add('pulse'));window.DanArcadeFX?.burst(boardEl.children[index],'#baff68',12)}}
function completeMission(){const finalElapsed=currentElapsed();running=false;elapsed=finalElapsed;clearInterval(timerHandle);clearInterval(ambientTimer);progress.completed[mission.level]=true;if(!progress.best[mission.level]||elapsed<progress.best[mission.level])progress.best[mission.level]=elapsed;localStorage.setItem(PROGRESS,JSON.stringify(progress));clearSave();window.DanArcadeScores?.record('xeno-sudoku.html',Math.max(1,mission.level*1000000-elapsed*100-mistakes*10000),`MISSION ${String(mission.level).padStart(2,'0')} · ${formatTime(elapsed)}`,mission.sector.difficulty);sound('victory');$('#victoryStats').textContent=`MISSION ${String(mission.level).padStart(2,'0')} · ${mission.sector.difficulty} · ${formatTime(elapsed)} · ${3-mistakes} BIO-SHIELDS REMAINING`;setTimeout(()=>victory.classList.add('show'),700)}
function repairShield(){values=values.map((value,index)=>value&&value!==mission.solution[index]?0:value);mistakes=0;running=true;startedAt=Date.now();repair.classList.remove('show');startTimer();startAmbience();render();save();setMessage('BIO-SHIELD RESTORED · CONTINUE','good');sound('hint')}
function restart(){if(!confirm('Restart this mission and erase its current entries?'))return;startMission(mission.level)}
function openMap(){buildMissionGrid();map.classList.add('show')}
function buildMissionGrid(){const grid=$('#missionGrid');grid.innerHTML='';for(let level=1;level<=36;level++){const info=core.missionInfo(level),button=document.createElement('button');button.className='mission-node';if(progress.completed[level])button.classList.add('done');if(level===mission.level)button.classList.add('current');button.style.setProperty('--node',info.sector.color);button.innerHTML=`<span>${String(level).padStart(2,'0')}</span><small>${info.sector.difficulty}</small>`;button.onclick=()=>startMission(level);grid.append(button)}}
function buildSectorChoices(){const wrap=$('#sectorChoices');wrap.innerHTML='';for(const sector of core.SECTORS){const done=Array.from({length:9},(_,i)=>sector.start+i).filter(level=>progress.completed[level]).length,button=document.createElement('button');button.className='sector-choice';button.style.setProperty('--sector',sector.color);button.innerHTML=`<b>${sector.difficulty}</b><small>${sector.name}<br>${done}/9 COMPLETE</small>`;button.onclick=()=>{const first=Array.from({length:9},(_,i)=>sector.start+i).find(level=>!progress.completed[level])||sector.start;startMission(first)};wrap.append(button)}}
function initPad(){for(let value=1;value<=9;value++){const button=document.createElement('button');button.textContent=value;button.setAttribute('aria-label',`Enter ${value}`);button.onclick=()=>enter(value);padEl.append(button)}}
function toggleSound(){soundOn=!soundOn;localStorage.setItem(AUDIO,soundOn?'on':'off');$('#soundButton').setAttribute('aria-pressed',String(soundOn));$('#soundButton').textContent=soundOn?'◖)) SOUND':'◖)) MUTED';if(soundOn){sound('correct');startAmbience()}else{clearInterval(ambientTimer);audioCtx?.suspend?.()}}
function keydown(event){if(map.classList.contains('show')||launch.classList.contains('show')||repair.classList.contains('show')||victory.classList.contains('show'))return;if(/^[1-9]$/.test(event.key)){enter(Number(event.key));return}if(event.key==='Backspace'||event.key==='Delete'||event.key==='0'){erase();return}if(event.key.toLowerCase()==='n'){notesMode=!notesMode;render();return}if(event.key.toLowerCase()==='h'){hint();return}if(selected<0)return;const row=Math.floor(selected/9),col=selected%9;if(event.key==='ArrowLeft')selected=row*9+(col+8)%9;else if(event.key==='ArrowRight')selected=row*9+(col+1)%9;else if(event.key==='ArrowUp')selected=((row+8)%9)*9+col;else if(event.key==='ArrowDown')selected=((row+1)%9)*9+col;else return;event.preventDefault();render()}
$('#soundButton').onclick=toggleSound;$('#missionsButton').onclick=openMap;$('#mapFromLaunch').onclick=openMap;$('#victoryMapButton').onclick=openMap;$('#closeMap').onclick=()=>map.classList.remove('show');$('#newMissionButton').onclick=restart;$('#undoButton').onclick=undo;$('#eraseButton').onclick=erase;$('#hintButton').onclick=hint;$('#notesButton').onclick=()=>{notesMode=!notesMode;sound('select');render();setMessage(notesMode?'MICRO-NOTES ACTIVE':'DIRECT INPUT ACTIVE')};$('#repairButton').onclick=repairShield;$('#nextMissionButton').onclick=()=>startMission(mission.level===36?1:mission.level+1);document.addEventListener('keydown',keydown);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});
initPad();buildSectorChoices();const stored=loadJSON(SAVE,null),requestedDifficulty=new URLSearchParams(location.search).get('difficulty'),requestedLevel=({easy:1,medium:10,hard:19,expert:28})[requestedDifficulty];$('#continueButton').disabled=false;$('#continueButton').textContent=requestedLevel?`BEGIN ${requestedDifficulty.toUpperCase()} MISSION`:stored?`CONTINUE MISSION ${String(stored.level).padStart(2,'0')}`:'BEGIN MISSION 01';$('#continueButton').onclick=()=>requestedLevel?startMission(requestedLevel):stored?startMission(stored.level,stored):startMission(1);mission=core.generateMission(requestedLevel||stored?.level||1);values=[...mission.puzzle];notes=Array.from({length:81},()=>new Set());selected=firstOpen();updateMissionUI();render();
})();
